import { describe, expect, it } from "vitest";
import { formatFeeLine, handlingFeeFor, totalWithFee, type Order } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`: the whole point of Replace Command with
 * Function is that the thing computing the fee changes shape - a class in the challenge,
 * a function in the solution. So this suite imports only the three callers -
 * `handlingFeeFor`, `formatFeeLine`, `totalWithFee` - and never the calculator by name.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function order(overrides: Partial<Order> = {}): Order {
  return {
    seatCount: 2,
    pricePerSeatPounds: 40,
    hoursUntilShowtime: 48,
    ...overrides,
  };
}

describe("handlingFeeFor", () => {
  it("charges a base fee plus a flat amount per seat, outside the rush window", () => {
    expect(handlingFeeFor(order({ seatCount: 4, hoursUntilShowtime: 48 }))).toBe(8);
  });

  // Guards the rush window's boundary - the surcharge applies strictly inside it, not
  // exactly on the edge, a detail an inequality flip could silently invert.
  it("adds the rush surcharge only strictly inside the booking window", () => {
    expect(handlingFeeFor(order({ seatCount: 1, hoursUntilShowtime: 24 }))).toBe(3.5);
    expect(handlingFeeFor(order({ seatCount: 1, hoursUntilShowtime: 23 }))).toBe(8.5);
  });

  // Guards against capping the base fee and the rush surcharge separately, rather than
  // capping the combined total - the two would agree everywhere except this case.
  it("lets the rush surcharge push a fee into the cap that seat count alone would not", () => {
    expect(handlingFeeFor(order({ seatCount: 8, hoursUntilShowtime: 23 }))).toBe(19);
    expect(handlingFeeFor(order({ seatCount: 9, hoursUntilShowtime: 23 }))).toBe(20);
  });

  // Guards the cap itself, for a group large enough that nothing else in the formula
  // would naturally stop the fee from climbing.
  it("never charges past the maximum fee, however large the group", () => {
    expect(handlingFeeFor(order({ seatCount: 50, hoursUntilShowtime: 48 }))).toBe(20);
  });
});

describe("formatFeeLine", () => {
  // Guards the display formatting - both the currency mark and always showing two
  // decimal places, even for a fee that lands on a whole pound.
  it("formats the fee to two decimal places with the currency mark", () => {
    expect(formatFeeLine(order({ seatCount: 2, hoursUntilShowtime: 48 }))).toBe(
      "Handling fee: £5.00",
    );
  });

  // Guards against the rounded/formatted string quietly becoming the value other callers
  // compute from, instead of formatting stopping at display.
  it("still shows a fractional fee to the exact penny, not rounded to a whole pound", () => {
    expect(formatFeeLine(order({ seatCount: 1, hoursUntilShowtime: 23 }))).toBe(
      "Handling fee: £8.50",
    );
  });
});

describe("totalWithFee", () => {
  // Guards against the total silently becoming the fee alone, dropping the seat subtotal.
  it("adds the handling fee on top of the seat subtotal, not in place of it", () => {
    const theOrder = order({
      seatCount: 3,
      pricePerSeatPounds: 40,
      hoursUntilShowtime: 48,
    });
    expect(totalWithFee(theOrder)).toBe(126.5);
  });
});
