import { describe, expect, it } from "vitest";
import { InstrumentRental, receiptLine, RoomBooking, totalBookingCents } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of extracting Bookable. Do not edit this file: if a
 * refactoring seems to require changing a test, either the refactoring changed behaviour
 * or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Extract Superclass could silently change -
 * not one per method. Each test names the move it is guarding against.
 */

describe("InstrumentRental", () => {
  // Guards the shared cost formula: rate times units, rounded to the cent.
  it("charges the daily rate times the number of days rented", () => {
    const rental = new InstrumentRental({
      instrumentName: "Cello #4",
      category: "Cello",
      rentalDays: 3,
      dailyRateCents: 799,
      studentName: "Priya",
    });
    expect(rental.costCents()).toBe(2397);
  });

  // Boundary: singular vs plural in the day count, on either side of one - the description
  // is not part of the pulled-up formula, and an over-eager merge could drag it along anyway.
  it("describes a one-day rental in the singular", () => {
    const rental = new InstrumentRental({
      instrumentName: "Violin #2",
      category: "Violin",
      rentalDays: 1,
      dailyRateCents: 500,
      studentName: "Ada",
    });
    expect(rental.bookingDescription()).toBe("Violin rental for Ada: Violin #2 (1 day)");
  });

  // Guards lateFeeCents staying independent of the instrument's own rate. If a shared
  // superclass method absorbed this, a cheap and an expensive rental would diverge here.
  it("charges the same flat late fee regardless of the instrument's own rate", () => {
    const cheap = new InstrumentRental({
      instrumentName: "Recorder #9",
      category: "Recorder",
      rentalDays: 1,
      dailyRateCents: 50,
      studentName: "Kai",
    });
    const pricey = new InstrumentRental({
      instrumentName: "Cello #4",
      category: "Cello",
      rentalDays: 1,
      dailyRateCents: 799,
      studentName: "Priya",
    });
    expect(cheap.lateFeeCents(2)).toBe(pricey.lateFeeCents(2));
    expect(cheap.lateFeeCents(2)).toBe(1000);
  });
});

describe("RoomBooking", () => {
  // Guards the same cost formula holding for a room, sharing costCents with InstrumentRental.
  it("charges the hourly rate times the number of hours booked", () => {
    const booking = new RoomBooking({
      roomName: "Room A",
      capacity: 4,
      bookedHours: 2,
      hourlyRateCents: 1250,
      studentName: "Leila",
    });
    expect(booking.costCents()).toBe(2500);
  });

  // Boundary: a fractional session rounds to the nearest cent, not truncates.
  it("rounds a fractional-hour booking to the nearest cent", () => {
    const booking = new RoomBooking({
      roomName: "Studio 2",
      capacity: 2,
      bookedHours: 1.5,
      hourlyRateCents: 999,
      studentName: "Nora",
    });
    // 1498.5 rounds up.
    expect(booking.costCents()).toBe(1499);
  });

  // Guards lateFeeCents staying tied to the room's own rate and rounding up to a whole
  // hour, the opposite shape from InstrumentRental's flat fee - collapsing the two into one
  // implementation would make this test and the instrument's late-fee test agree, which they
  // must not.
  it("bills an overrun at the room's own hourly rate, rounded up to the next hour", () => {
    const small = new RoomBooking({
      roomName: "Room A",
      capacity: 4,
      bookedHours: 2,
      hourlyRateCents: 800,
      studentName: "A",
    });
    const large = new RoomBooking({
      roomName: "Room B",
      capacity: 10,
      bookedHours: 2,
      hourlyRateCents: 2000,
      studentName: "B",
    });
    expect(small.lateFeeCents(0.5)).toBe(800);
    expect(large.lateFeeCents(0.5)).toBe(2000);
  });
});

describe("receiptLine", () => {
  // Guards the polymorphic call working through the extracted Bookable type, plural case.
  it("renders an instrument rental's description and cost together", () => {
    const rental = new InstrumentRental({
      instrumentName: "Violin #2",
      category: "Violin",
      rentalDays: 2,
      dailyRateCents: 500,
      studentName: "Ada",
    });
    expect(receiptLine(rental)).toBe("Violin rental for Ada: Violin #2 (2 days): $10.00");
  });

  // Guards the same polymorphic call for the other Bookable subclass.
  it("renders a room booking's description and cost together", () => {
    const booking = new RoomBooking({
      roomName: "Room B",
      capacity: 6,
      bookedHours: 1,
      hourlyRateCents: 900,
      studentName: "Marco",
    });
    expect(receiptLine(booking)).toBe(
      "Room booking for Marco: Room B (1h, seats 6): $9.00",
    );
  });
});

describe("totalBookingCents", () => {
  // Boundary: an empty list bills nothing, not NaN from an empty reduce.
  it("is zero for no bookings", () => {
    expect(totalBookingCents([])).toBe(0);
  });

  // Guards summation working across mixed Bookable subtypes through one shared method call -
  // the whole point of pulling costCents up onto Bookable.
  it("sums costs across a mix of instrument rentals and room bookings", () => {
    const rental = new InstrumentRental({
      instrumentName: "Violin #2",
      category: "Violin",
      rentalDays: 2,
      dailyRateCents: 500,
      studentName: "Ada",
    });
    const booking = new RoomBooking({
      roomName: "Room A",
      capacity: 4,
      bookedHours: 2,
      hourlyRateCents: 1250,
      studentName: "Leila",
    });
    expect(totalBookingCents([rental, booking])).toBe(1000 + 2500);
  });
});
