import { describe, expect, it } from "vitest";
import { priceRegistrationLine } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * Prices are in whole cents. The desk line is `name|distance|membership|promo`, and the
 * last two fields may be missing entirely on a short line.
 */

describe("priceRegistrationLine", () => {
  it("charges the plain base fee when nobody qualifies for a discount", () => {
    const charge = priceRegistrationLine("Bruno Costa|5K|GUEST|");
    expect(charge).toEqual({
      runnerName: "Bruno Costa",
      baseFeeCents: 1500,
      memberDiscountCents: 0,
      promoDiscountCents: 0,
      totalCents: 1500,
    });
  });

  it("takes 15% off the base fee for a member, with no promo involved", () => {
    const charge = priceRegistrationLine("Ana Ferreira|5K|MEMBER|");
    // 15% of 1500 is exact here.
    expect(charge.memberDiscountCents).toBe(225);
    expect(charge.totalCents).toBe(1275);
  });

  // Guards against truncating instead of rounding when the discount lands on a
  // fraction of a cent - the FUN fee is chosen so 15% does not divide evenly.
  it("rounds a fractional member discount instead of truncating it", () => {
    const charge = priceRegistrationLine("Priya Shah|FUN|MEMBER|");
    // 399 * 0.15 = 59.85, which rounds up to 60, not down to 59.
    expect(charge.memberDiscountCents).toBe(60);
    expect(charge.totalCents).toBe(339);
  });

  // Guards the order of operations: the early-bird discount must be capped by what is
  // still owed *after* the member discount, not by the base fee. Reordering the two
  // discounts would leave a few cents owing here instead of zero.
  it("caps the early-bird discount at the post-member subtotal, never below zero", () => {
    const charge = priceRegistrationLine("Priya Shah|FUN|MEMBER|EARLY");
    expect(charge.memberDiscountCents).toBe(60);
    // Capped, not the full 500.
    expect(charge.promoDiscountCents).toBe(339);
    expect(charge.totalCents).toBe(0);
  });

  // Same cap, isolated from the member discount, so a fix to one path can't hide behind
  // the other.
  it("caps the early-bird discount at the base fee for a non-member too", () => {
    const charge = priceRegistrationLine("Zoe Almeida|FUN|GUEST|EARLY");
    expect(charge.promoDiscountCents).toBe(399);
    expect(charge.totalCents).toBe(0);
  });

  // Guards against computing the member discount from the post-promo subtotal instead
  // of the base fee. Same inputs as the next test, minus membership - the two totals
  // must differ by exactly the member discount on the *base*, not on a reduced amount.
  it("applies the member percentage to the base fee, not to the discounted subtotal", () => {
    const member = priceRegistrationLine("Marcos Lima|10K|MEMBER|EARLY");
    // 15% of 2200.
    expect(member.memberDiscountCents).toBe(330);
    // The subtotal (1870) easily covers the flat discount.
    expect(member.promoDiscountCents).toBe(500);
    expect(member.totalCents).toBe(1370);
  });

  it("gives a guest the full flat early-bird discount when the subtotal covers it", () => {
    const guest = priceRegistrationLine("Celia Nunes|10K|GUEST|EARLY");
    expect(guest.promoDiscountCents).toBe(500);
    expect(guest.totalCents).toBe(1700);
  });

  // Guards which phase owns validation: an unrecognised distance is a pricing failure
  // (no entry in the price list), not something the parser should silently accept or
  // reject on its own.
  it("rejects a distance the price list does not recognise", () => {
    expect(() => priceRegistrationLine("Ines Rocha|15K|GUEST|")).toThrow(
      "Unknown distance: 15K",
    );
  });

  // Guards against assuming every line has all four fields. A desk line with no
  // membership or promo field at all must default to guest, no promo - not throw.
  it("treats missing trailing fields as guest with no promo", () => {
    const charge = priceRegistrationLine("Joao Pedro|HALF");
    expect(charge.memberDiscountCents).toBe(0);
    expect(charge.promoDiscountCents).toBe(0);
    expect(charge.totalCents).toBe(4000);
  });

  // Guards against the case-normalising trim/uppercase logic leaking onto the name
  // field, which must survive verbatim once its own surrounding whitespace is trimmed.
  it("is case- and whitespace-tolerant on the coded fields, but leaves the name alone", () => {
    const charge = priceRegistrationLine("  PRIYA shah  |  10k  |  Member  |  early  ");
    expect(charge.runnerName).toBe("PRIYA shah");
    expect(charge.totalCents).toBe(1370);
  });
});
