import { describe, expect, it } from "vitest";
import {
  closeStandingOrder,
  completeRouteStop,
  reprintReceipt,
  type WholesaleOrder,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of moving the total computation into the shared receipt
 * builder. Do not edit this file: if a refactoring seems to require changing a test,
 * either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Move Statements into Function could
 * silently change - not one per caller. Each test names the move it is guarding against.
 */

const bramble: WholesaleOrder = {
  id: "WO-1042",
  customerName: "Bramble Café",
  routeName: "North Loop",
  items: [
    { name: "Sourdough Loaf", quantity: 12, unitPriceCents: 650 },
    { name: "Cinnamon Roll", quantity: 18, unitPriceCents: 300 },
  ],
  creditCents: 500,
};

const cornerDiner: WholesaleOrder = {
  id: "WO-2087",
  customerName: "Corner Diner",
  routeName: "Harbor Loop",
  items: [{ name: "Baguette", quantity: 1, unitPriceCents: 1205 }],
  creditCents: 0,
};

const testKitchenSupply: WholesaleOrder = {
  id: "WO-3099",
  customerName: "Test Kitchen Supply",
  routeName: "Harbor Loop",
  items: [],
  creditCents: 0,
};

const blueDoor: WholesaleOrder = {
  id: "WO-4021",
  customerName: "Blue Door Cafe",
  routeName: "North Loop",
  items: [{ name: "Rye Loaf", quantity: 2, unitPriceCents: 700 }],
  creditCents: 1300,
};

const millerStreet: WholesaleOrder = {
  id: "WO-5050",
  customerName: "Miller Street Cafe",
  routeName: "Harbor Loop",
  items: [{ name: "Rye Loaf", quantity: 1, unitPriceCents: 400 }],
  creditCents: 400,
};

const fernwayGrocer: WholesaleOrder = {
  id: "WO-6061",
  customerName: "Fernway Grocer",
  routeName: "South Ridge",
  items: [
    { name: "Walnut Bread", quantity: 5, unitPriceCents: 480 },
    { name: "Apple Danish", quantity: 10, unitPriceCents: 275 },
    { name: "Baguette", quantity: 3, unitPriceCents: 405 },
  ],
  creditCents: 65,
};

describe("completeRouteStop", () => {
  // Guards the header, the item block, and the total staying in that order, and the
  // credit actually being subtracted, once the shared prelude lands inside the function.
  it("renders the header, each item line, the credited total, then the stop's own line", () => {
    expect(completeRouteStop(bramble)).toEqual([
      "Ashgrove Bakery Co-op — Order WO-1042",
      "Deliver to: Bramble Café, North Loop route",
      "  12 x Sourdough Loaf — $78.00",
      "  18 x Cinnamon Roll — $54.00",
      "Total: $127.00",
      "Signed for at the door.",
    ]);
  });
});

describe("closeStandingOrder", () => {
  // Boundary: a single-digit cents remainder. A move that rebuilds the template by hand
  // instead of reusing the formatter could easily drop the leading zero.
  it("pads a single-digit cents remainder with a leading zero", () => {
    expect(closeStandingOrder(cornerDiner)).toEqual([
      "Ashgrove Bakery Co-op — Order WO-2087",
      "Deliver to: Corner Diner, Harbor Loop route",
      "  1 x Baguette — $12.05",
      "Total: $12.05",
      "Filed with this week's invoice packet.",
    ]);
  });

  // Guards item order and per-item arithmetic surviving the move: three items, given in
  // an order a sort would disturb, each needing its own quantity x price line.
  it("keeps items in the order given and prices each one independently", () => {
    expect(closeStandingOrder(fernwayGrocer)).toEqual([
      "Ashgrove Bakery Co-op — Order WO-6061",
      "Deliver to: Fernway Grocer, South Ridge route",
      "  5 x Walnut Bread — $24.00",
      "  10 x Apple Danish — $27.50",
      "  3 x Baguette — $12.15",
      "Total: $63.00",
      "Filed with this week's invoice packet.",
    ]);
  });
});

describe("reprintReceipt", () => {
  // Boundary: no items at all. Guards against a stray blank line where the item block
  // would otherwise have gone.
  it("prints just the header and a zero total for an order with no items", () => {
    expect(reprintReceipt(testKitchenSupply)).toEqual([
      "Ashgrove Bakery Co-op — Order WO-3099",
      "Deliver to: Test Kitchen Supply, Harbor Loop route",
      "Total: $0.00",
      "REPRINT",
    ]);
  });

  // Boundary: the credit exactly equals the subtotal. This is the one caller whose
  // pre-refactor copy of the total math never floored a negative result - at exactly
  // zero there is nothing for a floor to do, so this passes on both sides of the move.
  it("floors the total at exactly zero when the credit exactly covers the subtotal", () => {
    expect(reprintReceipt(millerStreet)).toEqual([
      "Ashgrove Bakery Co-op — Order WO-5050",
      "Deliver to: Miller Street Cafe, Harbor Loop route",
      "  1 x Rye Loaf — $4.00",
      "Total: $0.00",
      "REPRINT",
    ]);
  });
});

describe("all three callers", () => {
  // Guards the precondition this refactoring depends on: given the same order, every
  // caller must compute the same total. Only the trailing line - which stays on the
  // caller, not the shared function - is allowed to differ.
  it("agree on the total for the same order, and differ only in their own trailing line", () => {
    const stop = completeRouteStop(blueDoor);
    const standing = closeStandingOrder(blueDoor);
    const reprint = reprintReceipt(blueDoor);

    expect(stop.slice(0, -1)).toEqual(standing.slice(0, -1));
    expect(standing.slice(0, -1)).toEqual(reprint.slice(0, -1));
    expect(stop.at(-1)).toBe("Signed for at the door.");
    expect(standing.at(-1)).toBe("Filed with this week's invoice packet.");
    expect(reprint.at(-1)).toBe("REPRINT");
  });
});
