import { describe, expect, it } from "vitest";
import { priceOrderCents, type Customer, type Order, type OrderItem } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every branch you delete. Do not edit this file: if deleting dead code seems
 * to require changing a test, either the code was not dead or the exercise is wrong.
 *
 * There is one test per behaviour a plausible dead-code sweep could silently change - not
 * one per branch. Each test names the move it is guarding against.
 */

function customer(yearsActive: number): Customer {
  return { id: "CUST-1", name: "Test Cafe", yearsActive };
}

const dozenSourdough: readonly OrderItem[] = [
  { productName: "Sourdough loaf", unitPriceCents: 650, quantity: 12 },
];

describe("priceOrderCents", () => {
  it("charges the full subtotal for a newer account with no promo code", () => {
    const order: Order = { id: "ORD-1", customer: customer(2), items: dozenSourdough };
    expect(priceOrderCents(order)).toBe(7800);
  });

  // Guards the FOUNDER-RATE branch a customer reaches through tenure alone, never through
  // a typed-in code. Grepping this file for a call site that passes the literal
  // "FOUNDER-RATE" as an argument finds nothing - the string only ever appears inside
  // effectivePromoCode and promoDiscountCents themselves. Deleting either of them on that
  // evidence breaks this test.
  it("grants the founder rate automatically once a customer reaches five years, with no promo code entered", () => {
    const order: Order = { id: "ORD-2", customer: customer(5), items: dozenSourdough };
    expect(priceOrderCents(order)).toBe(6630);
  });

  // Boundary just below the tenure fallback. A `>` in place of `>=` would pass every other
  // test here and still be wrong.
  it("withholds the founder rate one year short of the five-year mark", () => {
    const order: Order = { id: "ORD-3", customer: customer(4), items: dozenSourdough };
    expect(priceOrderCents(order)).toBe(7800);
  });

  // A back-office correction can still set promoCode by hand even though the checkout
  // form no longer offers the field. Guards against making tenure a requirement instead
  // of one of two independent ways into the same discount.
  it("lets an explicitly entered promo code grant the founder rate even for a brand-new account", () => {
    const order: Order = {
      id: "ORD-4",
      customer: customer(0),
      items: dozenSourdough,
      promoCode: "FOUNDER-RATE",
    };
    expect(priceOrderCents(order)).toBe(6630);
  });

  // Guards the precedence between the two sources: an explicit code that doesn't match
  // must not fall through to the tenure default, even for a customer who would otherwise
  // qualify for it.
  it("gives no discount for an unrecognized promo code, even from a long-standing customer", () => {
    const order: Order = {
      id: "ORD-5",
      customer: customer(10),
      items: dozenSourdough,
      promoCode: "SPRING-MARKET",
    };
    expect(priceOrderCents(order)).toBe(7800);
  });

  // Guards against a reduce that overwrites instead of accumulates across multiple items.
  it("sums every item's unit price times quantity before applying any discount", () => {
    const items: readonly OrderItem[] = [
      { productName: "Sourdough loaf", unitPriceCents: 650, quantity: 12 },
      { productName: "Cinnamon roll", unitPriceCents: 325, quantity: 6 },
    ];
    const order: Order = { id: "ORD-6", customer: customer(0), items };
    expect(priceOrderCents(order)).toBe(9750);
  });

  // Boundary: the discount rounds to the nearest cent rather than truncating.
  // 2999 * 0.15 = 449.85, which rounds to 450, not 449.
  it("rounds the founder-rate discount to the nearest cent instead of truncating", () => {
    const items: readonly OrderItem[] = [
      { productName: "Custom order", unitPriceCents: 2999, quantity: 1 },
    ];
    const order: Order = {
      id: "ORD-7",
      customer: customer(1),
      items,
      promoCode: "FOUNDER-RATE",
    };
    expect(priceOrderCents(order)).toBe(2549);
  });

  // Boundary: an order with no items still prices at zero, including for a customer whose
  // tenure would otherwise trigger the founder rate - there is simply nothing to discount.
  it("prices an order with no items at zero, even for an eligible long-standing customer", () => {
    const order: Order = { id: "ORD-8", customer: customer(10), items: [] };
    expect(priceOrderCents(order)).toBe(0);
  });
});
