import { describe, expect, it } from "vitest";
import { invoiceLine, priceTerm, totalFeeCents } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of replacing the term-length subclasses with a delegate.
 * Do not edit this file: if a refactoring seems to require changing a test, either the
 * refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Replace Subclass with Delegate could
 * silently change - not one per branch. Each test names the move it is guarding against.
 */

describe("priceTerm", () => {
  // Guards the standard-term numbers themselves surviving the move off a dedicated class.
  it("prices a standard term for an adult at the full rate", () => {
    const pricing = priceTerm({ length: "standard", category: "adult" });
    expect(pricing.sessionsPerTerm()).toBe(10);
    expect(pricing.termFeeCents()).toBe(44990);
  });

  // Guards the child discount - one branch of the switch this drill collapses to one copy.
  it("takes a flat discount off a standard term for a child", () => {
    const pricing = priceTerm({ length: "standard", category: "child" });
    expect(pricing.termFeeCents()).toBe(41990);
  });

  // Boundary: the concession discount is a percentage that lands on a half-cent here.
  // Rounds half away from zero, so this pins Math.round's direction, not just its use.
  it("rounds a standard term's concession discount to the nearest cent", () => {
    const pricing = priceTerm({ length: "standard", category: "concession" });
    expect(pricing.termFeeCents()).toBe(38241);
  });

  // Guards the intensive-term numbers, on the other side of the length axis.
  it("prices an intensive term for an adult at the full rate", () => {
    const pricing = priceTerm({ length: "intensive", category: "adult" });
    expect(pricing.sessionsPerTerm()).toBe(4);
    expect(pricing.termFeeCents()).toBe(36000);
  });

  // The same discount switch, exercised through the other length - this is the test that
  // would fail first if collapsing the duplicated switch left one copy behind the other.
  it("takes the same flat discount off an intensive term for a child", () => {
    const pricing = priceTerm({ length: "intensive", category: "child" });
    expect(pricing.termFeeCents()).toBe(33000);
  });

  // Concession again, on numbers that happen to divide evenly - confirms the percentage
  // isn't hardcoded to the standard term's gross.
  it("takes the same percentage discount off an intensive term for a concession student", () => {
    const pricing = priceTerm({ length: "intensive", category: "concession" });
    expect(pricing.termFeeCents()).toBe(30600);
  });

  // Guards invoiceLine composing the session count and the formatted fee together.
  it("renders an invoice line as the session count, then the formatted fee", () => {
    const pricing = priceTerm({ length: "standard", category: "adult" });
    expect(invoiceLine("Priya Shah", pricing)).toBe("Priya Shah: 10 sessions, $449.90");
  });

  // Guards totalFeeCents summing across a mix of lengths and categories, not just one.
  it("sums fees across a mix of term lengths and categories", () => {
    const standardAdult = priceTerm({ length: "standard", category: "adult" });
    const intensiveConcession = priceTerm({
      length: "intensive",
      category: "concession",
    });
    expect(totalFeeCents([standardAdult, intensiveConcession])).toBe(44990 + 30600);
  });

  // Boundary: an empty batch bills nothing, not NaN from an empty reduce.
  it("bills nothing for an empty batch of priced terms", () => {
    expect(totalFeeCents([])).toBe(0);
  });
});
