import { describe, expect, it } from "vitest";
import {
  boardDisplayName,
  contactPhoneLine,
  dateOfBirthLine,
  followUpEligible,
  insuranceLabel,
  isBillable,
  nextOfKinLine,
  registeredPatient,
  requiresIdArmband,
  unknownPatient,
  waitingRoomSortKey,
  type RegisteredPatientData,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of introducing the special case. Do not edit this file: if
 * a refactoring seems to require changing a test, either the refactoring changed behaviour
 * or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Introduce Special Case could silently
 * change - not one per board function. Each test names the move it is guarding against.
 *
 * Note what is deliberately absent: no test here calls isBillable(unknownPatient()). That
 * exact call is where the challenge's ninth check and the solution disagree - see
 * WALKTHROUGH.md and tests-fixed/.
 */

function patientData(
  overrides: Partial<RegisteredPatientData> = {},
): RegisteredPatientData {
  return {
    id: "P-1042",
    name: "Priya Shah",
    phone: "555-0142",
    dateOfBirthIso: "1985-04-02",
    insuranceProvider: "Northfield Mutual",
    nextOfKinPhone: "555-0199",
    ...overrides,
  };
}

describe("boardDisplayName", () => {
  // Guards against forgetting the special case: an unidentified patient must never show
  // their raw record - there isn't one - where a name would normally go.
  it("shows the registered patient's own name, and a placeholder for an unidentified one", () => {
    expect(boardDisplayName(registeredPatient(patientData()))).toBe("Priya Shah");
    expect(boardDisplayName(unknownPatient())).toBe("Unidentified Patient");
  });
});

describe("contactPhoneLine", () => {
  it("shows the registered patient's phone, and that none is on file for an unidentified one", () => {
    expect(contactPhoneLine(registeredPatient(patientData()))).toBe("555-0142");
    expect(contactPhoneLine(unknownPatient())).toBe("No contact on file");
  });
});

describe("insuranceLabel", () => {
  // The anchor test: a registered self-pay patient and an unidentified patient both start
  // from "no insurance provider on file", and a version that collapses the special case
  // down to a null check instead of an identity check would label them the same way.
  it("tells a registered self-pay patient apart from an unidentified one, even though both have no insurance on file", () => {
    const selfPay = registeredPatient(patientData({ insuranceProvider: null }));
    expect(insuranceLabel(selfPay)).toBe("Self-pay");
    expect(insuranceLabel(unknownPatient())).toBe("Pending identification");
  });

  it("labels a registered patient's own insurer when one is on file", () => {
    expect(insuranceLabel(registeredPatient(patientData()))).toBe("Northfield Mutual");
  });
});

describe("dateOfBirthLine", () => {
  it("shows the registered patient's date of birth, and that it's unknown for an unidentified one", () => {
    expect(dateOfBirthLine(registeredPatient(patientData()))).toBe("1985-04-02");
    expect(dateOfBirthLine(unknownPatient())).toBe("DOB unknown");
  });
});

describe("nextOfKinLine", () => {
  // Mirrors the insuranceLabel anchor test: a registered patient with no next of kin on
  // file, and an unidentified patient, must not read the same way either.
  it("tells a registered patient with no next of kin on file apart from an unidentified patient", () => {
    const noKin = registeredPatient(patientData({ nextOfKinPhone: null }));
    expect(nextOfKinLine(noKin)).toBe("None on file");
    expect(nextOfKinLine(unknownPatient())).toBe("Not available");
  });
});

describe("requiresIdArmband", () => {
  it("requires an armband only for a patient who has not been identified yet", () => {
    expect(requiresIdArmband(registeredPatient(patientData()))).toBe(false);
    expect(requiresIdArmband(unknownPatient())).toBe(true);
  });
});

describe("waitingRoomSortKey", () => {
  // Guards against a rewrite that sorts the unidentified patient by name (empty string,
  // sorting first) instead of deliberately last.
  it("sorts an unidentified patient after every named patient on the board", () => {
    const names = ["Zeynep Aydin", "Ana Costa"].map((name) =>
      waitingRoomSortKey(registeredPatient(patientData({ name }))),
    );
    const sorted = [...names, waitingRoomSortKey(unknownPatient())].sort();
    expect(sorted[sorted.length - 1]).toBe(waitingRoomSortKey(unknownPatient()));
  });
});

describe("isBillable", () => {
  // Only the registered-patient side of this function is safe to pin in the shared suite;
  // see the file comment and tests-fixed/ for why.
  it("treats every registered patient as billable, insured or self-pay", () => {
    expect(isBillable(registeredPatient(patientData()))).toBe(true);
    expect(isBillable(registeredPatient(patientData({ insuranceProvider: null })))).toBe(
      true,
    );
  });
});

describe("followUpEligible", () => {
  it("allows a follow-up for a registered patient and refuses one for an unidentified patient", () => {
    expect(followUpEligible(registeredPatient(patientData()))).toBe(true);
    expect(followUpEligible(unknownPatient())).toBe(false);
  });
});
