import { describe, expect, it } from "vitest";
import { TicketOffice, type SerialPrinter } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Remove Setting
 * Method is that `Ticket`'s constructor and its settable-id surface change shape - the
 * challenge builds a ticket with a placeholder id and fixes it up afterwards with `setId`,
 * the solution requires the real id up front and has no such method at all. So this suite
 * never constructs a `Ticket` directly and never calls a setter on its id - it only calls
 * `TicketOffice`, whose own signature does not change, and reads back what it returns.
 *
 * One thing it deliberately does NOT pin: whether a ticket can be found by its own id
 * immediately after `issueTicket` returns. Against the challenge that lookup fails - the
 * registry was keyed by the placeholder before the real serial was stamped on. The shared
 * suite has to stay green against both versions, so it cannot take a side; the proof that
 * the solution fixed it lives in `tests-fixed/`.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function sequentialPrinter(prefix: string): SerialPrinter {
  let count = 0;
  return {
    nextSerial(): string {
      count = count + 1;
      return `${prefix}-${count}`;
    },
  };
}

describe("TicketOffice.issueTicket", () => {
  it("issues a ticket carrying the performance, price, and holder it was given", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    const ticket = office.issueTicket({
      performanceId: "gala-2026",
      priceCents: 4500,
      holderName: "Mina Cho",
    });

    expect(ticket.performanceId).toBe("gala-2026");
    expect(ticket.priceCents).toBe(4500);
    expect(ticket.holderName).toBe("Mina Cho");
  });

  it("stamps the ticket with the printer's serial", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    const ticket = office.issueTicket({
      performanceId: "gala-2026",
      priceCents: 4500,
      holderName: "Mina Cho",
    });

    expect(ticket.id).toBe("GALA-1");
  });

  // Guards against both tickets ending up keyed - or named - the same way, which would
  // make findById ambiguous even once it works at all.
  it("gives consecutive tickets distinct ids", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    const details = {
      performanceId: "gala-2026",
      priceCents: 4500,
      holderName: "Mina Cho",
    };

    const first = office.issueTicket(details);
    const second = office.issueTicket(details);

    expect(first.id).not.toBe(second.id);
  });

  // Guards the boundary where a naive "if (priceCents)" check would treat a free ticket
  // as if issuing it had failed.
  it("carries a zero price through issuance without special-casing it", () => {
    const office = new TicketOffice(sequentialPrinter("COMP"));
    const ticket = office.issueTicket({
      performanceId: "preview-night",
      priceCents: 0,
      holderName: "Press Desk",
    });

    expect(ticket.priceCents).toBe(0);
  });
});

describe("Ticket.transferTo", () => {
  it("moves only the holder name, leaving the id, performance, and price untouched", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    const ticket = office.issueTicket({
      performanceId: "gala-2026",
      priceCents: 4500,
      holderName: "Mina Cho",
    });
    const id = ticket.id;

    ticket.transferTo("Wale Osei");

    expect(ticket.holderName).toBe("Wale Osei");
    expect(ticket.id).toBe(id);
    expect(ticket.performanceId).toBe("gala-2026");
    expect(ticket.priceCents).toBe(4500);
  });

  // Guards against a shared-state bug where two tickets alias the same holder field -
  // easy to introduce while moving fields around during the refactor.
  it("leaves a different ticket's holder alone", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    const details = {
      performanceId: "gala-2026",
      priceCents: 4500,
      holderName: "Mina Cho",
    };
    const first = office.issueTicket(details);
    const second = office.issueTicket(details);

    first.transferTo("Wale Osei");

    expect(second.holderName).toBe("Mina Cho");
  });
});

describe("TicketOffice.findById", () => {
  it("returns undefined for a serial nobody has issued", () => {
    const office = new TicketOffice(sequentialPrinter("GALA"));
    expect(office.findById("GALA-999")).toBeUndefined();
  });
});
