import { describe, expect, it } from "vitest";
import {
  bookAtCounter,
  bookByMail,
  bookByPhone,
  type Order,
  type Section,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Remove Flag
 * Argument is that a signature changes - the function behind these three callers stops
 * taking a boolean at all. So this suite imports only the three callers -
 * `bookAtCounter`, `bookByMail`, `bookByPhone` - and never the function that currently
 * takes the flag. It pins what every caller returns and what it does to the section's
 * seat count and waitlist. It says nothing about how many functions do the booking
 * underneath, or what any of them are called.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function section(availableSeats: number, waitlist: string[] = []): Section {
  return { name: "Stalls", availableSeats, waitlist };
}

function order(customerName: string, seatCount: number): Order {
  return { customerName, seatCount };
}

describe("bookAtCounter", () => {
  it("confirms the booking and takes the seats from the section", () => {
    const stalls = section(5);
    const receipt = bookAtCounter(stalls, order("Ana", 2));
    expect(receipt).toMatchObject({ status: "confirmed", seatCount: 2 });
    expect(stalls.availableSeats).toBe(3);
  });

  // Guards against turning the priority path into a waitlist path: a counter sale
  // fails outright when there isn't room, it never queues silently.
  it("throws rather than waitlisting when the section is full", () => {
    const stalls = section(1);
    expect(() => bookAtCounter(stalls, order("Bruno", 2))).toThrow();
    expect(stalls.waitlist).toEqual([]);
  });
});

describe("bookByMail", () => {
  it("confirms as pending when there is room", () => {
    const stalls = section(5);
    const receipt = bookByMail(stalls, order("Celia", 3));
    expect(receipt).toMatchObject({ status: "pending", seatCount: 3 });
    expect(stalls.availableSeats).toBe(2);
  });

  // Guards against turning the standard path into a throw: mail orders wait, they
  // never fail outright.
  it("waitlists instead of throwing when the section is full", () => {
    const stalls = section(1);
    const receipt = bookByMail(stalls, order("Duarte", 2));
    expect(receipt.status).toBe("waitlisted");
    expect(stalls.waitlist).toEqual(["Duarte"]);
  });

  // Guards the exact-fit boundary: asking for precisely what's left confirms it,
  // an off-by-one in the comparison would waitlist it instead.
  it("confirms exactly when the order asks for exactly what remains", () => {
    const stalls = section(4);
    const receipt = bookByMail(stalls, order("Elsa", 4));
    expect(receipt.status).toBe("pending");
    expect(stalls.availableSeats).toBe(0);
  });

  // Guards against the waitlist losing arrival order across multiple bookings.
  it("keeps waitlisted customers in the order they were turned away", () => {
    const stalls = section(0);
    bookByMail(stalls, order("First", 1));
    bookByMail(stalls, order("Second", 1));
    expect(stalls.waitlist).toEqual(["First", "Second"]);
  });
});

describe("bookByPhone", () => {
  it("treats a small group as a standard order and waitlists it when the section is full", () => {
    const stalls = section(1);
    const receipt = bookByPhone(stalls, order("Small Group", 3));
    expect(receipt.status).toBe("waitlisted");
  });

  // Guards the threshold itself: at the cutoff, the order is priority, not standard,
  // so it throws instead of waitlisting when there isn't room.
  it("treats a group at the threshold as priority", () => {
    const stalls = section(2);
    expect(() => bookByPhone(stalls, order("Big Group", 8))).toThrow();
  });

  it("confirms a large group immediately when there is room", () => {
    const stalls = section(10);
    const receipt = bookByPhone(stalls, order("Big Group", 8));
    expect(receipt.status).toBe("confirmed");
    expect(stalls.availableSeats).toBe(2);
  });

  // Guards off-by-one on the threshold in the other direction: one seat short of the
  // cutoff is still standard.
  it("treats one seat short of the threshold as standard, not priority", () => {
    const stalls = section(2);
    const receipt = bookByPhone(stalls, order("Medium Group", 7));
    expect(receipt.status).toBe("waitlisted");
    expect(stalls.waitlist).toEqual(["Medium Group"]);
  });
});
