import { describe, expect, it } from "vitest";
import { calculateEntryFee, type EntryRequest, type Race } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour that a *plausible* refactoring of this file could
 * silently change - not one per line. Each test names the move it is guarding against.
 */

const raceHome: Race = {
  baseFeeCents: 4000,
  date: "2026-06-21",
  hostClub: "Silverbrook AC",
};

const baseEntry: EntryRequest = {
  ageCategory: "adult",
  club: "Silverbrook AC",
  isMember: false,
  // 11 days before the race: not early bird
  registeredOn: "2026-06-10",
};

describe("calculateEntryFee", () => {
  it("charges the base fee plus the flat affiliation fee when nothing else applies", () => {
    expect(calculateEntryFee(baseEntry, raceHome)).toBe(4200);
  });

  it("applies the member discount to the base fee", () => {
    expect(calculateEntryFee({ ...baseEntry, isMember: true }, raceHome)).toBe(3600);
  });

  // Guards the early-bird boundary: registering exactly on the cut-off day still counts.
  it("applies the early-bird discount when registered exactly on the cut-off day", () => {
    // 21 days before the race
    const onTime = { ...baseEntry, registeredOn: "2026-05-31" };
    expect(calculateEntryFee(onTime, raceHome)).toBe(3800);
  });

  // Guards the other side of the same boundary - a plausible `>` for `>=` slip.
  it("withholds the early-bird discount one day short of the cut-off", () => {
    // 20 days before the race
    const oneDayLate = { ...baseEntry, registeredOn: "2026-06-01" };
    expect(calculateEntryFee(oneDayLate, raceHome)).toBe(4200);
  });

  it("applies the non-host surcharge to runners from another club", () => {
    const visitor = { ...baseEntry, club: "Riverside Runners" };
    expect(calculateEntryFee(visitor, raceHome)).toBe(4800);
  });

  it("applies the junior concession", () => {
    expect(calculateEntryFee({ ...baseEntry, ageCategory: "junior" }, raceHome)).toBe(
      3200,
    );
  });

  it("applies the senior concession", () => {
    expect(calculateEntryFee({ ...baseEntry, ageCategory: "senior" }, raceHome)).toBe(
      3700,
    );
  });

  // Guards the discount chain staying multiplicative. An additive shortcut
  // (0.85 + 0.9 - 1 = 0.75) would give 3200, not 3260.
  it("combines the member and early-bird discounts multiplicatively, not additively", () => {
    const memberEarlyBird = {
      ...baseEntry,
      isMember: true,
      registeredOn: "2026-05-31",
    };
    expect(calculateEntryFee(memberEarlyBird, raceHome)).toBe(3260);
  });

  // Guards the affiliation fee staying outside the discount chain even when every
  // other discount is stacked as high as it goes.
  it("keeps the affiliation fee flat no matter how large the other discounts are", () => {
    const maximallyDiscounted: EntryRequest = {
      ageCategory: "junior",
      club: "Silverbrook AC",
      isMember: true,
      registeredOn: "2026-05-31",
    };
    expect(calculateEntryFee(maximallyDiscounted, raceHome)).toBe(2260);
  });

  // Guards the rounding itself: a stray `Math.floor` or `Math.ceil` would only show up
  // once a fractional cent value is on the wrong side of .5.
  it("rounds the final total to the nearest cent, in both directions", () => {
    // discounted base is 2834.75
    const roundsUp = calculateEntryFee(
      { ...baseEntry, isMember: true },
      { ...raceHome, baseFeeCents: 3335 },
    );
    // discounted base is 2831.35
    const roundsDown = calculateEntryFee(
      { ...baseEntry, isMember: true },
      { ...raceHome, baseFeeCents: 3331 },
    );

    expect(roundsUp).toBe(3035);
    expect(roundsDown).toBe(3031);
  });
});
