import { describe, expect, it } from "vitest";
import { renderSupplierReport, type SupplierReport } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

describe("renderSupplierReport", () => {
  it("lists accepted deliveries, then rejected, then a summary with the running total", () => {
    const week: SupplierReport = {
      weekOf: "2026-08-24",
      truckCapacityKg: 500,
      deliveries: [
        {
          supplierName: "Millbrook Grain Co",
          itemName: "Bread Flour",
          weightKg: 120,
          costCents: 34000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Dale Farm Dairy",
          itemName: "Butter",
          weightKg: 40,
          costCents: 21000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Two Rivers Orchard",
          itemName: "Apples",
          weightKg: 90,
          costCents: 15000,
          qualityPassed: false,
          rejectionReason: "bruised stock",
        },
        {
          supplierName: "Hollow Creek Eggs",
          itemName: "Eggs",
          weightKg: 60,
          costCents: 18000,
          qualityPassed: true,
          rejectionReason: null,
        },
      ],
    };

    expect(renderSupplierReport(week)).toBe(
      [
        "Supplier Report — week of 2026-08-24",
        "====================================",
        "Accepted:",
        "  Millbrook Grain Co — Bread Flour: 120kg, $340.00",
        "  Dale Farm Dairy — Butter: 40kg, $210.00",
        "  Hollow Creek Eggs — Eggs: 60kg, $180.00",
        "Rejected:",
        "  Two Rivers Orchard — Apples: rejected (bruised stock)",
        "------------------------------------",
        "Accepted: 3 of 4 deliveries, $730.00",
        "Rejected: 1 of 4 deliveries",
        "Truck capacity: 500kg — within capacity",
      ].join("\n"),
    );
  });

  // Guards against a rejected line dropping its `?? "no reason given"` fallback while
  // being converted from a loop body into a .map callback.
  it("falls back to 'no reason given' when a rejection carries no reason", () => {
    const week: SupplierReport = {
      weekOf: "2026-08-31",
      truckCapacityKg: 1000,
      deliveries: [
        {
          supplierName: "Two Rivers Orchard",
          itemName: "Apples",
          weightKg: 90,
          costCents: 15000,
          qualityPassed: false,
          rejectionReason: null,
        },
      ],
    };

    expect(renderSupplierReport(week)).toContain(
      "  Two Rivers Orchard — Apples: rejected (no reason given)",
    );
  });

  // Guards against the capacity check reporting the heaviest or the last delivery instead
  // of the first one that actually tips the running total over the limit - the usual
  // casualty of trying to fold this into a .filter or .reduce that keeps going past it.
  it("names the first delivery that pushes the running weight over capacity, not the heaviest one", () => {
    const week: SupplierReport = {
      weekOf: "2026-09-07",
      truckCapacityKg: 200,
      deliveries: [
        {
          supplierName: "Millbrook Grain Co",
          itemName: "Bread Flour",
          weightKg: 80,
          costCents: 20000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Dale Farm Dairy",
          itemName: "Butter",
          weightKg: 90,
          costCents: 21000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Stonebridge Mill",
          itemName: "Rye Flour",
          weightKg: 50,
          costCents: 16000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Hollow Creek Eggs",
          itemName: "Eggs",
          weightKg: 200,
          costCents: 18000,
          qualityPassed: true,
          rejectionReason: null,
        },
      ],
    };

    // Running weight: 80, 170, 220 (breaches here, at Stonebridge Mill), 420. The 200kg
    // delivery from Hollow Creek Eggs is the heaviest single delivery but arrives after
    // the truck is already over capacity, so it must not be the one named.
    expect(renderSupplierReport(week)).toContain(
      "Truck capacity: 200kg — would exceed at delivery 3 (Stonebridge Mill)",
    );
  });

  // Boundary: a running weight exactly equal to capacity has not exceeded it. Guards a
  // `>=` sneaking in where the challenge uses `>`.
  it("treats a running weight exactly at capacity as within capacity, not a breach", () => {
    const week: SupplierReport = {
      weekOf: "2026-09-14",
      truckCapacityKg: 150,
      deliveries: [
        {
          supplierName: "Millbrook Grain Co",
          itemName: "Bread Flour",
          weightKg: 100,
          costCents: 20000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Dale Farm Dairy",
          itemName: "Butter",
          weightKg: 50,
          costCents: 21000,
          qualityPassed: true,
          rejectionReason: null,
        },
      ],
    };

    expect(renderSupplierReport(week)).toContain(
      "Truck capacity: 150kg — within capacity",
    );
  });

  // Guards the empty case, where every filter and reduce runs over nothing.
  it("still renders both sections and a summary for a week with no deliveries", () => {
    const week: SupplierReport = {
      weekOf: "2026-09-21",
      truckCapacityKg: 300,
      deliveries: [],
    };

    expect(renderSupplierReport(week)).toBe(
      [
        "Supplier Report — week of 2026-09-21",
        "====================================",
        "Accepted:",
        "  (none)",
        "Rejected:",
        "  (none)",
        "------------------------------------",
        "Accepted: 0 of 0 deliveries, $0.00",
        "Rejected: 0 of 0 deliveries",
        "Truck capacity: 300kg — within capacity",
      ].join("\n"),
    );
  });

  // Guards against a pipeline conversion that "helpfully" sorts the accepted deliveries -
  // filter alone must not reorder them.
  it("lists accepted deliveries in delivery order, not sorted by name", () => {
    const week: SupplierReport = {
      weekOf: "2026-09-28",
      truckCapacityKg: 1000,
      deliveries: [
        {
          supplierName: "Zephyr Bakehouse Supply",
          itemName: "Yeast",
          weightKg: 5,
          costCents: 4000,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Anders Milling",
          itemName: "Rye Flour",
          weightKg: 30,
          costCents: 9000,
          qualityPassed: true,
          rejectionReason: null,
        },
      ],
    };

    const rows = renderSupplierReport(week).split("\n").slice(3, 5);
    expect(rows[0]).toContain("Zephyr Bakehouse Supply");
    expect(rows[1]).toContain("Anders Milling");
  });

  // Guards the accepted total against re-deriving "accepted" a second time instead of
  // folding the already-filtered list - and pins the cents-to-dollars padding.
  it("sums only accepted deliveries' costs, padding cents below ten", () => {
    const week: SupplierReport = {
      weekOf: "2026-10-05",
      truckCapacityKg: 1000,
      deliveries: [
        {
          supplierName: "Millbrook Grain Co",
          itemName: "Bread Flour",
          weightKg: 10,
          costCents: 1205,
          qualityPassed: true,
          rejectionReason: null,
        },
        {
          supplierName: "Two Rivers Orchard",
          itemName: "Apples",
          weightKg: 90,
          costCents: 999_999,
          qualityPassed: false,
          rejectionReason: "bruised stock",
        },
      ],
    };

    expect(renderSupplierReport(week)).toContain("Accepted: 1 of 2 deliveries, $12.05");
  });
});
