import { describe, expect, it } from "vitest";
import { dispatchToCourier, dispatchToDriver, type DispatchStop } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of pulling the two callers' closings back out of the
 * shared function. Do not edit this file: if a refactoring seems to require changing a
 * test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Move Statements to Callers could silently
 * change - not one per caller. Each test names the move it is guarding against.
 */

const cedarHollow: DispatchStop = {
  id: "DS-1001",
  customerName: "Cedar Hollow Café",
  destination: "142 Elm Street",
  items: [
    { name: "Sourdough Loaf", quantity: 12, unitWeightGrams: 900 },
    { name: "Cinnamon Roll", quantity: 24, unitWeightGrams: 90 },
  ],
};

const saltmarsh: DispatchStop = {
  id: "DS-2044",
  customerName: "Saltmarsh Provisions",
  destination: "88 Harbor Road",
  items: [
    { name: "Baguette", quantity: 40, unitWeightGrams: 250 },
    { name: "Walnut Bread", quantity: 10, unitWeightGrams: 700 },
  ],
};

const ferryPoint: DispatchStop = {
  id: "DS-2077",
  customerName: "Ferry Point Market",
  destination: "3 Ferry Point Lane",
  items: [{ name: "Apple Danish", quantity: 1, unitWeightGrams: 1050 }],
};

const willowCreek: DispatchStop = {
  id: "DS-3099",
  customerName: "Willow Creek Test Kitchen",
  destination: "5 Test Way",
  items: [],
};

const northgate: DispatchStop = {
  id: "DS-4021",
  customerName: "Northgate Diner",
  destination: "27 Ridge Ave",
  items: [
    { name: "Rye Loaf", quantity: 3, unitWeightGrams: 850 },
    { name: "Baguette", quantity: 6, unitWeightGrams: 250 },
    { name: "Cinnamon Roll", quantity: 2, unitWeightGrams: 90 },
  ],
};

const pinehill: DispatchStop = {
  id: "DS-5050",
  customerName: "Pinehill Market",
  destination: "9 Pine Hill Road",
  items: [{ name: "Baguette", quantity: 4, unitWeightGrams: 250 }],
};

describe("dispatchToDriver", () => {
  // Guards the driver's closing surviving the move: whole-gram weight, then the
  // door-signature line, once that pair no longer lives inside a shared branch.
  it("renders the header, item lines, weight in whole grams, then the sign-off line", () => {
    expect(dispatchToDriver(cedarHollow)).toEqual([
      "Ashgrove Bakery Co-op — Stop DS-1001",
      "Deliver to: Cedar Hollow Café, 142 Elm Street",
      "  12 x Sourdough Loaf",
      "  24 x Cinnamon Roll",
      "Total weight: 12960 g",
      "Please sign at the door to confirm receipt.",
    ]);
  });

  // Boundary: no items at all. Guards against a stray blank line where the item block
  // would otherwise sit, now that rendering the items lives outside the closing.
  it("still renders a header and a zero-gram weight for a stop with no items", () => {
    expect(dispatchToDriver(willowCreek)).toEqual([
      "Ashgrove Bakery Co-op — Stop DS-3099",
      "Deliver to: Willow Creek Test Kitchen, 5 Test Way",
      "Total weight: 0 g",
      "Please sign at the door to confirm receipt.",
    ]);
  });

  // Guards item order surviving the split into a shared prelude plus a caller-owned
  // close: nothing about this refactoring should touch how items are listed.
  it("keeps items in the order given, not sorted by name or weight", () => {
    expect(dispatchToDriver(northgate)).toEqual([
      "Ashgrove Bakery Co-op — Stop DS-4021",
      "Deliver to: Northgate Diner, 27 Ridge Ave",
      "  3 x Rye Loaf",
      "  6 x Baguette",
      "  2 x Cinnamon Roll",
      "Total weight: 4230 g",
      "Please sign at the door to confirm receipt.",
    ]);
  });
});

describe("dispatchToCourier", () => {
  // Guards the courier's closing surviving the move: the gram-to-kilogram conversion
  // and the liability line, once they no longer share a branch with the driver's pair.
  it("renders the header, item lines, weight converted to kilograms, then the liability line", () => {
    expect(dispatchToCourier(saltmarsh)).toEqual([
      "Ashgrove Bakery Co-op — Stop DS-2044",
      "Deliver to: Saltmarsh Provisions, 88 Harbor Road",
      "  40 x Baguette",
      "  10 x Walnut Bread",
      "Total weight: 17.0 kg",
      "Courier handoff — Ashgrove liability ends at pickup.",
    ]);
  });

  // Boundary: 1050 g is exactly 1.05 kg. Guards the rounding rule staying exactly what
  // it was once the conversion moves out of the shared function and into one caller.
  it("rounds a kilogram total that lands exactly on a tenth's boundary", () => {
    expect(dispatchToCourier(ferryPoint)).toEqual([
      "Ashgrove Bakery Co-op — Stop DS-2077",
      "Deliver to: Ferry Point Market, 3 Ferry Point Lane",
      "  1 x Apple Danish",
      "Total weight: 1.1 kg",
      "Courier handoff — Ashgrove liability ends at pickup.",
    ]);
  });
});

describe("both callers together", () => {
  // Guards the actual precondition this refactoring exploits: the two callers must
  // diverge only in what comes after the shared prelude, never before it. A move that
  // quietly re-merges the two closings behind a flag would still pass every test above
  // in isolation; only comparing the two outputs catches it. Contrast with drill-08-03's
  // "all three callers agree" test, which guards the opposite precondition.
  it("share the header and item lines exactly, and differ only in their closing two lines", () => {
    const driver = dispatchToDriver(pinehill);
    const courier = dispatchToCourier(pinehill);

    expect(driver.slice(0, -2)).toEqual(courier.slice(0, -2));
    expect(driver.at(-2)).toBe("Total weight: 1000 g");
    expect(courier.at(-2)).toBe("Total weight: 1.0 kg");
    expect(driver.at(-1)).toBe("Please sign at the door to confirm receipt.");
    expect(courier.at(-1)).toBe("Courier handoff — Ashgrove liability ends at pickup.");
  });
});
