import { describe, expect, it } from "vitest";
import { renderProductionSummary, type Order, type ProductionDay } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * Each test names the move it is guarding against, and there is one per behaviour a
 * plausible Split Loop could silently change - not one per line.
 */

function dayOf(dateLabel: string, orders: readonly Order[]): ProductionDay {
  return { dateLabel, orders };
}

describe("renderProductionSummary", () => {
  it("tallies the till total and the flour draw for a typical day", () => {
    const orders: Order[] = [
      { customerName: "Rosa Bittencourt", totalCents: 1850, flourGrams: 900 },
      { customerName: "Tomas Vidal", totalCents: 4200, flourGrams: 1600 },
      { customerName: "Community Kitchen", totalCents: 0, flourGrams: 3000 },
    ];

    expect(renderProductionSummary(dayOf("2026-09-02", orders))).toBe(
      [
        "Ashgrove Bakery Co-op — 2026-09-02",
        "Till total: $60.50",
        "Flour to draw for tomorrow: 5.5kg",
      ].join("\n"),
    );
  });

  // Guards against the copy-paste mistake at the heart of this refactoring: duplicating
  // the merged loop and then stripping the wrong field out of the wrong copy, so revenue
  // and flour end up reading each other's numbers.
  it("keeps revenue and flour as two independent sums when an order only feeds one of them", () => {
    const orders: Order[] = [
      { customerName: "Gift Card Redemption", totalCents: 5000, flourGrams: 0 },
      { customerName: "Community Kitchen Donation", totalCents: 0, flourGrams: 1200 },
    ];

    const report = renderProductionSummary(dayOf("2026-09-03", orders));
    expect(report).toContain("Till total: $50.00");
    expect(report).toContain("Flour to draw for tomorrow: 1.2kg");
  });

  // Guards the empty case, where a running total that starts anywhere but zero would
  // still slip through unnoticed on non-empty days.
  it("sums to zero for a day with no orders", () => {
    expect(renderProductionSummary(dayOf("2026-09-04", []))).toBe(
      [
        "Ashgrove Bakery Co-op — 2026-09-04",
        "Till total: $0.00",
        "Flour to draw for tomorrow: 0g",
      ].join("\n"),
    );
  });

  it("carries a single order's totals through unchanged", () => {
    const orders: Order[] = [
      { customerName: "Ana Souza", totalCents: 1275, flourGrams: 450 },
    ];

    const report = renderProductionSummary(dayOf("2026-09-05", orders));
    expect(report).toContain("Till total: $12.75");
    expect(report).toContain("Flour to draw for tomorrow: 450g");
  });

  // Guards against a formatter that drops the leading zero on a remainder under ten
  // cents - an easy slip if the padding is "simplified" away during the split.
  it("pads a remainder under ten cents with a leading zero", () => {
    const orders: Order[] = [
      { customerName: "Ines Rocha", totalCents: 305, flourGrams: 0 },
    ];

    expect(renderProductionSummary(dayOf("2026-09-06", orders))).toContain(
      "Till total: $3.05",
    );
  });

  // Guards the grams/kilograms boundary at exactly 1000g in both directions.
  it("switches from grams to a whole kilogram exactly at 1000g, not a gram before", () => {
    const justUnder = dayOf("2026-09-07", [
      { customerName: "Paulo Serra", totalCents: 0, flourGrams: 999 },
    ]);
    const exactly = dayOf("2026-09-07", [
      { customerName: "Paulo Serra", totalCents: 0, flourGrams: 1000 },
    ]);

    expect(renderProductionSummary(justUnder)).toContain(
      "Flour to draw for tomorrow: 999g",
    );
    expect(renderProductionSummary(exactly)).toContain("Flour to draw for tomorrow: 1kg");
  });

  // Guards against a formatter that always shows a decimal, even when there isn't one.
  it("keeps a fractional kilogram total to one decimal place", () => {
    const orders: Order[] = [
      { customerName: "Celia Nunes", totalCents: 0, flourGrams: 1500 },
    ];

    expect(renderProductionSummary(dayOf("2026-09-08", orders))).toContain(
      "Flour to draw for tomorrow: 1.5kg",
    );
  });
});
