import { describe, expect, it } from "vitest";
import { cartSection, sectionTally, spineLabelSection } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 *
 * cartSection and sectionTally are only exercised here with shelf codes shaped the way
 * every caller already agreed on before this refactoring: a two-letter section, or a code
 * that carries a shelf letter. That is deliberate, not an oversight - see WALKTHROUGH.md
 * for what a three-letter section or an unshelved code does to each of them, and why
 * closing that gap is not part of this exercise.
 */

describe("cartSection", () => {
  it("takes the section from a two-letter, lettered shelf code", () => {
    expect(cartSection("NF-770-A")).toBe("NF");
  });

  // Guards against the class number's decimal point being folded into the section by a
  // parser that stops at the wrong character.
  it("is not confused by a decimal class number", () => {
    expect(cartSection("YA-070.5-D")).toBe("YA");
  });
});

describe("spineLabelSection", () => {
  // Guards a three-letter section - the shape cartSection's original slice(0, 2) got
  // wrong. This caller was already correct; the refactor must not regress it.
  it("takes the full section from a three-letter code", () => {
    expect(spineLabelSection("JUV-741-B")).toBe("JUV");
  });

  // Guards a shelf code with no shelf letter yet - an item still in processing. This is
  // the shape sectionTally's original regex silently dropped; this caller never did.
  it("reads the section even when there is no shelf letter yet", () => {
    expect(spineLabelSection("FIC-813")).toBe("FIC");
  });

  it("is not confused by a decimal class number", () => {
    expect(spineLabelSection("REF-030.92-C")).toBe("REF");
  });
});

describe("sectionTally", () => {
  // Guards against merging counts across sections, and against a three-letter section
  // being treated as though it were shorter than it is.
  it("counts each lettered item under its own section", () => {
    expect(sectionTally(["NF-770-A", "NF-500-B", "FIC-813-C"])).toEqual({
      NF: 2,
      FIC: 1,
    });
  });

  // Guards the empty case, where there is nothing to fold into the tally.
  it("returns an empty tally for no items", () => {
    expect(sectionTally([])).toEqual({});
  });
});
