import { describe, expect, it } from "vitest";
import {
  itemsWithAllergenConflict,
  type Order,
  type OrderItem,
  type Product,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of turning the hand-rolled allergen loop into a call to
 * the predicate that already exists for the online menu. Do not edit this file: if a
 * refactoring seems to require changing a test, either the refactoring changed behaviour
 * or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Replace Inline Code with Function Call
 * could silently change - not one per product. Each test names the move it is guarding
 * against. Passing every test here is evidence the swap is safe, not proof: read
 * WALKTHROUGH.md for how the equivalence was actually established before the swap, not
 * just checked afterward.
 */

const sourdoughLoaf: Product = {
  id: "P-SOUR",
  name: "Sourdough Loaf",
  allergens: ["gluten"],
};
const baguette: Product = { id: "P-BAG", name: "Baguette", allergens: ["gluten"] };
const oatScone: Product = {
  id: "P-SCONE",
  name: "Oat Scone",
  allergens: ["gluten", "dairy"],
};
const almondCroissant: Product = {
  id: "P-ALMOND",
  name: "Almond Croissant",
  allergens: ["gluten", "dairy", "tree nuts"],
};
const pecanTart: Product = {
  id: "P-PECAN",
  name: "Pecan Tart",
  allergens: ["gluten", "dairy", "tree nuts", "eggs"],
};
const hazelnutBiscotti: Product = {
  id: "P-HAZEL",
  name: "Hazelnut Biscotti",
  allergens: ["gluten", "tree nuts"],
};
const riceCracker: Product = { id: "P-RICE", name: "Rice Cracker", allergens: [] };

function item(product: Product, quantity = 1): OrderItem {
  return { product, quantity };
}

function orderWith(
  items: readonly OrderItem[],
  mustAvoidAllergens: readonly string[],
): Order {
  return {
    id: "ORD-1",
    customerName: "The Riverside Cafe",
    items,
    mustAvoidAllergens,
  };
}

describe("itemsWithAllergenConflict", () => {
  it("flags items whose allergens overlap the order's avoid-list, and leaves the rest alone", () => {
    const sourdough = item(sourdoughLoaf);
    const almond = item(almondCroissant);
    const scone = item(oatScone);
    const pecan = item(pecanTart);
    const order = orderWith([sourdough, almond, scone, pecan], ["tree nuts"]);

    expect(itemsWithAllergenConflict(order)).toEqual([almond, pecan]);
  });

  // Guards against a version that stops at the first conflict instead of scanning every
  // item - a `break` after the first match, or a `.find()` swapped in for `.filter()`.
  // The conflicts sit at the first and last position on purpose, with two safe items
  // between them, so an early exit or a "first match only" bug fails loudly.
  it("flags every conflicting item, not just the first one found", () => {
    const pecan = item(pecanTart);
    const sourdough = item(sourdoughLoaf);
    const scone = item(oatScone);
    const almond = item(almondCroissant);
    const order = orderWith([pecan, sourdough, scone, almond], ["tree nuts"]);

    expect(itemsWithAllergenConflict(order)).toEqual([pecan, almond]);
  });

  // Guards against checking only the first entry of mustAvoidAllergens - biscotti has no
  // "dairy" (the first avoided allergen) but does have "tree nuts" (the second), so an
  // inner check that stops after the first avoided allergen misses this conflict.
  it("catches a conflict from an allergen further down the avoid-list, not just the first one checked", () => {
    const biscotti = item(hazelnutBiscotti);
    const safe = item(baguette);
    const order = orderWith([biscotti, safe], ["dairy", "tree nuts"]);

    expect(itemsWithAllergenConflict(order)).toEqual([biscotti]);
  });

  // Guards against a naive translation of the nested loop that pushes an item once per
  // matching allergen instead of once per item - pecanTart matches three of the three
  // avoided allergens here, and should still appear exactly once.
  it("flags an item only once, even when it conflicts with more than one avoided allergen", () => {
    const pecan = item(pecanTart);
    const order = orderWith([pecan], ["dairy", "tree nuts", "eggs"]);

    expect(itemsWithAllergenConflict(order)).toEqual([pecan]);
  });

  // Boundary: nothing to avoid means nothing can conflict, no matter how allergenic the
  // order is. A version that treats an empty avoid-list as "avoid everything" fails here.
  it("returns nothing when the order has no allergens to avoid", () => {
    const order = orderWith([item(pecanTart), item(almondCroissant)], []);

    expect(itemsWithAllergenConflict(order)).toEqual([]);
  });

  // Boundary: products with no allergens at all can never conflict with anything.
  it("returns nothing when none of the ordered products carry any allergens", () => {
    const order = orderWith([item(riceCracker), item(riceCracker)], ["gluten", "dairy"]);

    expect(itemsWithAllergenConflict(order)).toEqual([]);
  });

  // Boundary: an order with no items has nothing to scan in either loop.
  it("returns nothing for an order with no items", () => {
    const order = orderWith([], ["tree nuts"]);

    expect(itemsWithAllergenConflict(order)).toEqual([]);
  });
});
