import { describe, expect, it } from "vitest";
import { renderProfileCard, renderSquadSheet, type RunnerRecord } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it guards against. The season these profiles are
 * printed for is fixed at 2026 (see `SEASON` in the solution), so every fixture's ages and
 * qualifying windows are computed against that.
 */

describe("renderProfileCard", () => {
  // Guards against a transform that derives fields ad hoc per caller instead of once:
  // every derived field (age group, best pace, handicap, selectability) must agree. Also
  // guards the qualifying-window filter itself: the stale 2023 race and the 3km race are
  // both faster than the qualifying results, so merging "recent" and "long enough" with
  // OR, or dropping either condition, would pull one of them in and beat 3:40/km.
  it("prints the full card for a senior runner with a mix of qualifying and stale results", () => {
    const ana: RunnerRecord = {
      name: "Ana Ferreira",
      birthYear: 1994,
      joinedSeason: 2021,
      results: [
        { race: "Silverbrook 10K", season: 2026, distanceKm: 10, seconds: 2400 },
        { race: "Riverside 5K", season: 2025, distanceKm: 5, seconds: 1100 },
        { race: "Old Race", season: 2023, distanceKm: 10, seconds: 2000 },
        { race: "Short Race", season: 2026, distanceKm: 3, seconds: 600 },
      ],
    };

    expect(renderProfileCard(ana)).toBe(
      [
        "Ana Ferreira",
        "SEN · member since 2021",
        "Best pace 3:40/km",
        "Handicap +3:20",
        "Available for selection",
      ].join("\n"),
    );
  });

  // Guards the empty-results case: `Math.min(...[])` is `Infinity`, not a sentinel a
  // formatter can print. Best pace must fall back to "unranked", not a bogus time.
  it("reports an unranked runner with no qualifying results", () => {
    const celia: RunnerRecord = {
      name: "Celia Nunes",
      birthYear: 2007,
      joinedSeason: 2024,
      results: [],
    };

    expect(renderProfileCard(celia)).toBe(
      [
        "Celia Nunes",
        "U20 · member since 2024",
        "Best pace unranked",
        "Handicap +0:00",
        "Not eligible for selection",
      ].join("\n"),
    );
  });

  // Guards selection eligibility needing BOTH conditions, each isolated from the other: a
  // runner with plenty of qualifying results but who joined this season is not eligible
  // (a transform that checks only the result count would wrongly mark them eligible), and
  // a long-time member with only one qualifying result is not eligible either (a
  // transform that checks only tenure would wrongly mark them eligible too).
  it("requires both joining before this season and at least two qualifying results", () => {
    const joinedThisSeason: RunnerRecord = {
      name: "Bruno Costa",
      birthYear: 1990,
      joinedSeason: 2026,
      results: [
        { race: "A", season: 2026, distanceKm: 10, seconds: 1800 },
        { race: "B", season: 2026, distanceKm: 5, seconds: 900 },
      ],
    };
    const oneQualifyingResult: RunnerRecord = {
      name: "Gabriel",
      birthYear: 1985,
      joinedSeason: 2018,
      results: [{ race: "G", season: 2026, distanceKm: 10, seconds: 2500 }],
    };

    expect(renderProfileCard(joinedThisSeason)).toContain("Not eligible for selection");
    expect(renderProfileCard(oneQualifyingResult)).toContain(
      "Not eligible for selection",
    );
  });

  // Guards the handicap floor: a runner faster than scratch pace gets a negative gap,
  // which must clamp to zero rather than print a negative handicap. Non-veteran, so the
  // clamp is isolated from the separate veteran allowance.
  it("clamps the handicap gap at zero for a runner faster than scratch pace", () => {
    const speedy: RunnerRecord = {
      name: "Speedy",
      birthYear: 1994,
      joinedSeason: 2026,
      results: [{ race: "A", season: 2026, distanceKm: 10, seconds: 1800 }],
    };

    expect(renderProfileCard(speedy)).toContain("Handicap +0:00");
  });

  // Guards the veteran allowance as a flat addition tied to the age-group boundary, not
  // to pace: two runners with the identical qualifying pace, one turning veteran, differ
  // by exactly the 30-second allowance.
  it("adds the veteran allowance only from age 35, not age 34", () => {
    const race = { race: "E", season: 2026, distanceKm: 10, seconds: 2000 };
    const underAge: RunnerRecord = {
      name: "Under",
      birthYear: 1992,
      joinedSeason: 2020,
      results: [race],
    };
    const veteranAge: RunnerRecord = {
      name: "Over",
      birthYear: 1991,
      joinedSeason: 2020,
      results: [race],
    };

    expect(renderProfileCard(underAge)).toContain("Handicap +0:00");
    expect(renderProfileCard(veteranAge)).toContain("Handicap +0:30");
  });

  // Guards the age-group boundary itself: 20 is senior, not under-20, and the floor-to-5
  // bucketing must not off-by-one a runner right on the line.
  it("puts a 20-year-old in the senior group, not under-20", () => {
    const fatima: RunnerRecord = {
      name: "Fatima",
      birthYear: 2006,
      joinedSeason: 2020,
      results: [],
    };

    expect(renderProfileCard(fatima)).toContain("SEN · member since 2020");
  });

  // Guards rounding versus truncation in the pace formatter. 981s over 6km is exactly
  // 163.5 s/km; truncating (Math.floor) prints 2:43, rounding prints 2:44.
  it("rounds a half-second pace up rather than truncating it", () => {
    const rounder: RunnerRecord = {
      name: "Rounder",
      birthYear: 1994,
      joinedSeason: 2020,
      results: [{ race: "R", season: 2026, distanceKm: 6, seconds: 981 }],
    };

    expect(renderProfileCard(rounder)).toContain("Best pace 2:44/km");
  });
});

describe("renderSquadSheet", () => {
  // Guards the ranking itself, and that the per-row derivation matches the card's: the
  // same four runners as the card tests, ranked fastest qualifying pace first, with the
  // unranked runner sinking to the bottom rather than sorting as "fastest".
  it("ranks runners by best pace, fastest first, with the unranked runner last", () => {
    const ana: RunnerRecord = {
      name: "Ana Ferreira",
      birthYear: 1994,
      joinedSeason: 2021,
      results: [
        { race: "Silverbrook 10K", season: 2026, distanceKm: 10, seconds: 2400 },
        { race: "Riverside 5K", season: 2025, distanceKm: 5, seconds: 1100 },
      ],
    };
    const bruno: RunnerRecord = {
      name: "Bruno Costa",
      birthYear: 1990,
      joinedSeason: 2026,
      results: [{ race: "A", season: 2026, distanceKm: 10, seconds: 1800 }],
    };
    const celia: RunnerRecord = {
      name: "Celia Nunes",
      birthYear: 2007,
      joinedSeason: 2024,
      results: [],
    };

    expect(renderSquadSheet([ana, bruno, celia])).toBe(
      [
        "Silverbrook Squad Sheet - 2026",
        "==============================",
        "Bruno Costa            V35  3:00/km    +0:30 no",
        "Ana Ferreira           SEN  3:40/km    +3:20 yes",
        "Celia Nunes            U20  unranked   +0:00 no",
      ].join("\n"),
    );
  });

  // Guards sort stability: runners tied on best pace keep the order they were passed in,
  // rather than a comparator that treats equal values as an arbitrary swap.
  it("keeps runners tied on best pace in the order they were given", () => {
    const race = { race: "X", season: 2026, distanceKm: 10, seconds: 2000 };
    const tieB: RunnerRecord = {
      name: "Tie B",
      birthYear: 1990,
      joinedSeason: 2020,
      results: [race],
    };
    const tieA: RunnerRecord = {
      name: "Tie A",
      birthYear: 1990,
      joinedSeason: 2020,
      results: [race],
    };

    const rows = renderSquadSheet([tieB, tieA]).split("\n").slice(2);
    expect(rows[0]).toContain("Tie B");
    expect(rows[1]).toContain("Tie A");
  });

  // Guards the empty case: a header and a rule for a squad with nobody on it, not a crash
  // when there is no fastest runner to rank against.
  it("still prints a header and rule for an empty squad", () => {
    expect(renderSquadSheet([])).toBe(
      ["Silverbrook Squad Sheet - 2026", "=============================="].join("\n"),
    );
  });
});
