import { describe, expect, it } from "vitest";
import { renderRaceReport, type Race } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 */

const halfMarathon: Race = {
  name: "Silverbrook Half Marathon",
  date: "2026-03-14",
  distanceKm: 21.0975,
  entries: [
    { name: "Bruno Costa", club: "Riverside Runners", seconds: 5469 },
    { name: "Ana Ferreira", club: "Silverbrook AC", seconds: 4967 },
    { name: "Marcos Lima", club: "Riverside Runners", seconds: null },
    { name: "Celia Nunes", club: "Silverbrook AC", seconds: 6242 },
  ],
};

describe("renderRaceReport", () => {
  it("renders finishers ranked by time, then the runners who did not finish", () => {
    expect(renderRaceReport(halfMarathon)).toBe(
      [
        "Silverbrook Half Marathon - 2026-03-14",
        "======================================",
        "  1 Ana Ferreira           Silverbrook AC       1:22:47 3:55/km",
        "  2 Bruno Costa            Riverside Runners    1:31:09 4:19/km",
        "  3 Celia Nunes            Silverbrook AC       1:44:02 4:56/km",
        "DNF Marcos Lima            Riverside Runners",
        "--------------------------------------",
        "Finishers: 3 of 4",
        "Fastest: Ana Ferreira (1:22:47)",
        "Average pace: 4:24/km",
      ].join("\n"),
    );
  });

  it("drops the hour component for races finished in under an hour", () => {
    const fiveK: Race = {
      name: "Tuesday 5K",
      date: "2026-05-19",
      distanceKm: 5,
      entries: [
        { name: "Ana Ferreira", club: "Silverbrook AC", seconds: 1024 },
        { name: "Joao Pedro Vasconcelos", club: "Riverside Runners", seconds: 1500 },
      ],
    };

    expect(renderRaceReport(fiveK)).toBe(
      [
        "Tuesday 5K - 2026-05-19",
        "=======================",
        "  1 Ana Ferreira           Silverbrook AC       17:04 3:25/km",
        "  2 Joao Pedro Vasconcelos Riverside Runners    25:00 5:00/km",
        "-----------------------",
        "Finishers: 2 of 2",
        "Fastest: Ana Ferreira (17:04)",
        "Average pace: 4:12/km",
      ].join("\n"),
    );
  });

  it("omits the fastest and average lines when nobody finished", () => {
    const abandoned: Race = {
      name: "Coldwater Fell Race",
      date: "2026-01-09",
      distanceKm: 12,
      entries: [
        { name: "Ines Rocha", club: "Coldwater Harriers", seconds: null },
        { name: "Paulo Serra", club: "Unattached", seconds: null },
      ],
    };

    expect(renderRaceReport(abandoned)).toBe(
      [
        "Coldwater Fell Race - 2026-01-09",
        "================================",
        "DNF Ines Rocha             Coldwater Harriers",
        "DNF Paulo Serra            Unattached",
        "--------------------------------",
        "Finishers: 0 of 2",
      ].join("\n"),
    );
  });

  it("rules the separator to the width of the title", () => {
    const report = renderRaceReport(halfMarathon).split("\n");
    const title = report[0] ?? "";
    expect(report[1]).toBe("=".repeat(title.length));
    expect(report).toContain("-".repeat(title.length));
  });
});
