import { describe, expect, it } from "vitest";
import { renderRaceReport, type Race } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour that a *plausible* refactoring of this file could
 * silently change - not one per line. Line coverage here was already 100% with half these
 * tests, which is the point: coverage tells you which code ran, never which promises are
 * pinned. Each test below names the move it is guarding against.
 */

const halfMarathon: Race = {
  name: "Silverbrook Half Marathon",
  date: "2026-03-14",
  distanceKm: 21.0975,
  entries: [
    { name: "Bruno Costa", club: "Riverside Runners", seconds: 5469 },
    { name: "Ana Ferreira", club: "Silverbrook AC", seconds: 4967 },
    { name: "Marcos Lima", club: "Riverside Runners", seconds: null },
    { name: "Celia Nunes", club: "Silverbrook AC", seconds: 6242 },
  ],
};

describe("renderRaceReport", () => {
  it("renders finishers ranked by time, then the runners who did not finish", () => {
    expect(renderRaceReport(halfMarathon)).toBe(
      [
        "Silverbrook Half Marathon - 2026-03-14",
        "======================================",
        "  1 Ana Ferreira           Silverbrook AC       1:22:47 3:55/km",
        "  2 Bruno Costa            Riverside Runners    1:31:09 4:19/km",
        "  3 Celia Nunes            Silverbrook AC       1:44:02 4:56/km",
        "DNF Marcos Lima            Riverside Runners",
        "--------------------------------------",
        "Finishers: 3 of 4",
        "Fastest: Ana Ferreira (1:22:47)",
        "Average pace: 4:24/km",
      ].join("\n"),
    );
  });

  it("drops the hour component for races finished in under an hour", () => {
    const fiveK: Race = {
      name: "Tuesday 5K",
      date: "2026-05-19",
      distanceKm: 5,
      entries: [
        { name: "Ana Ferreira", club: "Silverbrook AC", seconds: 1024 },
        { name: "Joao Pedro Vasconcelos", club: "Riverside Runners", seconds: 1500 },
      ],
    };

    expect(renderRaceReport(fiveK)).toBe(
      [
        "Tuesday 5K - 2026-05-19",
        "=======================",
        "  1 Ana Ferreira           Silverbrook AC       17:04 3:25/km",
        "  2 Joao Pedro Vasconcelos Riverside Runners    25:00 5:00/km",
        "-----------------------",
        "Finishers: 2 of 2",
        "Fastest: Ana Ferreira (17:04)",
        "Average pace: 4:12/km",
      ].join("\n"),
    );
  });

  it("omits the fastest and average lines when nobody finished", () => {
    const abandoned: Race = {
      name: "Coldwater Fell Race",
      date: "2026-01-09",
      distanceKm: 12,
      entries: [
        { name: "Ines Rocha", club: "Coldwater Harriers", seconds: null },
        { name: "Paulo Serra", club: "Unattached", seconds: null },
      ],
    };

    expect(renderRaceReport(abandoned)).toBe(
      [
        "Coldwater Fell Race - 2026-01-09",
        "================================",
        "DNF Ines Rocha             Coldwater Harriers",
        "DNF Paulo Serra            Unattached",
        "--------------------------------",
        "Finishers: 0 of 2",
      ].join("\n"),
    );
  });

  it("rules the separator to the width of the title", () => {
    const report = renderRaceReport(halfMarathon).split("\n");
    const title = report[0] ?? "";
    expect(report[1]).toBe("=".repeat(title.length));
    expect(report).toContain("-".repeat(title.length));
  });

  // Guards against a sort comparator that stops being stable - the usual casualty of
  // "Substitute Algorithm" or a switch to a different sort helper.
  it("keeps runners with identical times in the order they were entered", () => {
    const tied: Race = {
      name: "Tie Test",
      date: "2026-02-01",
      distanceKm: 10,
      entries: [
        { name: "Zeta Last", club: "B", seconds: 3000 },
        { name: "Alpha First", club: "A", seconds: 3000 },
      ],
    };

    const rows = renderRaceReport(tied).split("\n").slice(2, 4);
    expect(rows[0]).toContain("Zeta Last");
    expect(rows[1]).toContain("Alpha First");
  });

  // Guards against merging the two passes over `entries` into one loop, which would
  // interleave the DNF lines with the ranked ones.
  it("lists every finisher before any DNF, and keeps DNFs in entry order", () => {
    const mixed: Race = {
      name: "DNF Order",
      date: "2026-02-02",
      distanceKm: 10,
      entries: [
        { name: "Zoe", club: "Z", seconds: null },
        { name: "Adam", club: "A", seconds: 2400 },
        { name: "Bea", club: "B", seconds: null },
      ],
    };

    expect(renderRaceReport(mixed)).toBe(
      [
        "DNF Order - 2026-02-02",
        "======================",
        "  1 Adam                   A                    40:00 4:00/km",
        "DNF Zoe                    Z",
        "DNF Bea                    B",
        "----------------------",
        "Finishers: 1 of 3",
        "Fastest: Adam (40:00)",
        "Average pace: 4:00/km",
      ].join("\n"),
    );
  });

  // Guards the n=1 arithmetic when the running total becomes a query over the finishers.
  it("averages a single finisher to that finisher's own pace", () => {
    const solo: Race = {
      name: "Solo",
      date: "2026-02-03",
      distanceKm: 10,
      entries: [{ name: "Only One", club: "Solo AC", seconds: 2700 }],
    };

    expect(renderRaceReport(solo)).toContain("Average pace: 4:30/km");
  });

  // Guards against "tidying up" the columns into a truncation while extracting the
  // line renderer. Long names overflow the column; they are not cut.
  it("lets a name wider than its column push the row out instead of truncating", () => {
    const overflowing: Race = {
      name: "Overflow",
      date: "2026-02-04",
      distanceKm: 10,
      entries: [
        {
          name: "Maria Fernanda Albuquerque Santos",
          club: "A Very Long Club Name Indeed",
          seconds: 2400,
        },
      ],
    };

    expect(renderRaceReport(overflowing)).toContain(
      "  1 Maria Fernanda Albuquerque Santos A Very Long Club Name Indeed 40:00 4:00/km",
    );
  });

  // Guards the empty case, where there is no first element to reach for.
  it("still rules a header and a footer for a race nobody entered", () => {
    const nobody: Race = {
      name: "Nobody",
      date: "2026-02-05",
      distanceKm: 10,
      entries: [],
    };

    expect(renderRaceReport(nobody)).toBe(
      [
        "Nobody - 2026-02-05",
        "===================",
        "-------------------",
        "Finishers: 0 of 0",
      ].join("\n"),
    );
  });
});
