import { describe, expect, it } from "vitest";
import {
  borrowItem,
  currentLoanCount,
  loansDueSoon,
  openAccount,
  returnItem,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

describe("borrowItem", () => {
  it("adds a loan, and refuses the same item a second time", () => {
    const account = openAccount("MBR-118");

    expect(borrowItem(account, "BK-204", "2026-08-20")).toEqual({ borrowed: true });
    expect(currentLoanCount(account)).toBe(1);

    const again = borrowItem(account, "BK-204", "2026-08-27");
    expect(again.borrowed).toBe(false);
    expect(again.reason).toContain("already holds BK-204");
    expect(currentLoanCount(account)).toBe(1);
  });

  // Guards the cap boundary, and that a refusal at the cap does not sneak the sixth
  // loan in anyway - the usual casualty of checking the limit after the write.
  it("refuses a sixth loan once the member is at the cap, leaving the count at five", () => {
    const account = openAccount("MBR-118");
    for (const item of ["BK-1", "BK-2", "BK-3", "BK-4", "BK-5"]) {
      expect(borrowItem(account, item, "2026-08-20").borrowed).toBe(true);
    }

    const sixth = borrowItem(account, "BK-6", "2026-08-20");

    expect(sixth.borrowed).toBe(false);
    expect(sixth.reason).toContain("loan limit");
    expect(currentLoanCount(account)).toBe(5);
  });
});

describe("returnItem", () => {
  // Guards against a return that only decrements a counter without actually clearing
  // the item - the loan has to be gone, not just uncounted, or re-borrowing would fail.
  it("removes a held item and lets it be borrowed again", () => {
    const account = openAccount("MBR-118");
    borrowItem(account, "BK-204", "2026-08-20");

    expect(returnItem(account, "BK-204")).toBe(true);
    expect(currentLoanCount(account)).toBe(0);
    expect(borrowItem(account, "BK-204", "2026-09-10")).toEqual({ borrowed: true });
  });

  it("reports false for an item that was never on loan, without changing the count", () => {
    const account = openAccount("MBR-118");
    borrowItem(account, "BK-204", "2026-08-20");

    expect(returnItem(account, "BK-999")).toBe(false);
    expect(currentLoanCount(account)).toBe(1);
  });
});

describe("loansDueSoon", () => {
  const today = "2026-08-01";

  it("lists items due within the window, soonest first", () => {
    const account = openAccount("MBR-118");
    borrowItem(account, "BK-B", "2026-08-05");
    borrowItem(account, "BK-A", "2026-08-03");

    const dueSoon = loansDueSoon(account, today, 5);

    expect(dueSoon.map((entry) => entry.itemId)).toEqual(["BK-A", "BK-B"]);
    expect(dueSoon[0]).toEqual({ itemId: "BK-A", dueOn: "2026-08-03", daysUntilDue: 2 });
  });

  // Guards against treating "due soon" as "not yet returned" - an item already overdue
  // is a different report, not a longer window.
  it("excludes an item due beyond the window, and one already overdue", () => {
    const account = openAccount("MBR-118");
    borrowItem(account, "BK-FAR", "2026-08-10");
    borrowItem(account, "BK-LATE", "2026-07-30");

    expect(loansDueSoon(account, today, 5)).toEqual([]);
  });

  // Guards the off-by-one at the edge of the window: exactly `withinDays` away is in,
  // one day further is out.
  it("includes an item due exactly on the last day of the window", () => {
    const account = openAccount("MBR-118");
    borrowItem(account, "BK-EDGE", "2026-08-06");
    borrowItem(account, "BK-JUST-OUT", "2026-08-07");

    const dueSoon = loansDueSoon(account, today, 5);

    expect(dueSoon.map((entry) => entry.itemId)).toEqual(["BK-EDGE"]);
  });
});
