import { describe, expect, it } from "vitest";
import { overdueNotice, type Loan } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

function loan(overrides: Partial<Loan> = {}): Loan {
  return {
    itemKind: "book",
    dueOn: "2026-08-01",
    returnedOn: null,
    ...overrides,
  };
}

describe("overdueNotice", () => {
  it("reports nothing owed before the due date", () => {
    expect(overdueNotice(loan({ dueOn: "2026-08-20" }), "2026-08-15")).toBe(
      "Not overdue.",
    );
  });

  // Guards the boundary: due today is not yet late. An off-by-one here is the classic
  // casualty of moving this comparison during a refactor.
  it("does not call a loan overdue on the day it is due", () => {
    expect(overdueNotice(loan({ dueOn: "2026-08-20" }), "2026-08-20")).toBe(
      "Not overdue.",
    );
  });

  // Guards the other boundary: exactly at the edge of the grace period is still inside
  // it, not one day past.
  it("charges no fine while still inside the grace period", () => {
    expect(overdueNotice(loan({ dueOn: "2026-08-01" }), "2026-08-04")).toBe(
      "3 day(s) overdue, within the grace period - no fine.",
    );
  });

  // Guards chargeableDays being derived from daysLate rather than recomputed by hand -
  // the exact duplication Replace Temp with Query exists to remove.
  it("charges only the days past the grace period, at the item's daily rate", () => {
    expect(overdueNotice(loan({ dueOn: "2026-08-01" }), "2026-08-10")).toBe(
      "9 day(s) overdue (6 chargeable) - fine $0.60.",
    );
  });

  // Guards the per-item-kind rate surviving the move from a temp to a query.
  it("charges a DVD at its own, higher daily rate", () => {
    expect(
      overdueNotice(loan({ itemKind: "dvd", dueOn: "2026-08-01" }), "2026-08-06"),
    ).toBe("5 day(s) overdue (2 chargeable) - fine $1.00.");
  });

  // Guards the cap: once the raw fine would exceed it, the notice both caps the amount
  // and says so, rather than one of the two silently falling out of sync with the other.
  it("caps the fine and says so, once the raw amount would exceed it", () => {
    expect(
      overdueNotice(loan({ itemKind: "equipment", dueOn: "2026-07-01" }), "2026-08-01"),
    ).toBe("31 day(s) overdue (28 chargeable) - fine $15.00 (capped).");
  });

  // Guards effectiveReturnDate: lateness for a returned item is measured against the
  // day it came back, not against whatever "today" happens to be when the report runs.
  it("measures a returned loan's lateness against its return date, not today", () => {
    const returned = loan({ dueOn: "2026-08-01", returnedOn: "2026-08-05" });
    expect(overdueNotice(returned, "2026-09-01")).toBe(
      "4 day(s) overdue (1 chargeable) - fine $0.10.",
    );
  });

  it("treats a loan returned before its due date as not overdue", () => {
    const returned = loan({ dueOn: "2026-08-10", returnedOn: "2026-08-05" });
    expect(overdueNotice(returned, "2026-09-01")).toBe("Not overdue.");
  });

  // Guards the date arithmetic across a month boundary, the usual casualty of a
  // hand-rolled day-of-month subtraction creeping back in during a refactor.
  it("counts days correctly across a month boundary", () => {
    expect(overdueNotice(loan({ dueOn: "2026-01-30" }), "2026-03-02")).toBe(
      "31 day(s) overdue (28 chargeable) - fine $2.80.",
    );
  });
});
