import { describe, expect, it } from "vitest";
import { isEligibleForSameDaySlot, type OnCallLog, type Patient } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

function ineligiblePatient(overrides: Partial<Patient>): Patient {
  return {
    triageScore: 1,
    ageMonths: 60,
    hasChronicCondition: false,
    flaggedForNurseReview: false,
    ...overrides,
  };
}

function freshLog(): OnCallLog {
  return { pagesSent: 0 };
}

describe("isEligibleForSameDaySlot", () => {
  it("is not eligible when none of the conditions hold", () => {
    expect(isEligibleForSameDaySlot(ineligiblePatient({}), freshLog())).toBe(false);
  });

  it("is eligible once the triage score meets the urgent threshold", () => {
    const patient = ineligiblePatient({ triageScore: 4 });
    expect(isEligibleForSameDaySlot(patient, freshLog())).toBe(true);
  });

  // Guards the boundary a consolidated `>=` could quietly become `>`.
  it("is not eligible just below the urgent triage threshold", () => {
    const patient = ineligiblePatient({ triageScore: 3 });
    expect(isEligibleForSameDaySlot(patient, freshLog())).toBe(false);
  });

  it("is eligible for an infant under the age cutoff", () => {
    const patient = ineligiblePatient({ ageMonths: 23 });
    expect(isEligibleForSameDaySlot(patient, freshLog())).toBe(true);
  });

  // Guards the boundary a consolidated `<` could quietly become `<=`.
  it("is not eligible at exactly the infant age cutoff", () => {
    const patient = ineligiblePatient({ ageMonths: 24 });
    expect(isEligibleForSameDaySlot(patient, freshLog())).toBe(false);
  });

  it("is eligible for a patient with a chronic condition on file", () => {
    const patient = ineligiblePatient({ hasChronicCondition: true });
    expect(isEligibleForSameDaySlot(patient, freshLog())).toBe(true);
  });

  it("pages the on-call nurse and is eligible when flagged for review", () => {
    const log = freshLog();
    const patient = ineligiblePatient({ flaggedForNurseReview: true });
    expect(isEligibleForSameDaySlot(patient, log)).toBe(true);
    expect(log.pagesSent).toBe(1);
  });

  // The one this drill is about. A naive merge of all four conditions into one ||
  // expression short-circuits: once triageScore already makes the patient eligible,
  // `|| pageOnCallNurseIfFlagged(...)` is never evaluated and the page never fires.
  // The correct consolidation only folds in the three side-effect-free conditions and
  // still pages regardless of whether the patient already qualifies some other way.
  it("still pages the on-call nurse even when the patient already qualifies through triage", () => {
    const log = freshLog();
    const patient = ineligiblePatient({ triageScore: 4, flaggedForNurseReview: true });
    expect(isEligibleForSameDaySlot(patient, log)).toBe(true);
    expect(log.pagesSent).toBe(1);
  });

  // Guards against the paging call firing unconditionally regardless of the flag.
  it("does not page the on-call nurse when the patient is not flagged, even if eligible", () => {
    const log = freshLog();
    const patient = ineligiblePatient({ hasChronicCondition: true });
    isEligibleForSameDaySlot(patient, log);
    expect(log.pagesSent).toBe(0);
  });
});
