import { describe, expect, it } from "vitest";
import { isEligible, type Course, type Runner } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible refactoring of this file could silently
 * change - not one per line. Each test names the move it guards against.
 */

const licensedAdult: Runner = {
  age: 32,
  isSuspended: false,
  hasGuardianConsent: false,
  hasClubLicense: true,
  personalBestSeconds: 4200,
};

const openFiveK: Course = {
  name: "Silverbrook Open 5K",
  minAge: 10,
  requiresLicense: false,
  qualifyingSeconds: null,
};

const clubTenK: Course = {
  name: "Members-Only 10K",
  minAge: 14,
  requiresLicense: true,
  qualifyingSeconds: null,
};

const eliteHalf: Course = {
  name: "Elite Half Marathon Corral",
  minAge: 18,
  requiresLicense: true,
  qualifyingSeconds: 4800,
};

describe("isEligible", () => {
  it("accepts a licensed adult who meets every requirement of an elite course", () => {
    expect(isEligible(licensedAdult, eliteHalf)).toBe(true);
  });

  it("accepts anyone for an open course with no license or qualifying time", () => {
    const beginner: Runner = {
      ...licensedAdult,
      hasClubLicense: false,
      personalBestSeconds: null,
    };
    expect(isEligible(beginner, openFiveK)).toBe(true);
  });

  // Guards against the suspension check disappearing while it is being inlined - a
  // suspended runner must be rejected even when every other rule passes.
  it("rejects a suspended runner even when every other rule is satisfied", () => {
    const suspended: Runner = { ...licensedAdult, isSuspended: true };
    expect(isEligible(suspended, eliteHalf)).toBe(false);
  });

  // Guards the minAge boundary, which is inclusive: turning >= into > would reject a
  // runner on the exact day they become old enough.
  it("accepts a runner exactly at the course's minimum age and rejects one year younger", () => {
    const atMinimum: Runner = {
      ...licensedAdult,
      age: 14,
      hasClubLicense: true,
      hasGuardianConsent: true,
    };
    const oneYearYounger: Runner = { ...atMinimum, age: 13 };
    expect(isEligible(atMinimum, clubTenK)).toBe(true);
    expect(isEligible(oneYearYounger, clubTenK)).toBe(false);
  });

  // Guards the consent rule: a minor without guardian consent is out regardless of the
  // course's own minimum age, and consent lets them back in.
  it("requires guardian consent for a minor even on a course that would otherwise admit them", () => {
    const minorNoConsent: Runner = {
      ...licensedAdult,
      age: 16,
      hasGuardianConsent: false,
    };
    const minorWithConsent: Runner = { ...minorNoConsent, hasGuardianConsent: true };
    expect(isEligible(minorNoConsent, openFiveK)).toBe(false);
    expect(isEligible(minorWithConsent, openFiveK)).toBe(true);
  });

  // Guards the CONSENT_AGE boundary itself, separate from any course's minAge - a
  // seventeen-year-old needs consent, an eighteen-year-old does not.
  it("stops requiring guardian consent at exactly the consent age", () => {
    const seventeen: Runner = { ...licensedAdult, age: 17, hasGuardianConsent: false };
    const eighteen: Runner = { ...seventeen, age: 18 };
    expect(isEligible(seventeen, openFiveK)).toBe(false);
    expect(isEligible(eighteen, openFiveK)).toBe(true);
  });

  // Guards the license check's short-circuit in both directions: it must not block a
  // course that doesn't require one, and must block one that does.
  it("only enforces the license requirement on courses that ask for one", () => {
    const unlicensed: Runner = { ...licensedAdult, hasClubLicense: false };
    expect(isEligible(unlicensed, openFiveK)).toBe(true);
    expect(isEligible(unlicensed, clubTenK)).toBe(false);
  });

  // Guards the qualifying-time rule at both ends: no cutoff means no runner's personal
  // best is checked, but a cutoff that exists must reject a runner with no recorded time -
  // the null case cannot silently pass just because it also means "no requirement".
  it("only requires a recorded personal best when the course has a qualifying cutoff", () => {
    const noPersonalBest: Runner = { ...licensedAdult, personalBestSeconds: null };
    expect(isEligible(noPersonalBest, clubTenK)).toBe(true);
    expect(isEligible(noPersonalBest, eliteHalf)).toBe(false);
  });

  // Guards the <= boundary on the qualifying time: exactly on the cutoff passes, one
  // second over it fails.
  it("accepts a personal best exactly at the qualifying time and rejects one second slower", () => {
    const onTheCutoff: Runner = { ...licensedAdult, personalBestSeconds: 4800 };
    const oneSecondSlower: Runner = { ...licensedAdult, personalBestSeconds: 4801 };
    expect(isEligible(onTheCutoff, eliteHalf)).toBe(true);
    expect(isEligible(oneSecondSlower, eliteHalf)).toBe(false);
  });

  // Guards against the checks being combined with anything but AND: failing exactly one
  // of several otherwise-satisfied rules must still fail the whole thing.
  it("fails overall when exactly one requirement among several passing ones fails", () => {
    const failsOnlyLicense: Runner = { ...licensedAdult, hasClubLicense: false };
    expect(isEligible(failsOnlyLicense, eliteHalf)).toBe(false);
  });
});
