import { describe, expect, it } from "vitest";
import { renderTrainingSheet, type Runner, type TrainingPlan } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour that a *plausible* refactoring of this file could
 * silently change - not one per line. Each test below names the move it is guarding
 * against.
 */

const ana: Runner = {
  name: "Ana Ferreira",
  weeklyBaseKm: 40,
  thresholdPaceSecondsPerKm: 240,
};

describe("renderTrainingSheet", () => {
  it("renders the header, one row per week in plan order, and the total distance", () => {
    const plan: TrainingPlan = {
      race: "Coldwater Marathon",
      weeks: [
        { label: "Base 1", loadFactor: 1.0, paceOffsetSecondsPerKm: 30, recovery: false },
        { label: "Peak", loadFactor: 1.25, paceOffsetSecondsPerKm: 0, recovery: false },
        {
          label: "Recovery",
          loadFactor: 0.5,
          paceOffsetSecondsPerKm: 45,
          recovery: true,
        },
      ],
    };

    expect(renderTrainingSheet(ana, plan)).toBe(
      [
        "Ana Ferreira - Coldwater Marathon",
        "=================================",
        "Base 1        40 km  4:30/km",
        "Peak          50 km  4:00/km",
        "Recovery      20 km  4:45/km (recovery)",
        "---------------------------------",
        "Total: 110 km",
      ].join("\n"),
    );
  });

  it("rules the header and footer to the width of the title", () => {
    const plan: TrainingPlan = {
      race: "Coldwater Marathon",
      weeks: [
        { label: "Base 1", loadFactor: 1.0, paceOffsetSecondsPerKm: 0, recovery: false },
      ],
    };

    const lines = renderTrainingSheet(ana, plan).split("\n");
    const title = lines[0] ?? "";
    expect(lines[1]).toBe("=".repeat(title.length));
    expect(lines).toContain("-".repeat(title.length));
  });

  // Guards against a marker that leaks onto every row, or a boolean that gets read
  // backwards while the recovery flag moves from a raw field to a class query.
  it("marks only the weeks flagged as recovery, leaving the others unmarked", () => {
    const plan: TrainingPlan = {
      race: "Marker Check",
      weeks: [
        { label: "Hard", loadFactor: 1.0, paceOffsetSecondsPerKm: 0, recovery: false },
        { label: "Easy", loadFactor: 0.5, paceOffsetSecondsPerKm: 0, recovery: true },
      ],
    };

    const lines = renderTrainingSheet(ana, plan).split("\n");
    expect(lines[2]).not.toContain("(recovery)");
    expect(lines[3]).toContain("(recovery)");
  });

  // Guards against the total becoming a sum of the unrounded per-week distances
  // (2.5 + 2.5 = 5, then rounded once) instead of a sum of the rounded ones a reader can
  // already see printed above it (3 + 3 = 6). Combine Functions into Class makes it easy
  // to accidentally reach for the runner's raw fields again instead of the same rounded
  // query the rows already used.
  it("totals the rounded per-week distances, not the total of the unrounded values", () => {
    const runner: Runner = {
      name: "Rounding Test",
      weeklyBaseKm: 40,
      thresholdPaceSecondsPerKm: 200,
    };
    const plan: TrainingPlan = {
      race: "Round Race",
      weeks: [
        {
          label: "Half Up A",
          loadFactor: 0.0625,
          paceOffsetSecondsPerKm: 0,
          recovery: false,
        },
        {
          label: "Half Up B",
          loadFactor: 0.0625,
          paceOffsetSecondsPerKm: 0,
          recovery: false,
        },
      ],
    };

    const lines = renderTrainingSheet(runner, plan).split("\n");
    expect(lines[2]).toContain(" 3 km");
    expect(lines[3]).toContain(" 3 km");
    expect(lines).toContain("Total: 6 km");
  });

  // Guards the empty case, where there is no first week to reach for.
  it("still renders a header and footer for a plan with no weeks yet", () => {
    const plan: TrainingPlan = { race: "Not Started Yet", weeks: [] };

    expect(renderTrainingSheet(ana, plan)).toBe(
      [
        "Ana Ferreira - Not Started Yet",
        "==============================",
        "------------------------------",
        "Total: 0 km",
      ].join("\n"),
    );
  });

  // Guards the n=1 arithmetic when the total becomes a loop, or a sum, over the weeks.
  it("totals a single-week plan to that week's own distance", () => {
    const plan: TrainingPlan = {
      race: "Solo Half",
      weeks: [
        {
          label: "Only Week",
          loadFactor: 0.9,
          paceOffsetSecondsPerKm: 10,
          recovery: false,
        },
      ],
    };

    expect(renderTrainingSheet(ana, plan)).toContain("Total: 36 km");
  });

  // Guards against "tidying up" the label column into a truncation. A label wider than
  // its padding pushes the row out instead of losing characters.
  it("lets a week label wider than its column push the row out instead of truncating", () => {
    const runner: Runner = {
      name: "Big Runner",
      weeklyBaseKm: 999,
      thresholdPaceSecondsPerKm: 200,
    };
    const plan: TrainingPlan = {
      race: "Ultra",
      weeks: [
        {
          label: "An Extremely Long Week Label That Overflows",
          loadFactor: 1.0,
          paceOffsetSecondsPerKm: 0,
          recovery: false,
        },
      ],
    };

    expect(renderTrainingSheet(runner, plan)).toContain(
      "An Extremely Long Week Label That Overflows 999 km  3:20/km",
    );
  });

  // Guards the seconds padding in formatPace: an exact whole minute must still print
  // "00", not the bare "0" that padStart exists to prevent.
  it("pads the seconds of a pace that lands on an exact whole minute", () => {
    const runner: Runner = {
      name: "Whole Minute",
      weeklyBaseKm: 40,
      thresholdPaceSecondsPerKm: 300,
    };
    const plan: TrainingPlan = {
      race: "Whole Minute Race",
      weeks: [
        { label: "Steady", loadFactor: 1.0, paceOffsetSecondsPerKm: 0, recovery: false },
      ],
    };

    expect(renderTrainingSheet(runner, plan)).toContain("5:00/km");
  });

  // Guards the sign of the pace offset: a speed week is faster than threshold pace, so
  // the offset must subtract rather than always adding an "absolute" adjustment.
  it("applies a negative pace offset, for a week faster than threshold pace", () => {
    const runner: Runner = {
      name: "Speedy",
      weeklyBaseKm: 40,
      thresholdPaceSecondsPerKm: 240,
    };
    const plan: TrainingPlan = {
      race: "Speed Block",
      weeks: [
        { label: "Speed", loadFactor: 0.6, paceOffsetSecondsPerKm: -20, recovery: false },
      ],
    };

    expect(renderTrainingSheet(runner, plan)).toContain("3:40/km");
  });
});
