import { describe, expect, it } from "vitest";
import {
  publicSectionHasAvailability,
  sectionAvailabilitySummary,
  staffSectionHasAvailability,
  type Seat,
  type SeatStatus,
  type Show,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Replace Query with
 * Parameter is that a signature changes - `sectionHasAvailability` stops reading a reserve
 * count from module state and starts taking it as an argument instead. So this suite
 * imports only the three callers - `publicSectionHasAvailability`,
 * `staffSectionHasAvailability`, `sectionAvailabilitySummary` - and never the availability
 * check by name, because reshaping it is the entire point.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function seat(section: string, status: SeatStatus = "open"): Seat {
  return { section, status };
}

function showWith(openSeatsInStalls: number, otherSeats: Seat[] = []): Show {
  const stalls = Array.from({ length: openSeatsInStalls }, () => seat("Stalls"));
  return { title: "Halliday Winter Gala", seats: [...stalls, ...otherSeats] };
}

describe("publicSectionHasAvailability", () => {
  it("is true once the section has more open seats than the public hold", () => {
    expect(publicSectionHasAvailability(showWith(3), "Stalls")).toBe(true);
  });

  // Guards against the public hold being dropped or applied as >= instead of >.
  it("is false once only the held-back seats remain", () => {
    expect(publicSectionHasAvailability(showWith(2), "Stalls")).toBe(false);
  });

  it("is false for a section with no open seats at all", () => {
    const show = showWith(0, [seat("Stalls", "booked")]);
    expect(publicSectionHasAvailability(show, "Stalls")).toBe(false);
  });

  // Guards against dropping the section filter.
  it("never counts an open seat from a different section", () => {
    const show = showWith(0, [seat("Circle")]);
    expect(publicSectionHasAvailability(show, "Stalls")).toBe(false);
  });
});

describe("staffSectionHasAvailability", () => {
  // Guards against staff and public sharing the same hold count.
  it("is true for exactly the seats the public view calls unavailable", () => {
    const show = showWith(2);
    expect(publicSectionHasAvailability(show, "Stalls")).toBe(false);
    expect(staffSectionHasAvailability(show, "Stalls")).toBe(true);
  });

  it("is false once every seat in the section is taken", () => {
    const show = showWith(0, [seat("Stalls", "held")]);
    expect(staffSectionHasAvailability(show, "Stalls")).toBe(false);
  });
});

describe("sectionAvailabilitySummary", () => {
  // Guards against the two halves of the summary sharing one mutated value instead of
  // being computed independently.
  it("reports both views at once without either one affecting the other", () => {
    const show = showWith(2);
    expect(sectionAvailabilitySummary(show, "Stalls")).toEqual({
      publicAvailability: false,
      staffAvailability: true,
    });
  });

  // Guards against the order the two halves are computed in mattering.
  it("agrees with the two single-purpose callers for the same show", () => {
    const show = showWith(5);
    const summary = sectionAvailabilitySummary(show, "Stalls");
    expect(summary.publicAvailability).toBe(publicSectionHasAvailability(show, "Stalls"));
    expect(summary.staffAvailability).toBe(staffSectionHasAvailability(show, "Stalls"));
  });
});
