import { describe, expect, it } from "vitest";
import {
  InstrumentRental,
  LeaseToOwnRental,
  rentalLine,
  totalBuyoutCreditsCents,
  TrialRental,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of pushing buyoutCreditsCents down into LeaseToOwnRental.
 * Do not edit this file: if a refactoring seems to require changing a test, either the
 * refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Push Down Field could silently change - not
 * one per class. Each test names the move it is guarding against.
 */

const trial = new TrialRental({
  id: "R-1",
  studentName: "Ines Okafor",
  instrumentName: "Yamaha YCL-255 Clarinet",
  monthlyFeeCents: 2500,
  weeksRemaining: 4,
});

const leased = new LeaseToOwnRental({
  id: "R-2",
  studentName: "Marcus Bell",
  instrumentName: "Cecilio Full-Size Cello",
  monthlyFeeCents: 4500,
  purchasePriceCents: 180_000,
  buyoutCreditsCents: 54_000,
});

describe("rentalLine", () => {
  // Guards a trial rental's line staying free of any buyout mention - it never had a
  // buyout balance to report, and pushing the field down must not invent one.
  it("omits any buyout mention for a trial rental", () => {
    expect(rentalLine(trial)).toBe("Ines Okafor - Yamaha YCL-255 Clarinet ($25.00/mo)");
  });

  // Guards the buyout line appearing, with the right amount, for a lease-to-own rental.
  it("credits the accrued buyout balance on a lease-to-own rental's line", () => {
    expect(rentalLine(leased)).toBe(
      "Marcus Bell - Cecilio Full-Size Cello ($45.00/mo), $540.00 credited toward buyout",
    );
  });

  // Boundary: a lease-to-own rental with no credits yet still reports the line, at $0.00
  // rather than falling back to the trial-rental phrasing.
  it("still reports a buyout line of zero for a lease-to-own rental with no credits yet", () => {
    const fresh = new LeaseToOwnRental({
      id: "R-3",
      studentName: "Priya Nadar",
      instrumentName: "Stagg Viola",
      monthlyFeeCents: 3000,
      purchasePriceCents: 90_000,
      buyoutCreditsCents: 0,
    });
    expect(rentalLine(fresh)).toBe(
      "Priya Nadar - Stagg Viola ($30.00/mo), $0.00 credited toward buyout",
    );
  });
});

describe("totalBuyoutCreditsCents", () => {
  // Guards a mixed roster: the trial rental must contribute nothing, and must not be
  // skipped in a way that also silently skips the lease-to-own rental beside it.
  it("counts only the lease-to-own rentals in a mixed roster", () => {
    const roster: InstrumentRental[] = [trial, leased];
    expect(totalBuyoutCreditsCents(roster)).toBe(54_000);
  });

  // Guards against a roster of trial rentals only reporting anything but zero.
  it("returns zero for a roster with no lease-to-own rentals", () => {
    expect(totalBuyoutCreditsCents([trial])).toBe(0);
  });

  // Guards the empty case, where there is nothing to filter or reduce over.
  it("returns zero for an empty roster", () => {
    expect(totalBuyoutCreditsCents([])).toBe(0);
  });
});

describe("LeaseToOwnRental.remainingBuyoutCents", () => {
  // Guards the ordinary case: purchase price minus credits accrued so far.
  it("subtracts accrued credits from the purchase price", () => {
    expect(leased.remainingBuyoutCents()).toBe(126_000);
  });

  // Boundary: credits accrued cannot push the remaining balance below zero, once a
  // student has paid in more than the purchase price.
  it("floors the remaining balance at zero once credits exceed the purchase price", () => {
    const paidOff = new LeaseToOwnRental({
      id: "R-4",
      studentName: "Owen Tran",
      instrumentName: "Jupiter Trombone",
      monthlyFeeCents: 3500,
      purchasePriceCents: 60_000,
      buyoutCreditsCents: 63_000,
    });
    expect(paidOff.remainingBuyoutCents()).toBe(0);
  });
});

describe("shared identity", () => {
  // Guards the base fields staying reachable on both rental kinds after the field that
  // only one of them needs moves off the shared base.
  it("exposes id, studentName, and monthlyFeeCents on both rental kinds", () => {
    expect(trial.id).toBe("R-1");
    expect(trial.studentName).toBe("Ines Okafor");
    expect(leased.monthlyFeeCents).toBe(4500);
  });
});
