import { describe, expect, it } from "vitest";
import { appointmentChargeCents, type Appointment, type Tariff } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

const tariff: Tariff = {
  baseFeeCents: 8000,
  gstMultiplier: 1.1,
  outOfHoursMultiplier: 1.5,
  outOfHoursSurchargeCents: 4500,
};

function apptAt(overrides: Partial<Appointment>): Appointment {
  return {
    startMinute: 600,
    durationMinutes: 30,
    isWeekend: false,
    isPublicHoliday: false,
    ...overrides,
  };
}

describe("appointmentChargeCents", () => {
  it("charges the standard rate for a weekday appointment inside opening hours", () => {
    expect(appointmentChargeCents(apptAt({}), tariff)).toBe(8800);
  });

  it("charges the out-of-hours rate when the appointment starts before opening", () => {
    expect(appointmentChargeCents(apptAt({ startMinute: 420 }), tariff)).toBe(16500);
  });

  it("charges the out-of-hours rate when the appointment runs past closing", () => {
    const appt = apptAt({ startMinute: 1030, durationMinutes: 60 });
    expect(appointmentChargeCents(appt, tariff)).toBe(16500);
  });

  // Guards the lower boundary: extracting isOutOfHours must keep < strict, not <=.
  it("still charges the standard rate for an appointment starting at the opening minute", () => {
    expect(appointmentChargeCents(apptAt({ startMinute: 480 }), tariff)).toBe(8800);
  });

  // Guards the upper boundary: an appointment that ends exactly at closing time is not
  // out of hours - only one that runs past it is.
  it("still charges the standard rate for an appointment ending exactly at closing time", () => {
    const appt = apptAt({ startMinute: 1020, durationMinutes: 60 });
    expect(appointmentChargeCents(appt, tariff)).toBe(8800);
  });

  it("charges the out-of-hours rate for a weekend appointment inside normal opening hours", () => {
    expect(appointmentChargeCents(apptAt({ isWeekend: true }), tariff)).toBe(16500);
  });

  it("charges the out-of-hours rate for a public holiday appointment inside normal opening hours", () => {
    expect(appointmentChargeCents(apptAt({ isPublicHoliday: true }), tariff)).toBe(16500);
  });

  // Guards against the condition being rewritten as a count of matching reasons instead
  // of a boolean OR - two reasons to surcharge must not stack into two surcharges.
  it("does not stack the surcharge when an appointment is both a weekend and a public holiday", () => {
    const appt = apptAt({ isWeekend: true, isPublicHoliday: true });
    expect(appointmentChargeCents(appt, tariff)).toBe(16500);
  });

  // Guards against Math.round moving inside a branch, or being dropped from one of them.
  it("rounds a fractional standard-hours charge to the nearest whole cent", () => {
    const oddTariff: Tariff = { ...tariff, baseFeeCents: 8333 };
    expect(appointmentChargeCents(apptAt({}), oddTariff)).toBe(9166);
  });
});
