import { describe, expect, it } from "vitest";
import {
  holdNextAvailableSeat,
  nextSeatQuote,
  sectionHasAvailability,
  type Seat,
  type SeatStatus,
  type Show,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Separate Query
 * from Modifier is that a signature changes - `findSeatAndReserve` splits into two. So
 * this suite imports only the three callers - `holdNextAvailableSeat`, `nextSeatQuote`,
 * `sectionHasAvailability` - and never the seat-lookup function by name. It pins what
 * every caller returns and, where the two versions must agree, what it does to the seat
 * map. It says nothing about how many functions do the finding underneath.
 *
 * One thing it deliberately does NOT pin: whether asking for a quote or checking
 * availability leaves a seat held afterwards. Against the challenge those two callers
 * hold a seat as a side effect of looking; against the solution they don't - that is the
 * bug this refactoring removes, and the shared suite has to stay green against both, so it
 * cannot take a side. The proof that the solution fixed it lives in `tests-fixed/`.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function seat(
  section: string,
  row: number,
  number: number,
  priceCents: number,
  status: SeatStatus = "open",
): Seat {
  return { section, row, number, priceCents, status, heldBy: null };
}

function galaNight(): Show {
  return {
    title: "Halliday Winter Gala",
    seats: [
      seat("Stalls", 1, 1, 6000),
      seat("Stalls", 1, 2, 6000),
      seat("Stalls", 1, 3, 6000, "held"),
      seat("Stalls", 2, 1, 5000),
      seat("Stalls", 2, 2, 5000, "booked"),
      seat("Circle", 1, 1, 4000),
    ],
  };
}

describe("holdNextAvailableSeat", () => {
  it("holds the lowest-numbered open seat in the lowest row of the section", () => {
    const show = galaNight();
    const held = holdNextAvailableSeat(show, "Stalls", "C-1");
    expect(held).toMatchObject({ section: "Stalls", row: 1, number: 1 });
  });

  it("marks the held seat's status and customer on the show's own seat map", () => {
    const show = galaNight();
    holdNextAvailableSeat(show, "Stalls", "C-1");
    const seatOne = show.seats.find((s) => s.row === 1 && s.number === 1);
    expect(seatOne).toMatchObject({ status: "held", heldBy: "C-1" });
  });

  // Guards against a comparator that sorts by seat number before row - the front row
  // should win even when a later row happens to have a lower seat number.
  it("prefers a lower row over a lower seat number in a later row", () => {
    const show: Show = {
      title: "Row Order Test",
      seats: [seat("Stalls", 2, 1, 5000), seat("Stalls", 1, 9, 6000)],
    };

    expect(holdNextAvailableSeat(show, "Stalls", "C-1")).toMatchObject({
      row: 1,
      number: 9,
    });
  });

  // Guards against dropping the section filter while splitting the function in two.
  it("never offers a seat from a different section", () => {
    const show: Show = {
      title: "Section Test",
      seats: [seat("Stalls", 1, 1, 6000, "booked"), seat("Circle", 1, 1, 4000)],
    };

    expect(holdNextAvailableSeat(show, "Stalls", "C-1")).toBeNull();
  });

  // Guards against treating "held" as available - a seat mid-checkout for one customer
  // must not be offered to the next.
  it("skips seats that are already held or booked", () => {
    const show: Show = {
      title: "Skip Test",
      seats: [
        seat("Stalls", 1, 1, 6000, "held"),
        seat("Stalls", 1, 2, 6000, "booked"),
        seat("Stalls", 1, 3, 6000),
      ],
    };

    expect(holdNextAvailableSeat(show, "Stalls", "C-1")).toMatchObject({ number: 3 });
  });

  it("returns null once nothing is left to offer in the section", () => {
    const show: Show = {
      title: "Full Section",
      seats: [seat("Stalls", 1, 1, 6000, "held"), seat("Stalls", 1, 2, 6000, "booked")],
    };

    expect(holdNextAvailableSeat(show, "Stalls", "C-1")).toBeNull();
  });
});

describe("nextSeatQuote", () => {
  it("describes the same seat a hold would take, with its price", () => {
    const show = galaNight();
    expect(nextSeatQuote(show, "Stalls")).toEqual({
      section: "Stalls",
      row: 1,
      number: 1,
      priceCents: 6000,
    });
  });

  it("quotes nothing for a section with no open seats", () => {
    const show: Show = {
      title: "Full Section",
      seats: [seat("Stalls", 1, 1, 6000, "booked")],
    };

    expect(nextSeatQuote(show, "Stalls")).toBeNull();
  });
});

describe("sectionHasAvailability", () => {
  it("is true while the section still has an open seat", () => {
    expect(sectionHasAvailability(galaNight(), "Circle")).toBe(true);
  });

  it("is false once every seat in the section is held or booked", () => {
    const show: Show = {
      title: "Full Section",
      seats: [seat("Stalls", 1, 1, 6000, "held"), seat("Stalls", 1, 2, 6000, "booked")],
    };

    expect(sectionHasAvailability(show, "Stalls")).toBe(false);
  });

  // Guards the empty case: a section nobody seated at all is not the same code path as
  // one that filled up, and both must report unavailable.
  it("is false for a section with no seats at all", () => {
    const show: Show = { title: "No Such Section", seats: [seat("Stalls", 1, 1, 6000)] };
    expect(sectionHasAvailability(show, "Balcony")).toBe(false);
  });
});
