import { describe, expect, it } from "vitest";
import { staffPayoutCents, type Shift, type StaffMember } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of pulling the guard clauses out of the nested version.
 * Do not edit this file: if a refactoring seems to require changing a test, either the
 * refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Replace Nested Conditional with Guard
 * Clauses could silently change - not one per condition. Each test names the move it is
 * guarding against.
 */

function salariedStaff(overrides: Partial<StaffMember> = {}): StaffMember {
  return {
    id: "S-01",
    employmentType: "salaried",
    active: true,
    hourlyRateCents: 0,
    dailyRateCents: 32000,
    ...overrides,
  };
}

function hourlyStaff(overrides: Partial<StaffMember> = {}): StaffMember {
  return {
    id: "S-02",
    employmentType: "hourly",
    active: true,
    hourlyRateCents: 4200,
    dailyRateCents: 0,
    ...overrides,
  };
}

function completedShift(overrides: Partial<Shift> = {}): Shift {
  return {
    staffId: "S-01",
    status: "completed",
    durationMinutes: 360,
    payoutIssued: false,
    ...overrides,
  };
}

describe("staffPayoutCents", () => {
  // Guards against the salaried branch reading shift duration at all - it must not.
  it("pays a salaried staff member the flat daily rate for a completed shift", () => {
    const payout = staffPayoutCents(
      salariedStaff(),
      completedShift({ durationMinutes: 500 }),
    );
    expect(payout).toBe(32000);
  });

  // Guards against the hourly branch losing the per-minute rate on the way out of the nest.
  it("pays an hourly staff member rate times minutes under the overtime threshold", () => {
    const payout = staffPayoutCents(
      hourlyStaff(),
      completedShift({ durationMinutes: 360 }),
    );
    expect(payout).toBe(25200);
  });

  // Guards the overtime premium surviving the move - minutes past the threshold must be
  // paid at 1.5x, not folded into the regular rate.
  it("adds an overtime premium for minutes worked past the threshold", () => {
    const payout = staffPayoutCents(
      hourlyStaff(),
      completedShift({ durationMinutes: 540 }),
    );
    expect(payout).toBe(39900);
  });

  // Boundary: exactly at the threshold, not one minute of overtime is owed.
  it("charges no overtime premium for a shift that lands exactly on the threshold", () => {
    const payout = staffPayoutCents(
      hourlyStaff(),
      completedShift({ durationMinutes: 480 }),
    );
    expect(payout).toBe(33600);
  });

  // Guards the rounding step staying a single Math.round at the end, not one per minute.
  it("rounds a fractional hourly payout to the nearest cent", () => {
    const staff = hourlyStaff({ hourlyRateCents: 333 });
    const payout = staffPayoutCents(staff, completedShift({ durationMinutes: 47 }));
    expect(payout).toBe(261);
  });

  // Guards the first precondition surviving as an early exit, not getting dropped or
  // reordered below the employment-type decision.
  it("pays nothing to an inactive staff member even for a completed shift", () => {
    const payout = staffPayoutCents(salariedStaff({ active: false }), completedShift());
    expect(payout).toBe(0);
  });

  // Guards the second precondition: a shift that never completed pays nothing, whatever
  // duration it logged.
  it("pays nothing for a shift that was not completed", () => {
    const payout = staffPayoutCents(hourlyStaff(), completedShift({ status: "no-show" }));
    expect(payout).toBe(0);
  });

  // Guards against double payout: a shift whose payout already went to payroll must not
  // be paid again, regardless of employment type or duration.
  it("pays nothing for a shift whose payout was already issued", () => {
    const payout = staffPayoutCents(
      salariedStaff(),
      completedShift({ payoutIssued: true }),
    );
    expect(payout).toBe(0);
  });
});
