import { describe, expect, it } from "vitest";
import {
  bestStandingSpot,
  bestUpgradeCandidate,
  type Seat,
  type StandingSpot,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Preserve Whole
 * Object is that the scoring function's signature changes - it stops taking three loose
 * fields and starts taking a `Seat`. So this suite imports only the two callers -
 * `bestUpgradeCandidate` and `bestStandingSpot` - and never the scoring function itself.
 * It pins which seat or spot wins and why, never how many arguments the scorer underneath
 * takes.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function seat(
  section: string,
  distanceFromStageMeters: number,
  offsetFromCenterMeters: number,
  hasRestrictedView = false,
): Seat {
  return { section, distanceFromStageMeters, offsetFromCenterMeters, hasRestrictedView };
}

function spot(
  label: string,
  distanceFromStageMeters: number,
  offsetFromCenterMeters: number,
): StandingSpot {
  return { label, distanceFromStageMeters, offsetFromCenterMeters };
}

describe("bestUpgradeCandidate", () => {
  it("prefers the seat that is closer to the stage and more centered", () => {
    const close = seat("Stalls", 5, 0);
    const far = seat("Circle", 40, 10);
    expect(bestUpgradeCandidate([far, close])).toBe(close);
  });

  // Guards against dropping the restricted-view penalty while changing the signature:
  // a very close but restricted seat must still lose to a merely decent open one.
  it("halves a restricted-view seat's score, enough to change the ranking", () => {
    const closeButRestricted = seat("Stalls", 2, 0, true);
    const decentAndOpen = seat("Circle", 20, 5, false);
    expect(bestUpgradeCandidate([closeButRestricted, decentAndOpen])).toBe(decentAndOpen);
  });

  // Guards the comparison operator: a strict ">" keeps the first seat on a tie. Swapping
  // it for ">=" would silently hand the tie to whichever seat is listed second.
  it("keeps the first-listed seat when two seats score identically", () => {
    const first = seat("Stalls", 10, 0);
    const second = seat("Stalls", 10, 0);
    expect(bestUpgradeCandidate([first, second])).toBe(first);
  });

  // Guards the single-element case, where there is nothing to compare against.
  it("returns the only seat when there is exactly one", () => {
    const onlySeat = seat("Stalls", 30, 3);
    expect(bestUpgradeCandidate([onlySeat])).toBe(onlySeat);
  });

  // Guards the empty case, where there is no seat to reach for.
  it("returns null when there are no seats to offer", () => {
    expect(bestUpgradeCandidate([])).toBeNull();
  });
});

describe("bestStandingSpot", () => {
  it("prefers the spot that is closer to the stage and more centered", () => {
    const close = spot("Rail", 8, 2);
    const far = spot("Back Wall", 50, 20);
    expect(bestStandingSpot([far, close])).toBe(close);
  });

  it("returns null when there are no spots to offer", () => {
    expect(bestStandingSpot([])).toBeNull();
  });

  // Guards the clamps inside the shared position scorer: a distance or offset far past
  // its useful range must bottom out at the same floor, not go negative and flip the
  // comparison. Without the clamp the far-but-central spot would win outright.
  it("clamps an extreme distance and an extreme offset to the same floor", () => {
    const farButCentered = spot("Way Back", 200, 0);
    const closeButWayOffCenter = spot("Side Wall", 0, 200);
    expect(bestStandingSpot([farButCentered, closeButWayOffCenter])).toBe(farButCentered);
  });
});
