import { describe, expect, it } from "vitest";
import {
  invoiceTotalCents,
  openContractPlan,
  openCustomer,
  renegotiatePlanRate,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

describe("invoiceTotalCents", () => {
  it("applies the customer's discount to the subtotal", () => {
    const plan = openContractPlan("standard", "Standard Wholesale", 0.1);
    const customer = openCustomer("cust-1", "Riverside Diner", plan);

    expect(invoiceTotalCents(customer, 10_000)).toBe(9_000);
  });

  // Guards the boundary where the discount itself needs rounding before it is subtracted -
  // an easy spot for a refactor to swap Math.round for Math.floor without anyone noticing.
  it("rounds the discount to the nearest cent", () => {
    const plan = openContractPlan("standard", "Standard Wholesale", 0.075);
    const customer = openCustomer("cust-1", "Riverside Diner", plan);

    // 999 * 0.075 = 74.925, which rounds to 75.
    expect(invoiceTotalCents(customer, 999)).toBe(924);
  });

  it("charges full price for a customer on a zero-discount plan", () => {
    const plan = openContractPlan("trial", "Trial", 0);
    const customer = openCustomer("cust-1", "Pop-up Stand", plan);

    expect(invoiceTotalCents(customer, 500)).toBe(500);
  });
});

describe("openCustomer", () => {
  // Guards against a customer's discount being copied from the plan at construction time
  // and left to drift - it must read the plan's rate live, not a snapshot taken at signup.
  it("starts a customer who joins after a renegotiation at the new rate, not the original one", () => {
    const plan = openContractPlan("standard", "Standard Wholesale", 0.1);
    const early = openCustomer("cust-1", "Riverside Diner", plan);
    renegotiatePlanRate([early], "standard", 0.2);

    const late = openCustomer("cust-2", "Oak Street Cafe", plan);

    expect(invoiceTotalCents(late, 1_000)).toBe(800);
  });
});

describe("renegotiatePlanRate", () => {
  // The core guarantee this drill exists to protect: two customers on the same plan must
  // never disagree about its rate, including the one that was not passed first.
  it("updates every customer on the plan, not just the first one in the list", () => {
    const plan = openContractPlan("founders", "Founders Co-op Rate", 0.12);
    const first = openCustomer("cust-a", "Riverside Diner", plan);
    const second = openCustomer("cust-b", "Oak Street Cafe", plan);

    renegotiatePlanRate([first, second], "founders", 0.18);

    expect(invoiceTotalCents(first, 1_000)).toBe(820);
    expect(invoiceTotalCents(second, 1_000)).toBe(820);
  });

  // Guards against a renegotiation on one plan leaking into another plan's customers.
  it("does not touch customers on a different plan", () => {
    const founders = openContractPlan("founders", "Founders Co-op Rate", 0.12);
    const standard = openContractPlan("standard", "Standard Wholesale", 0.05);
    const onFounders = openCustomer("cust-a", "Riverside Diner", founders);
    const onStandard = openCustomer("cust-b", "Oak Street Cafe", standard);

    renegotiatePlanRate([onFounders, onStandard], "founders", 0.2);

    expect(invoiceTotalCents(onStandard, 1_000)).toBe(950);
  });

  // Guards the lookup-miss path: no customer in the roster belongs to the given plan id.
  it("does nothing when no customer in the roster is on the given plan", () => {
    const plan = openContractPlan("standard", "Standard Wholesale", 0.1);
    const customer = openCustomer("cust-1", "Riverside Diner", plan);

    renegotiatePlanRate([customer], "nonexistent-plan", 0.5);

    expect(invoiceTotalCents(customer, 1_000)).toBe(900);
  });

  // Guards the empty-roster case, where there is no first customer to find a plan through.
  it("does nothing when the roster is empty", () => {
    expect(() => renegotiatePlanRate([], "standard", 0.5)).not.toThrow();
  });
});
