import { describe, expect, it } from "vitest";
import {
  buildDailyBakePlan,
  type BakeDate,
  type BakeItem,
  type StandingOrder,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

const wednesday: BakeDate = { iso: "2026-03-11", dayOfWeek: "Wed" };

const sourdough: BakeItem = {
  sku: "SD-01",
  name: "Sourdough Loaf",
  aisle: "Bread Wall",
  batchSize: 6,
  wastageAllowance: 0.1,
};

const croissant: BakeItem = {
  sku: "CR-01",
  name: "Croissant",
  aisle: "Pastry Case",
  batchSize: 12,
  wastageAllowance: 0.2,
};

function orderFor(
  sku: string,
  days: StandingOrder["daysOfWeek"],
  units: number,
): StandingOrder {
  return { sku, customer: "The Corner Cafe", daysOfWeek: days, units };
}

describe("buildDailyBakePlan", () => {
  it("adds the wastage allowance, then rounds up to a full batch", () => {
    // 10 units + ceil(10 * 0.1) = 11 buffer units, rounded up to the next multiple of 6.
    const orders = [orderFor("SD-01", ["Wed"], 10)];
    const plan = buildDailyBakePlan(wednesday, [sourdough], orders);

    expect(plan.lines).toEqual([
      {
        sku: "SD-01",
        name: "Sourdough Loaf",
        shelfTag: "BRE-SOURDOUGH LOAF",
        bakeUnits: 12,
        batches: 2,
      },
    ]);
  });

  // Guards against a rounding fix that swaps ceil for round or floor anywhere in the chain.
  it("rounds the wastage allowance up, never down, even for a fraction under one", () => {
    // 7 units * 0.1 = 0.7, which must become 1 buffer unit, not 0.
    const orders = [orderFor("SD-01", ["Wed"], 7)];
    const plan = buildDailyBakePlan(wednesday, [sourdough], orders);

    // 7 + 1 = 8, rounded up to 12.
    expect(plan.lines[0]?.bakeUnits).toBe(12);
  });

  // Guards the boundary where the needed quantity already lands exactly on a batch.
  it("does not round up past an already-exact batch multiple", () => {
    // 20 units * 0.2 = 4 buffer units exactly; 20 + 4 = 24, already a multiple of 12.
    const orders = [orderFor("CR-01", ["Wed"], 20)];
    const plan = buildDailyBakePlan(wednesday, [croissant], orders);

    expect(plan.lines[0]?.bakeUnits).toBe(24);
    expect(plan.lines[0]?.batches).toBe(2);
  });

  // Guards a filter that stops checking daysOfWeek and counts every standing order instead.
  it("ignores a standing order on a day it does not name", () => {
    const orders = [orderFor("SD-01", ["Mon", "Thu"], 30)];
    const plan = buildDailyBakePlan(wednesday, [sourdough], orders);

    expect(plan.lines[0]?.bakeUnits).toBe(0);
  });

  // Guards a grouping step that overwrites same-sku orders instead of summing them.
  it("sums two standing orders for the same item on the same day", () => {
    const orders = [orderFor("SD-01", ["Wed"], 5), orderFor("SD-01", ["Wed", "Fri"], 4)];
    const plan = buildDailyBakePlan(wednesday, [sourdough], orders);

    // 5 + 4 = 9, + ceil(0.9) = 1 buffer unit = 10, rounded up to 12.
    expect(plan.lines[0]?.bakeUnits).toBe(12);
  });

  // Guards the shelf-tag format: a 3-letter aisle code, a dash, then the name in caps.
  it("builds the shelf tag from the first three letters of the aisle and the item name", () => {
    const orders = [orderFor("CR-01", ["Wed"], 1)];
    const plan = buildDailyBakePlan(wednesday, [croissant], orders);

    expect(plan.lines[0]?.shelfTag).toBe("PAS-CROISSANT");
  });

  // Guards against merging the per-item batches into a single division at the end, which
  // would drift from the sum of each item's own rounded-up batch count.
  it("totals ovenBatchesUsed as the sum of each line's own batches, not one plan-wide division", () => {
    const orders = [orderFor("SD-01", ["Wed"], 1), orderFor("CR-01", ["Wed"], 1)];
    const plan = buildDailyBakePlan(wednesday, [sourdough, croissant], orders);

    // 1 + 1 buffer = 2, rounded up to 6 -> 1 batch; 1 + 1 buffer = 2, rounded up to 12 -> 1 batch.
    expect(plan.lines[0]?.batches).toBe(1);
    expect(plan.lines[1]?.batches).toBe(1);
    expect(plan.ovenBatchesUsed).toBe(2);
  });

  // Guards the empty-catalogue case, where there is no first line to reach for.
  it("returns an empty plan for a day with nothing in the catalogue", () => {
    const plan = buildDailyBakePlan(wednesday, [], []);

    expect(plan).toEqual({ date: "2026-03-11", lines: [], ovenBatchesUsed: 0 });
  });

  // Guards an item with no standing orders at all disappearing from the sheet instead of
  // showing up at zero - the baker still needs to see it was considered.
  it("still lists an item with no standing orders today, at zero", () => {
    const plan = buildDailyBakePlan(wednesday, [sourdough], []);

    expect(plan.lines).toEqual([
      {
        sku: "SD-01",
        name: "Sourdough Loaf",
        shelfTag: "BRE-SOURDOUGH LOAF",
        bakeUnits: 0,
        batches: 0,
      },
    ]);
  });
});
