import { describe, expect, it } from "vitest";
import { PracticeRoom, renderPracticeSchedule } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of folding the empty PracticeRoom subclass into its
 * superclass. Do not edit this file: if a refactoring seems to require changing a test,
 * either the refactoring changed behaviour or the exercise is wrong.
 *
 * Collapse Hierarchy should be invisible from out here - every test below passes
 * unchanged whether PracticeRoom is an empty subclass of Room or a single class on its
 * own. That invisibility is the whole point: it is what makes it safe to delete the split.
 */

const studioA = new PracticeRoom({
  name: "Studio A",
  capacity: 2,
  hourlyRateCents: 1500,
});
const studioB = new PracticeRoom({
  name: "Studio B",
  capacity: 4,
  hourlyRateCents: 2200,
});

describe("PracticeRoom", () => {
  // Guards the basic accessors surviving the merge unchanged.
  it("reports its own name and capacity", () => {
    expect(studioA.name()).toBe("Studio A");
    expect(studioA.capacity()).toBe(2);
  });

  // Guards the booking-cost arithmetic, the one piece of real behaviour in this class.
  it("prices a booking at the hourly rate times the hours booked", () => {
    expect(studioA.bookingCostCents(2)).toBe(3000);
  });

  // Guards rounding on a rate that does not divide evenly across a fractional booking.
  it("rounds a fractional booking to the nearest cent", () => {
    const oddRate = new PracticeRoom({
      name: "Studio C",
      capacity: 1,
      hourlyRateCents: 1499,
    });
    expect(oddRate.bookingCostCents(1.5)).toBe(2249);
  });

  // Guards the describe() format, including the capacity note, unchanged.
  it("describes itself with its seating capacity", () => {
    expect(studioA.describe()).toBe("Studio A (seats 2)");
  });
});

describe("renderPracticeSchedule", () => {
  // Guards the empty case, where there is no first booking to reach for.
  it("says so plainly when nothing is booked", () => {
    expect(renderPracticeSchedule([])).toEqual(["No practice rooms booked today."]);
  });

  // Guards a single booking's line and total, the smallest non-empty case.
  it("renders a single booking and its total", () => {
    const lines = renderPracticeSchedule([{ room: studioA, hours: 2 }]);
    expect(lines).toEqual(["Studio A (seats 2) - 2h - $30.00", "Total: $30.00"]);
  });

  // Guards bookings staying in the order they were made, not sorted by room or cost -
  // a plausible but wrong "tidying" once the two room classes stop existing separately.
  it("lists bookings in the order given, not sorted", () => {
    const lines = renderPracticeSchedule([
      { room: studioB, hours: 1 },
      { room: studioA, hours: 1 },
    ]);
    expect(lines[0]).toContain("Studio B");
    expect(lines[1]).toContain("Studio A");
  });

  // Guards the total summing each booking's own cost rather than assuming one rate for
  // every room in the schedule.
  it("totals bookings across different rooms at their own rates", () => {
    const lines = renderPracticeSchedule([
      { room: studioA, hours: 2 },
      { room: studioB, hours: 1 },
    ]);
    expect(lines).toContain(`Total: $52.00`);
  });

  // Guards the same room being booked twice in one day without the second booking being
  // dropped or merged into the first.
  it("keeps two separate bookings of the same room as two lines", () => {
    const lines = renderPracticeSchedule([
      { room: studioA, hours: 1 },
      { room: studioA, hours: 3 },
    ]);
    expect(lines).toEqual([
      "Studio A (seats 2) - 1h - $15.00",
      "Studio A (seats 2) - 3h - $45.00",
      "Total: $60.00",
    ]);
  });

  // Guards against "tidying up" a long room name into a truncation while the hierarchy
  // collapses. A long name is not cut.
  it("does not truncate a long room name", () => {
    const bigName = new PracticeRoom({
      name: "The Recital Hall Annex Practice Suite",
      capacity: 8,
      hourlyRateCents: 4000,
    });
    const lines = renderPracticeSchedule([{ room: bigName, hours: 1 }]);
    expect(lines[0]).toBe(
      "The Recital Hall Annex Practice Suite (seats 8) - 1h - $40.00",
    );
  });
});
