import { describe, expect, it } from "vitest";
import {
  openLoan,
  overdueFineCents,
  renderLoanStatus,
  renewLoan,
  returnLoan,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * One test per behaviour a plausible refactoring of this file could silently change - not
 * one per line. Each test names the move it is guarding against.
 */

describe("openLoan", () => {
  // Guards against the due date drifting off the checkout date once it moves behind a
  // constructor or a factory function.
  it("computes a due date twenty-one days after checkout", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    expect(loan.dueOn).toBe("2026-08-22");
    expect(loan.returnedOn).toBeNull();
    expect(loan.renewalCount).toBe(0);
  });
});

describe("renewLoan", () => {
  // Guards against anchoring the new due date to the *old* due date instead of to the day
  // the renewal happens - an easy swap once both dates are close by inside one function.
  it("anchors the new due date to today, not to the old due date", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");

    const outcome = renewLoan(loan, "2026-08-20");

    expect(outcome).toEqual({ renewed: true });
    expect(loan.dueOn).toBe("2026-09-10");
    expect(loan.renewalCount).toBe(1);
  });

  // Guards the boundary of the renewal limit, and that a refusal leaves state untouched -
  // the usual casualty of folding a guard clause into the mutation it is meant to prevent.
  it("refuses a third renewal, leaving the due date and count from the second", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    renewLoan(loan, "2026-08-20");
    renewLoan(loan, "2026-09-05");

    const outcome = renewLoan(loan, "2026-09-20");

    expect(outcome.renewed).toBe(false);
    expect(outcome.reason).toContain("no renewals left");
    expect(loan.dueOn).toBe("2026-09-26");
    expect(loan.renewalCount).toBe(2);
  });

  // Guards against a renewal silently reviving a loan that was already handed back.
  it("refuses to renew a loan that has already been returned", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    returnLoan(loan, "2026-08-15");

    const outcome = renewLoan(loan, "2026-08-16");

    expect(outcome.renewed).toBe(false);
    expect(outcome.reason).toContain("already returned");
    expect(loan.renewalCount).toBe(0);
  });
});

describe("returnLoan", () => {
  it("records the date the item came back", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");

    returnLoan(loan, "2026-08-15");

    expect(loan.returnedOn).toBe("2026-08-15");
  });
});

describe("renderLoanStatus", () => {
  // Guards the boundary: due today is not yet overdue. An off-by-one here (`>=` for `>`)
  // is the classic casualty of moving this comparison during a refactor.
  it("does not call a loan overdue on the day it is due", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    expect(renderLoanStatus(loan, "2026-08-22")).toBe("On loan until 2026-08-22");
  });

  it("counts the days once a loan is overdue", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    expect(renderLoanStatus(loan, "2026-08-25")).toBe("3 day(s) overdue");
  });

  // Guards against the overdue check running first and shadowing a loan that was, in
  // fact, returned - order matters once both checks read the same two fields.
  it("reports the return date once a loan is returned, however late 'today' is asked", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    returnLoan(loan, "2026-08-25");
    expect(renderLoanStatus(loan, "2026-12-01")).toBe("Returned on 2026-08-25");
  });
});

describe("overdueFineCents", () => {
  // Guards against using `today` as the fine's endpoint once a loan is already returned -
  // the two dates are equally in scope and only one of them is correct here.
  it("is zero for a loan returned on time, even when asked about much later", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    returnLoan(loan, "2026-08-20");
    expect(overdueFineCents(loan, "2026-12-01")).toBe(0);
  });

  it("accrues per day late for an unreturned loan, and caps at the maximum when very late", () => {
    const loan = openLoan("MBR-118", "BK-204", "2026-08-01");
    expect(overdueFineCents(loan, "2026-09-01")).toBe(200);
    expect(overdueFineCents(loan, "2026-12-01")).toBe(1000);
  });
});
