import { describe, expect, it } from "vitest";
import { renderSplitReport, type SplitSheet } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * Inline Variable is *usually* safe, which is exactly why the few ways it can bite are
 * worth pinning. Each test below names the move it guards against.
 */

const halfMarathon: SplitSheet = {
  runner: "Ana Ferreira",
  club: "Silverbrook AC",
  splits: [
    { label: "5K", km: 5, elapsedSeconds: 1024 },
    { label: "10K", km: 10, elapsedSeconds: 2071 },
    { label: "15K", km: 15, elapsedSeconds: 3140 },
    { label: "Finish", km: 21.0975, elapsedSeconds: 4470 },
  ],
};

describe("renderSplitReport", () => {
  it("renders a leg per mat, then the summary", () => {
    expect(renderSplitReport(halfMarathon)).toBe(
      [
        "Ana Ferreira - Silverbrook AC",
        "5K         17:04   +17:04 3:25/km",
        "10K        34:31   +17:27 3:29/km",
        "15K        52:20   +17:49 3:34/km",
        "Finish   1:14:30   +22:10 3:38/km",
        "Total: 1:14:30 over 21.1 km",
        "Fastest leg: 5K at 3:25/km",
        "Even pacing: yes",
      ].join("\n"),
    );
  });

  // Guards the `?? 0` that only matters for the first mat, where there is no previous
  // split to read. Inline it wrongly and the first leg is NaN or the whole race long.
  it("measures the first leg from the start line, not from the mat before it", () => {
    const solo: SplitSheet = {
      runner: "Bruno Costa",
      club: "Riverside Runners",
      splits: [{ label: "Finish", km: 10, elapsedSeconds: 2400 }],
    };

    expect(renderSplitReport(solo)).toBe(
      [
        "Bruno Costa - Riverside Runners",
        "Finish     40:00   +40:00 4:00/km",
        "Total: 40:00 over 10.0 km",
        "Fastest leg: Finish at 4:00/km",
        "Even pacing: yes",
      ].join("\n"),
    );
  });

  // Guards against swapping the two duration columns. Both are `formatDuration` calls;
  // once the variables that told them apart are gone, only their order does.
  it("shows elapsed time first and the leg's own duration second", () => {
    const row = renderSplitReport(halfMarathon).split("\n")[2] ?? "";
    expect(row).toContain("34:31");
    expect(row.indexOf("34:31")).toBeLessThan(row.indexOf("+17:27"));
  });

  // Guards the empty case: no legs means no summary, not a summary full of zeroes.
  it("prints the name line alone for a sheet with no mats crossed", () => {
    const nothing: SplitSheet = {
      runner: "Ines Rocha",
      club: "Coldwater Harriers",
      splits: [],
    };

    expect(renderSplitReport(nothing)).toBe("Ines Rocha - Coldwater Harriers");
  });

  // Guards against relaxing `<` to `<=` while inlining the pace comparison - the tie
  // would then be won by the last leg instead of the first.
  it("awards the fastest leg to the earliest of equally fast legs", () => {
    const tied: SplitSheet = {
      runner: "Tie Test",
      club: "Silverbrook AC",
      splits: [
        { label: "Half", km: 5, elapsedSeconds: 1200 },
        { label: "Finish", km: 10, elapsedSeconds: 2400 },
      ],
    };

    expect(renderSplitReport(tied)).toContain("Fastest leg: Half at 4:00/km");
  });

  // Guards the h:mm:ss boundary, where one second decides whether the hour is printed.
  it("drops the hour below 3600 seconds and prints it at 3600", () => {
    const crossing: SplitSheet = {
      runner: "Hour Boundary",
      club: "Silverbrook AC",
      splits: [
        { label: "10K", km: 10, elapsedSeconds: 3599 },
        { label: "Finish", km: 20, elapsedSeconds: 7200 },
      ],
    };

    const lines = renderSplitReport(crossing).split("\n");
    expect(lines[1]).toBe("10K        59:59   +59:59 6:00/km");
    expect(lines[2]).toBe("Finish   2:00:00 +1:00:01 6:00/km");
  });

  // Guards the rounding in formatPace. A half second per kilometre rounds up; a switch
  // to Math.floor while tidying the expression would show 3:25 here.
  it("rounds a pace of x.5 seconds per kilometre up", () => {
    const half: SplitSheet = {
      runner: "Rounding",
      club: "Silverbrook AC",
      splits: [{ label: "2K", km: 2, elapsedSeconds: 411 }],
    };

    expect(renderSplitReport(half)).toContain("Fastest leg: 2K at 3:26/km");
  });

  // Guards the even-pacing tolerance, which is inclusive. Exactly 15 s/km off the
  // average still counts as even; 16 does not.
  it("counts a leg exactly at the tolerance as evenly paced", () => {
    const onTheLine: SplitSheet = {
      runner: "Tolerance",
      club: "Silverbrook AC",
      splits: [
        { label: "First", km: 5, elapsedSeconds: 1425 },
        { label: "Second", km: 10, elapsedSeconds: 3000 },
      ],
    };
    const overTheLine: SplitSheet = {
      ...onTheLine,
      splits: [
        { label: "First", km: 5, elapsedSeconds: 1420 },
        { label: "Second", km: 10, elapsedSeconds: 3000 },
      ],
    };

    expect(renderSplitReport(onTheLine)).toContain("Even pacing: yes");
    expect(renderSplitReport(overTheLine)).toContain("Even pacing: no");
  });

  // Guards against "tidying" the label column into a truncation. A long mat name pushes
  // the row out; it is not cut.
  it("lets a mat name wider than its column push the row out", () => {
    const wide: SplitSheet = {
      runner: "Maria Fernanda Albuquerque Santos",
      club: "Silverbrook AC",
      splits: [
        { label: "Beacon Hill gate", km: 4, elapsedSeconds: 1000 },
        { label: "Finish", km: 8, elapsedSeconds: 2000 },
      ],
    };

    expect(renderSplitReport(wide)).toContain(
      "Beacon Hill gate   16:40   +16:40 4:10/km",
    );
  });
});
