import { describe, expect, it } from "vitest";
import {
  importTickets,
  issueCompTicket,
  sellPremiumTicket,
  sellStandardTicket,
  type TicketRow,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Replace
 * Constructor with Factory Function is that `new Ticket(type, ...)` disappears - the
 * challenge builds every ticket by calling the constructor directly and lets it throw on
 * bad input, the solution builds tickets through named factories and a private
 * constructor nothing outside the class can call. So this suite never constructs a
 * `Ticket` directly - it only calls the four callers, whose own signatures do not change,
 * and reads back what they return.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

describe("sellStandardTicket", () => {
  it("prices a standard ticket at face value, with no perks", () => {
    const ticket = sellStandardTicket(3000);
    expect(ticket).toMatchObject({ type: "standard", priceCents: 3000, perks: [] });
  });
});

describe("sellPremiumTicket", () => {
  it("marks a premium ticket up by half, with lounge access and priority entry", () => {
    const ticket = sellPremiumTicket(4000);
    expect(ticket).toMatchObject({
      type: "premium",
      priceCents: 6000,
      perks: ["Lounge access", "Priority entry"],
    });
  });

  // Guards a rounding boundary a naive refactor could flip from round-half-up to truncate.
  it("rounds a markup that lands on a half-cent to the nearest cent", () => {
    const ticket = sellPremiumTicket(333);
    expect(ticket.priceCents).toBe(500);
  });
});

describe("issueCompTicket", () => {
  it("issues a free ticket with pickup instructions when a staff member authorizes it", () => {
    const ticket = issueCompTicket(5000, "J. Alvarez");
    expect(ticket).toMatchObject({
      type: "comp",
      priceCents: 0,
      perks: ["Will call pickup"],
      authorizedBy: "J. Alvarez",
    });
  });

  // Guards against "fail without throwing" regressing into a thrown exception a caller
  // that only checks for null would no longer catch.
  it("refuses a comp ticket with no authorizing staff member, without throwing", () => {
    expect(() => issueCompTicket(5000, null)).not.toThrow();
    expect(issueCompTicket(5000, null)).toBeNull();
  });

  // Guards the boundary between "missing" and "blank" - a check for null alone would let
  // an empty string slip through as if it named someone.
  it("treats an empty authorizing name the same as no name at all", () => {
    expect(issueCompTicket(5000, "")).toBeNull();
  });
});

describe("importTickets", () => {
  it("builds a ticket for every valid row and skips the rest", () => {
    const rows: TicketRow[] = [
      { type: "standard", faceValueCents: 3000, authorizedBy: null },
      { type: "comp", faceValueCents: 5000, authorizedBy: null },
      { type: "premium", faceValueCents: 4000, authorizedBy: null },
      { type: "comp", faceValueCents: 5000, authorizedBy: "J. Alvarez" },
    ];

    const result = importTickets(rows);

    expect(result.skipped).toBe(1);
    expect(result.issued).toHaveLength(3);
  });

  // Guards against a refactor that filters or sorts while assembling `issued`, instead of
  // preserving each row's place in the file.
  it("keeps issued tickets in the same order as their rows", () => {
    const rows: TicketRow[] = [
      { type: "standard", faceValueCents: 1000, authorizedBy: null },
      { type: "comp", faceValueCents: 5000, authorizedBy: null },
      { type: "premium", faceValueCents: 2000, authorizedBy: null },
    ];

    const result = importTickets(rows);

    expect(result.issued.map((ticket) => ticket.type)).toEqual(["standard", "premium"]);
  });

  it("returns nothing issued and nothing skipped for an empty batch", () => {
    expect(importTickets([])).toEqual({ issued: [], skipped: 0 });
  });

  it("skips every row when every row is an unauthorized comp ticket", () => {
    const rows: TicketRow[] = [
      { type: "comp", faceValueCents: 5000, authorizedBy: null },
      { type: "comp", faceValueCents: 6000, authorizedBy: "" },
    ];

    expect(importTickets(rows)).toEqual({ issued: [], skipped: 2 });
  });
});
