import { describe, expect, it } from "vitest";
import {
  closeRegistration,
  decideEntry,
  isRegistrationOpen,
  lateFeeCents,
  raiseDues,
  spotsRemaining,
  startSeason,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * The settings are module state, not a parameter, so each test opens by calling
 * `startSeason` with the fixture it needs - that is also a real operation (the committee
 * setting dues, the rate, and the cap for the year), not a test-only backdoor.
 */

describe("decideEntry", () => {
  // Guards against an accept path that forgets to record the new member.
  it("accepts an applicant when there is room, and counts them against capacity", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 2 });

    expect(decideEntry({ name: "Ana Ferreira" })).toEqual({ accepted: true });
    expect(spotsRemaining()).toBe(1);
  });

  // Guards the boundary: the club is full at zero spots, not at minus one.
  it("rejects an applicant with a reason once the club is full", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 1 });
    decideEntry({ name: "Ana Ferreira" });

    expect(decideEntry({ name: "Bruno Costa" })).toEqual({
      accepted: false,
      reason: "the club is full for Bruno Costa",
    });
  });

  // Guards against a rejection path that still mutates state on its way out - a real
  // risk once the mutation is hidden behind a name instead of written at the call site.
  it("rejects entry while registration is closed, without touching the member count", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 5 });
    closeRegistration();

    expect(decideEntry({ name: "Celia Nunes" })).toEqual({
      accepted: false,
      reason: "registration is closed for Celia Nunes",
    });
    expect(spotsRemaining()).toBe(5);
  });
});

describe("startSeason", () => {
  // Guards against collapsing the five-field reset into one assignment and dropping one
  // of them - memberCount and registrationOpen are the two easiest to forget.
  it("resets the member count and reopens registration for the new season", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 2 });
    decideEntry({ name: "Ana Ferreira" });
    closeRegistration();

    startSeason({ duesCents: 4700, lateFeeRatePercent: 6, capacity: 3 });

    expect(spotsRemaining()).toBe(3);
    expect(isRegistrationOpen()).toBe(true);
  });
});

describe("closeRegistration", () => {
  // Guards against a setter reaching further than its name promises.
  it("closes registration without changing capacity or the member count", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 5 });
    decideEntry({ name: "Ana Ferreira" });

    closeRegistration();

    expect(isRegistrationOpen()).toBe(false);
    expect(spotsRemaining()).toBe(4);
  });
});

describe("lateFeeCents", () => {
  // Guards the rounding boundary - dues that do not divide evenly by the rate.
  it("rounds the fee to the nearest cent", () => {
    startSeason({ duesCents: 4567, lateFeeRatePercent: 5, capacity: 10 });

    expect(lateFeeCents()).toBe(228);
  });

  // Guards against the fee being cached at season-start instead of derived live - the
  // exact bug a hasty "just store it in settings" fix would introduce.
  it("reflects a dues increase on the very next calculation", () => {
    startSeason({ duesCents: 4500, lateFeeRatePercent: 5, capacity: 10 });
    const before = lateFeeCents();

    raiseDues(500);

    expect(before).toBe(225);
    expect(lateFeeCents()).toBe(250);
  });
});
