import { describe, expect, it } from "vitest";
import { fareCents, newTrip, routeSummary, tripLogRow } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of renaming Trip's fields. Do not edit this file: if a
 * refactoring seems to require changing a test, either the refactoring changed behaviour
 * or the exercise is wrong.
 *
 * Trip is built only through newTrip and read only through fareCents, routeSummary, and
 * tripLogRow - never by spelling a field name in an object literal here - because the
 * field names themselves are what this drill renames, and this file has to pass unchanged
 * against both the challenge and the solution.
 *
 * One test per behaviour a plausible Rename Field could silently change, not one per
 * station.
 */

const stationNames = new Map([
  ["DOCK-ELM", "Elm Street"],
  ["DOCK-PINE", "Pine & 5th"],
]);

describe("fareCents", () => {
  // Guards against the renamed duration field being read from the wrong position, or the
  // fare being computed against a station id instead.
  it("charges the flat per-minute rate for the trip's full duration", () => {
    expect(fareCents(newTrip(18, "DOCK-ELM", "DOCK-PINE"), 15)).toBe(270);
  });

  // Boundary: a zero-minute trip still has two real stations and must not throw.
  it("returns zero for a zero-minute trip", () => {
    expect(fareCents(newTrip(0, "DOCK-ELM", "DOCK-ELM"), 15)).toBe(0);
  });
});

describe("routeSummary", () => {
  // Guards against the start and end station fields being swapped during the rename.
  it("names both stations, start before end, when both are in the directory", () => {
    const trip = newTrip(12, "DOCK-ELM", "DOCK-PINE");
    expect(routeSummary(trip, stationNames)).toBe("Elm Street to Pine & 5th");
  });

  // Boundary: a station retired from the directory since the trip was taken. A rename
  // that dropped the `?? ` fallback would throw instead of falling back to the raw id.
  it("falls back to the raw station id when a station is missing from the directory", () => {
    const trip = newTrip(12, "DOCK-ELM", "DOCK-GONE");
    expect(routeSummary(trip, stationNames)).toBe("Elm Street to DOCK-GONE");
  });

  // Boundary: start and end are the same station on a round trip - a swapped-field bug
  // would be invisible here, so this alone isn't sufficient, but it must still pass.
  it("handles a round trip that starts and ends at the same station", () => {
    const trip = newTrip(9, "DOCK-ELM", "DOCK-ELM");
    expect(routeSummary(trip, stationNames)).toBe("Elm Street to Elm Street");
  });
});

describe("tripLogRow", () => {
  // Guards against the warehouse's published keys drifting out of sync with which Trip
  // field feeds which key - a mix-up here corrupts data an external job already trusts.
  it("publishes duration, start, and end under the warehouse's existing dt/st/en keys", () => {
    const row = tripLogRow(newTrip(18, "DOCK-ELM", "DOCK-PINE"));
    expect(row.dt).toBe(18);
    expect(row.st).toBe("DOCK-ELM");
    expect(row.en).toBe("DOCK-PINE");
  });

  // The anchor test: the whole point of this drill is that Trip's field names change and
  // TripLogRow's do not. A rename that bled across that boundary - renaming the published
  // row's keys to match Trip's - would fail this test, not any type check, because
  // TripLogRow is typed independently of Trip and the compiler cannot see the external
  // consumer that depends on these exact keys.
  it("never publishes Trip's own field names, only the warehouse's dt/st/en", () => {
    const row = tripLogRow(newTrip(5, "DOCK-PINE", "DOCK-PINE"));
    expect(Object.keys(row).sort()).toEqual(["dt", "en", "st"]);
  });
});
