import { describe, expect, it } from "vitest";
import { searchTitles, type CatalogueEntry } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after the algorithm is swapped. Do not edit this file: if a rewrite seems to
 * require changing a test, either the rewrite changed behaviour or the exercise is wrong.
 *
 * Substitute Algorithm is not provably behaviour-preserving by reading the two versions
 * side by side, the way Extract Function or Rename Variable are - the old scan and the new
 * one share no structure at all. This suite is the only thing standing between "refactor"
 * and "silent rewrite." If a test here is wrong or missing, nothing else in this exercise
 * will tell you that the new algorithm disagrees with the old one.
 *
 * Two of the tests below (empty query, and the tie-break order) pin behaviour the old scan
 * has by accident - nobody designed it, it just fell out of how the loops were written.
 * The point of the exercise is noticing that before you replace the loops, not after.
 */

const library: CatalogueEntry[] = [
  { id: "b1", title: "Garden of Forking Paths", author: "J. Ilves" },
  { id: "b2", title: "Gardening for Beginners", author: "P. Duarte" },
  { id: "b3", title: "The Silent Garden", author: "Rosa Kwan" },
  { id: "b4", title: "Arthurian Legends", author: "Guy Fenwick" },
  { id: "b5", title: "Bartholomew's Diary", author: "N. Okafor" },
  { id: "b6", title: "Midnight Silence", author: "Ana Bardot" },
];

function ids(entries: readonly CatalogueEntry[]): string[] {
  return entries.map((entry) => entry.id);
}

describe("searchTitles", () => {
  it("ranks matches by how early the matching word falls in the title", () => {
    // Guards against a rank derived from anything other than word position - character
    // offset, title length, alphabetical order of the title itself.
    expect(ids(searchTitles(library, "gard"))).toEqual(["b1", "b2", "b3"]);
  });

  it("matches case-insensitively, in both the query and the title", () => {
    // Guards against folding case on only one side of the comparison.
    expect(ids(searchTitles(library, "GaRd"))).toEqual(["b1", "b2", "b3"]);
  });

  it("matches a query that prefixes a word, not one that merely appears inside it", () => {
    // The central trap: "arth" is a *substring* of "Bartholomew's" (b-ART-Holomew's) but
    // is not a prefix of any word in that title, so it must not match. A rewrite around
    // String.includes instead of a word-by-word prefix check passes every other test in
    // this file and fails exactly this one.
    const result = searchTitles(library, "arth");
    expect(ids(result)).toEqual(["b4"]);
  });

  it("keeps entries tied on the same rank in catalogue order, not alphabetical order", () => {
    // Guards sort stability specifically. "Owl Country" sorts after "Otter Lake"
    // alphabetically but is entered first here - if the tie-break silently became
    // alphabetical, or the sort stopped being stable, this is the test that notices.
    const tied: CatalogueEntry[] = [
      { id: "owl", title: "Owl Country", author: "R. Stace" },
      { id: "otter", title: "Otter Lake", author: "M. Vance" },
    ];
    expect(ids(searchTitles(tied, "o"))).toEqual(["owl", "otter"]);
  });

  it("returns the whole catalogue, in catalogue order, for an empty query", () => {
    // The other accident: every word "starts with" the empty string, so an empty query
    // matches everything rather than nothing. A defensive `if (!query) return []` added
    // during the rewrite would be a plausible-looking behaviour change, not a safe one.
    expect(ids(searchTitles(library, ""))).toEqual(["b1", "b2", "b3", "b4", "b5", "b6"]);
  });

  it("returns nothing when no title has a word starting with the query", () => {
    // Guards the plain miss case against an algorithm that defaults to "match everything"
    // or throws instead of returning an empty list.
    expect(searchTitles(library, "zzz")).toEqual([]);
  });

  it("searches titles only - a query that matches an author finds nothing", () => {
    // "fenw" is a prefix of author Guy Fenwick's surname but appears in no title. Guards
    // against a rewrite that broadens the scan to every field on the entry.
    expect(searchTitles(library, "fenw")).toEqual([]);
  });

  it("matches a query the same length as the whole word it matches", () => {
    // Boundary: the query is not strictly shorter than the word, only equal to it. An
    // off-by-one in a hand-rolled comparison loop usually shows up right at this edge.
    expect(ids(searchTitles(library, "diary"))).toEqual(["b5"]);
  });

  it("matches nothing when the query is longer than every word in the catalogue", () => {
    // The other side of the same boundary: comparing past the end of the shorter string.
    // A loop that reads an out-of-range index instead of stopping there can return a false
    // match, or a wrong one, instead of the empty list this asserts.
    expect(searchTitles(library, "supercalifragilistic")).toEqual([]);
  });

  it("returns nothing for an empty catalogue, whatever the query", () => {
    // The single- and zero-element inputs a plausible extraction, sort, or lookup swap
    // could each mishandle in a different way.
    expect(searchTitles([], "garden")).toEqual([]);
  });
});
