import { describe, expect, it } from "vitest";
import {
  bookTrip,
  correctRiderPhone,
  findRider,
  openDirectory,
  registerRider,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of giving Rider a single, shared owner instead of copying
 * it onto every trip. Do not edit this file: if a refactoring seems to require changing a
 * test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible refactoring of this file could silently
 * change - not one per function. Each test names the move it is guarding against.
 *
 * Note what is deliberately absent: no test registers a rider, books a trip, corrects the
 * rider's phone, and then re-reads that *same, already-booked* trip's phone number. That
 * exact combination is where the challenge's copied-per-trip details and the solution's
 * shared rider record disagree - see WALKTHROUGH.md. A test that asserted a value there
 * could only pass against one of src/ or the solution, never both, so it cannot live in a
 * suite that has to grade both. The proof that the solution gets it right lives in
 * `tests-fixed/`, which runs against solutions only.
 */

describe("bookTrip", () => {
  it("books a trip carrying the rider's registered contact details", () => {
    const directory = openDirectory();
    registerRider(directory, {
      id: "RIDER-1",
      name: "Priya Shah",
      phone: "555-0100",
      email: "priya@example.com",
    });

    const trip = bookTrip(directory, "TRIP-1", {
      riderId: "RIDER-1",
      fromStationId: "STATION-ELM",
      toStationId: "STATION-PINE",
    });

    expect(trip.rider.name).toBe("Priya Shah");
    expect(trip.rider.phone).toBe("555-0100");
  });

  // Sentinel: booking for a rider who was never registered must fail loudly, not silently
  // create a half-formed trip.
  it("throws when booking a trip for a rider who is not registered", () => {
    const directory = openDirectory();

    expect(() =>
      bookTrip(directory, "TRIP-1", {
        riderId: "RIDER-GHOST",
        fromStationId: "STATION-ELM",
        toStationId: "STATION-PINE",
      }),
    ).toThrow(/RIDER-GHOST/u);
  });

  // Ties: two trips booked by the same rider both start from the same registered details -
  // duplication at booking time is expected; the question this drill answers is what
  // happens to it afterwards.
  it("gives two trips booked by the same rider the same starting contact details", () => {
    const directory = openDirectory();
    registerRider(directory, {
      id: "RIDER-1",
      name: "Priya Shah",
      phone: "555-0100",
      email: "priya@example.com",
    });

    const first = bookTrip(directory, "TRIP-1", {
      riderId: "RIDER-1",
      fromStationId: "STATION-ELM",
      toStationId: "STATION-PINE",
    });
    const second = bookTrip(directory, "TRIP-2", {
      riderId: "RIDER-1",
      fromStationId: "STATION-PINE",
      toStationId: "STATION-OAK",
    });

    expect(first.rider.phone).toBe("555-0100");
    expect(second.rider.phone).toBe("555-0100");
  });
});

describe("correctRiderPhone", () => {
  it("updates the rider's own record in the directory", () => {
    const directory = openDirectory();
    registerRider(directory, {
      id: "RIDER-1",
      name: "Priya Shah",
      phone: "555-0100",
      email: "priya@example.com",
    });

    correctRiderPhone(directory, "RIDER-1", "555-0199");

    expect(findRider(directory, "RIDER-1")?.phone).toBe("555-0199");
  });

  // Guards the forward direction: a trip booked after a correction must reflect the
  // corrected number, not whatever the rider's phone happened to be earlier.
  it("is reflected on a trip booked after the correction", () => {
    const directory = openDirectory();
    registerRider(directory, {
      id: "RIDER-1",
      name: "Priya Shah",
      phone: "555-0100",
      email: "priya@example.com",
    });

    correctRiderPhone(directory, "RIDER-1", "555-0199");
    const trip = bookTrip(directory, "TRIP-1", {
      riderId: "RIDER-1",
      fromStationId: "STATION-ELM",
      toStationId: "STATION-PINE",
    });

    expect(trip.rider.phone).toBe("555-0199");
  });

  // Guards against a correction reaching further than its own rider - the scope this
  // refactoring must not widen while fixing how updates propagate within it.
  it("never touches a different rider's trip", () => {
    const directory = openDirectory();
    registerRider(directory, {
      id: "RIDER-1",
      name: "Priya Shah",
      phone: "555-0100",
      email: "priya@example.com",
    });
    registerRider(directory, {
      id: "RIDER-2",
      name: "Owen Bramwell",
      phone: "555-0200",
      email: "owen@example.com",
    });
    const otherTrip = bookTrip(directory, "TRIP-2", {
      riderId: "RIDER-2",
      fromStationId: "STATION-OAK",
      toStationId: "STATION-BIRCH",
    });

    correctRiderPhone(directory, "RIDER-1", "555-0199");

    expect(otherTrip.rider.phone).toBe("555-0200");
  });

  // Sentinel: correcting an unregistered rider is a safe no-op, not a thrown error or a
  // silent registration.
  it("does nothing when the rider id is not in the directory", () => {
    const directory = openDirectory();

    expect(() => correctRiderPhone(directory, "RIDER-GHOST", "555-0199")).not.toThrow();
    expect(findRider(directory, "RIDER-GHOST")).toBeUndefined();
  });
});
