import { describe, expect, it } from "vitest";
import { doseMg, volumeMl, type DrugProfile } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after introducing the assertion. Do not edit this file: if a refactoring seems to
 * require changing a test, either the refactoring changed behaviour or the exercise is
 * wrong.
 *
 * There is one test per behaviour a plausible Introduce Assertion could silently change -
 * not one per drug. Each test names the move it is guarding against.
 *
 * Note what is deliberately absent: no test here constructs a DrugProfile with a
 * non-positive concentration to watch the assertion fire. WALKTHROUGH.md explains why that
 * absence is the point, not a gap - the short version is that a value a test can construct
 * on purpose is exactly the kind of value that isn't cannot-happen any more.
 */

const amoxicillin: DrugProfile = {
  name: "Amoxicillin",
  mgPerKg: 25,
  concentrationMgPerMl: 50,
};

describe("doseMg", () => {
  // Guards against the per-kg rate being applied to the wrong operand, or dropped.
  it("multiplies weight by the drug's mg-per-kg rate", () => {
    expect(doseMg(20, amoxicillin)).toBe(500);
  });

  // Boundary: the daily cap must actually bind for a large enough patient.
  it("caps the dose at the daily limit for a heavy patient", () => {
    expect(doseMg(300, amoxicillin)).toBe(4000);
  });

  // Sentinel: a weight of zero or below is not a real patient and must be rejected before
  // any arithmetic runs on it, not silently turned into a dose of zero.
  it("rejects a non-positive weight", () => {
    expect(() => doseMg(0, amoxicillin)).toThrow(/plausible weight/u);
    expect(() => doseMg(-4, amoxicillin)).toThrow(/plausible weight/u);
  });

  // Sentinel: a weight far past anything a human patient could have is treated as a data
  // entry mistake, not a very large dose.
  it("rejects a weight past the plausible ceiling", () => {
    expect(() => doseMg(450, amoxicillin)).toThrow(/plausible weight/u);
  });
});

describe("volumeMl", () => {
  // Guards against a rewrite that divides the raw weight-times-rate figure instead of the
  // capped dose - the two only differ once the daily cap has actually bound.
  it("divides the dose, not the raw weight-times-rate figure, by the concentration", () => {
    const heavyPatientVolume = volumeMl(300, amoxicillin);
    expect(heavyPatientVolume).toBeCloseTo(4000 / 50);
  });

  // The everyday case: a plausible weight and a well-formed formulary entry produce a
  // plausible, non-throwing volume.
  it("computes the volume to draw up for an ordinary dose", () => {
    expect(volumeMl(20, amoxicillin)).toBeCloseTo(500 / 50);
  });

  // volumeMl calls doseMg internally - this weight must still be rejected here too, not
  // just when doseMg is called directly.
  it("still rejects a non-positive weight when computing a volume", () => {
    expect(() => volumeMl(0, amoxicillin)).toThrow(/plausible weight/u);
  });
});
