import { describe, expect, it } from "vitest";
import {
  Member,
  canBorrowMore,
  formatLoanLimitLine,
  holdQueueCapacity,
  isApproachingLoanLimit,
  remainingLoanAllowance,
  totalBranchLoanCapacity,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of hiding the chain behind Member. Do not edit this file:
 * if a refactoring seems to require changing a test, either the refactoring changed
 * behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Hide Delegate could silently change - not
 * one per function. Each test names the move it is guarding against.
 */

const priya = new Member({
  id: "M-1042",
  name: "Priya Chandran",
  tierName: "standard",
  memberSince: "2021-06-15",
});
const owen = new Member({
  id: "M-2091",
  name: "Owen Bramwell",
  tierName: "family",
  memberSince: "2019-01-03",
});
const ada = new Member({
  id: "M-3007",
  name: "Ada Level",
  tierName: "senior",
  memberSince: "2015-09-30",
});

describe("canBorrowMore", () => {
  // Guards the strict inequality: a member exactly at their limit cannot borrow more.
  it("allows another loan below the limit and refuses one at it", () => {
    expect(canBorrowMore(priya, 4)).toBe(true);
    expect(canBorrowMore(priya, 5)).toBe(false);
  });
});

describe("remainingLoanAllowance", () => {
  // Guards the ordinary subtraction surviving the move from a chain to a query.
  it("subtracts what is on loan from the tier's limit", () => {
    expect(remainingLoanAllowance(owen, 3)).toBe(7);
  });

  // Guards the floor at zero - a tier downgrade could leave a member over their new
  // limit, and the allowance must never read as negative.
  it("floors at zero for a member already over their limit", () => {
    expect(remainingLoanAllowance(priya, 8)).toBe(0);
  });
});

describe("formatLoanLimitLine", () => {
  // Guards the exact wording and the number substituted into it.
  it("names the member and their tier's loan limit", () => {
    expect(formatLoanLimitLine(owen)).toBe("Owen Bramwell: loan limit 10");
  });
});

describe("isApproachingLoanLimit", () => {
  // Guards the boundary in both directions - one item below flags, two does not.
  it("flags a member one item away from their limit but not two", () => {
    expect(isApproachingLoanLimit(ada, 7)).toBe(true);
    expect(isApproachingLoanLimit(ada, 6)).toBe(false);
  });
});

describe("holdQueueCapacity", () => {
  // Guards the multiplier - a query that only forwarded the limit would return the
  // wrong number here without the "* 2" surviving the move.
  it("doubles the member's loan limit", () => {
    expect(holdQueueCapacity(priya)).toBe(10);
    expect(holdQueueCapacity(owen)).toBe(20);
  });
});

describe("totalBranchLoanCapacity", () => {
  // Guards the accumulation across a mix of tiers, once per member.
  it("sums every member's loan limit once each", () => {
    expect(totalBranchLoanCapacity([priya, owen, ada])).toBe(23);
  });

  // Guards the empty case, where reduce's initial value is the only thing returned.
  it("returns zero for a branch with no members", () => {
    expect(totalBranchLoanCapacity([])).toBe(0);
  });
});
