import { describe, expect, it } from "vitest";
import {
  describeCourse,
  describeWithPrerequisite,
  seatsRemaining,
  type CourseCatalogue,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the lookup's signature is exactly
 * what you are changing. So the suite pins the three *callers* - `describeCourse`,
 * `seatsRemaining`, `describeWithPrerequisite` - and says nothing about the lookup
 * function underneath, by name or by shape. Rename it, drop its parameter, delegate
 * through a second function while you migrate - none of that can turn this suite red,
 * because it never had the old (or new) signature to depend on in the first place. Only a
 * change to what a caller actually returns or throws can.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

const spring: CourseCatalogue = {
  season: "Spring 2026",
  courses: [
    { code: "5K-BASE", title: "Beginner 5K", capacity: 20, prerequisiteCode: null },
    {
      code: "SPEED-END",
      title: "Speed Endurance",
      capacity: 12,
      prerequisiteCode: "5K-BASE",
    },
    {
      code: "ADV-TRACK",
      title: "Advanced Track",
      capacity: 8,
      prerequisiteCode: "GHOST-101",
    },
  ],
};

const summer: CourseCatalogue = {
  season: "Summer 2026",
  courses: [
    { code: "5K-BASE", title: "Beginner 5K", capacity: 25, prerequisiteCode: null },
  ],
};

const winter: CourseCatalogue = { season: "Winter 2026", courses: [] };

describe("describeCourse", () => {
  it("formats the title and capacity of a course that exists", () => {
    expect(describeCourse(spring, "5K-BASE")).toBe("Beginner 5K (20 places)");
  });

  // Guards against the season in the error message drifting away from the catalogue
  // that was actually passed - the exact tell that the old `season` parameter was
  // provably redundant, and the exact way a careless removal could go wrong.
  it("throws naming the missing code and the catalogue's own season", () => {
    expect(() => describeCourse(spring, "YOGA-101")).toThrow(
      'No course "YOGA-101" in the Spring 2026 catalogue.',
    );
  });

  // Same behaviour, a different catalogue. If a refactor ever hardcodes or memoizes the
  // season instead of reading it off the catalogue argument, this is the test that catches
  // it - the message above alone could pass by coincidence.
  it("reports a different season for a different catalogue", () => {
    expect(() => describeCourse(summer, "YOGA-101")).toThrow(
      'No course "YOGA-101" in the Summer 2026 catalogue.',
    );
  });

  // Guards the empty case: no courses to search still has a season to report.
  it("throws correctly against a catalogue with no courses at all", () => {
    expect(() => describeCourse(winter, "5K-BASE")).toThrow(
      'No course "5K-BASE" in the Winter 2026 catalogue.',
    );
  });
});

describe("seatsRemaining", () => {
  it("subtracts enrolled from capacity", () => {
    expect(seatsRemaining(spring, "5K-BASE", 14)).toBe(6);
  });

  // Guards against a "helpful" clamp to zero creeping in during the refactor - an
  // overbooked course is a real, reportable state, not an error to hide.
  it("allows a negative result when a course is overbooked", () => {
    expect(seatsRemaining(spring, "SPEED-END", 15)).toBe(-3);
  });
});

describe("describeWithPrerequisite", () => {
  it("returns the bare title when there is no prerequisite", () => {
    expect(describeWithPrerequisite(spring, "5K-BASE")).toBe("Beginner 5K");
  });

  it("names the prerequisite's title when there is one", () => {
    expect(describeWithPrerequisite(spring, "SPEED-END")).toBe(
      "Speed Endurance (requires Beginner 5K)",
    );
  });

  // Guards the two lookup call sites against being merged or swapped: the error must
  // name the missing *prerequisite* code, not the course that referenced it.
  it("throws naming the prerequisite's own code when the prerequisite is missing", () => {
    expect(() => describeWithPrerequisite(spring, "ADV-TRACK")).toThrow(
      'No course "GHOST-101" in the Spring 2026 catalogue.',
    );
  });
});
