import { describe, expect, it } from "vitest";
import {
  refundForBulkCancellation,
  refundForSelfServiceCancellation,
  refundForSupportDeskCancellation,
  type Booking,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the whole point of Replace Parameter
 * with Query is that a signature changes - `refundAmountCents` stops taking a day count
 * and starts taking the moment of cancellation instead. So this suite imports only the
 * three callers - `refundForSelfServiceCancellation`, `refundForSupportDeskCancellation`,
 * `refundForBulkCancellation` - and never the refund calculation by name. It pins what a
 * cancellation at a given moment is worth; it says nothing about how many arguments the
 * function underneath takes to work that out.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

const MS_PER_DAY = 1000 * 60 * 60 * 24;

function booking(seatPriceCents: number, showDate: Date): Booking {
  return { id: "B-1", seatPriceCents, showDate };
}

function daysBeforeShow(showDate: Date, days: number): Date {
  return new Date(showDate.getTime() - days * MS_PER_DAY);
}

const SHOW_DATE = new Date(Date.UTC(2026, 5, 20));

describe("refundForSelfServiceCancellation", () => {
  it("refunds in full at exactly the 14-day cutoff", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, 14);
    expect(refundForSelfServiceCancellation(booking(6000, SHOW_DATE), cancelledAt)).toBe(
      6000,
    );
  });

  // Guards against a cutoff that drifts by one day when the comparison is rewritten.
  it("drops to a half refund one day inside the full-refund cutoff", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, 13);
    expect(refundForSelfServiceCancellation(booking(6000, SHOW_DATE), cancelledAt)).toBe(
      3000,
    );
  });

  it("still gives a half refund at exactly the 3-day cutoff", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, 3);
    expect(refundForSelfServiceCancellation(booking(6000, SHOW_DATE), cancelledAt)).toBe(
      3000,
    );
  });

  // Guards against the lower cutoff drifting the same way the upper one could.
  it("drops to no refund one day inside the partial-refund cutoff", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, 2);
    expect(refundForSelfServiceCancellation(booking(6000, SHOW_DATE), cancelledAt)).toBe(
      0,
    );
  });

  // Guards against treating "the show already happened" as a positive day count.
  it("refunds nothing once the show date has already passed", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, -1);
    expect(refundForSelfServiceCancellation(booking(6000, SHOW_DATE), cancelledAt)).toBe(
      0,
    );
  });

  // Guards against truncating instead of rounding when a half refund isn't a whole cent.
  it("rounds a half refund to the nearest cent", () => {
    const cancelledAt = daysBeforeShow(SHOW_DATE, 10);
    expect(refundForSelfServiceCancellation(booking(4999, SHOW_DATE), cancelledAt)).toBe(
      2500,
    );
  });
});

// Guards against the two front-door callers drifting apart once only one of them is
// moved onto the new signature.
it("refundForSupportDeskCancellation agrees with self-service for the same moment", () => {
  const cancelledAt = daysBeforeShow(SHOW_DATE, 5);
  const theBooking = booking(6000, SHOW_DATE);

  expect(refundForSupportDeskCancellation(theBooking, cancelledAt)).toBe(
    refundForSelfServiceCancellation(theBooking, cancelledAt),
  );
});

describe("refundForBulkCancellation", () => {
  // Guards against every booking in the batch being scored against the first booking's
  // show date instead of its own.
  it("scores each booking against its own show date, not the first one's", () => {
    const cancelledAt = new Date(Date.UTC(2026, 5, 1));
    // 2 days out - inside the no-refund window.
    const soonShow = booking(6000, new Date(Date.UTC(2026, 5, 3)));
    // 29 days out - well past the full-refund cutoff.
    const farShow = booking(6000, new Date(Date.UTC(2026, 5, 30)));

    expect(refundForBulkCancellation([soonShow, farShow], cancelledAt)).toEqual([
      0, 6000,
    ]);
  });

  it("returns an empty list for an empty batch", () => {
    expect(refundForBulkCancellation([], SHOW_DATE)).toEqual([]);
  });
});
