import { describe, expect, it } from "vitest";
import { renderPacingReport, type SplitLog } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file: if a refactoring seems to require
 * changing a test, either the refactoring changed behaviour or the exercise is wrong.
 *
 * A rename cannot change behaviour, so these tests cannot tell a good rename from a bad
 * one - that job belongs to a reader, not the suite. What they pin down instead is the
 * arithmetic itself: the exact formula the mysterious names are hiding, so a rename that
 * quietly guesses wrong about what a variable *is* still gets caught, the same way any
 * other accidental behaviour change would.
 */

describe("renderPacingReport", () => {
  // Guards the whole shape, and the case where the formula gives its cleanest possible
  // answer: identical segment paces mean zero spread.
  it("reports zero spread for a session paced identically every kilometre", () => {
    const evenTempo: SplitLog = {
      runner: "Ana Ferreira",
      session: "Tuesday tempo, 2026-04-14",
      checkpoints: [
        { markerKm: 1, elapsedSeconds: 240 },
        { markerKm: 2, elapsedSeconds: 480 },
        { markerKm: 3, elapsedSeconds: 720 },
      ],
    };

    expect(renderPacingReport(evenTempo)).toBe(
      [
        "Ana Ferreira - Tuesday tempo, 2026-04-14",
        "  1km  4:00/km",
        "  2km  4:00/km",
        "  3km  4:00/km",
        "",
        "Average pace: 4:00/km",
        "Pacing spread: ±0s/km",
        "Consistency: Even",
      ].join("\n"),
    );
  });

  // Guards the actual formula, not just its shape: this is the population standard
  // deviation of the three paces (200, 260, 180 s/km), which is ±34s/km. A substitute
  // that averages the absolute deviations from the mean instead - a very plausible
  // near-miss - gives a different number (±26.7, rounding to ±27), so this test would
  // catch that swap even though both "look like" a spread.
  it("computes the pacing spread as the population standard deviation of segment paces", () => {
    const surge: SplitLog = {
      runner: "Bruno Costa",
      session: "Wednesday fartlek, 2026-04-15",
      checkpoints: [
        { markerKm: 1, elapsedSeconds: 200 },
        { markerKm: 2, elapsedSeconds: 460 },
        { markerKm: 3, elapsedSeconds: 640 },
      ],
    };

    expect(renderPacingReport(surge)).toBe(
      [
        "Bruno Costa - Wednesday fartlek, 2026-04-15",
        "  1km  3:20/km",
        "  2km  4:20/km",
        "  3km  3:00/km",
        "",
        "Average pace: 3:33/km",
        "Pacing spread: ±34s/km",
        "Consistency: Uneven",
      ].join("\n"),
    );
  });

  // Guards the `?? 0` fallback: a session's first checkpoint has no previous checkpoint
  // in the log, and its pace must be measured from the start line (0 km, 0 s), not left
  // undefined or divided against the wrong marker.
  it("measures the first segment from the start line, not from a missing previous checkpoint", () => {
    const lateMat: SplitLog = {
      runner: "Late Mat",
      session: "First mat at 2km",
      checkpoints: [{ markerKm: 2, elapsedSeconds: 500 }],
    };

    expect(renderPacingReport(lateMat)).toContain("2km  4:10/km");
  });

  // Guards against a segment calculation that assumes every marker is exactly 1km apart.
  // The gap between the first two markers here is 2km, not 1.
  it("divides by the actual distance between markers, not a fixed one kilometre", () => {
    const unevenGaps: SplitLog = {
      runner: "Gappy",
      session: "Uneven marker gaps",
      checkpoints: [
        { markerKm: 1, elapsedSeconds: 200 },
        { markerKm: 3, elapsedSeconds: 620 },
        { markerKm: 4, elapsedSeconds: 830 },
      ],
    };

    const lines = renderPacingReport(unevenGaps).split("\n");
    expect(lines[1]).toBe("  1km  3:20/km");
    expect(lines[2]).toBe("  3km  3:30/km");
    expect(lines[3]).toBe("  4km  3:30/km");
  });

  // Guards the single-element case: with one segment, the mean of squares equals the
  // square of the mean exactly, so the spread must come out to zero, not `NaN` from a
  // formula that divides by `count - 1` or otherwise mishandles n = 1.
  it("reports zero spread for a session with a single recorded kilometre", () => {
    const solo: SplitLog = {
      runner: "Celia Nunes",
      session: "Solo km, 2026-04-16",
      checkpoints: [{ markerKm: 1, elapsedSeconds: 300 }],
    };

    expect(renderPacingReport(solo)).toContain("Pacing spread: ±0s/km");
  });

  // Guards the even/uneven boundary from below: a spread of exactly 8s/km - the
  // threshold - still counts as evenly paced, so the comparison must be `<=`, not `<`.
  it("counts a spread exactly at the threshold as evenly paced", () => {
    const atThreshold: SplitLog = {
      runner: "Boundary Runner",
      session: "Threshold test",
      checkpoints: [
        { markerKm: 1, elapsedSeconds: 200 },
        { markerKm: 2, elapsedSeconds: 416 },
      ],
    };

    expect(renderPacingReport(atThreshold)).toContain("Consistency: Even");
  });

  // Guards the same boundary from above: one second of spread past the threshold flips
  // the verdict to uneven.
  it("counts a spread just past the threshold as unevenly paced", () => {
    const justOver: SplitLog = {
      runner: "Boundary Runner",
      session: "Threshold test",
      checkpoints: [
        { markerKm: 1, elapsedSeconds: 200 },
        { markerKm: 2, elapsedSeconds: 417 },
      ],
    };

    expect(renderPacingReport(justOver)).toContain("Consistency: Uneven");
  });

  // Guards rounding versus truncation in the pace formatter. 163.5 s/km sits exactly
  // between two seconds; truncating (Math.floor) prints 2:43, rounding prints 2:44.
  it("rounds a half-second pace up rather than truncating it", () => {
    const halfSecond: SplitLog = {
      runner: "Rounder",
      session: "Half-second pace",
      checkpoints: [{ markerKm: 1, elapsedSeconds: 163.5 }],
    };

    expect(renderPacingReport(halfSecond)).toContain("1km  2:44/km");
  });
});
