import { describe, expect, it } from "vitest";
import {
  raisePriceBands,
  raiseRestrictedViewBand,
  raiseStandardBand,
  RESTRICTED_VIEW_CODE,
  type PriceBand,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`: merging three raise functions into one is a
 * signature change by definition, so the suite pins the *callers* the box office's sales
 * system actually calls - `raiseStandardBand`, `raiseRestrictedViewBand`, and
 * `raisePriceBands` - and says nothing about how many functions sit behind them or what
 * they are named.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

const stalls: PriceBand = { code: "A", name: "Stalls", pricePounds: 60 };

describe("raiseStandardBand", () => {
  // Guards the tier-to-amount mapping itself. Merging the three raise functions into
  // one is only safe if every tier still lands on the same amount it did before.
  it("raises by the flat amount its demand tier calls for", () => {
    expect(raiseStandardBand(stalls, "low").pricePounds).toBe(65);
    expect(raiseStandardBand(stalls, "medium").pricePounds).toBe(70);
    expect(raiseStandardBand(stalls, "high").pricePounds).toBe(80);
  });

  // Guards against the restricted-view ceiling leaking into the merged function and
  // capping every band it touches, standard bands included.
  it("does not cap a standard band even past what would be the restricted-view ceiling", () => {
    const circle: PriceBand = { code: "B", name: "Circle", pricePounds: 50 };
    expect(raiseStandardBand(circle, "high").pricePounds).toBe(70);
  });

  // Guards against a refactor that rebuilds the returned band from scratch instead of
  // spreading the original - only the price should move.
  it("changes only the price, leaving the band's code and name untouched", () => {
    const raised = raiseStandardBand(
      { code: "C", name: "Grand Circle", pricePounds: 40 },
      "medium",
    );
    expect(raised.code).toBe("C");
    expect(raised.name).toBe("Grand Circle");
    expect(raised.pricePounds).toBe(50);
  });
});

describe("raiseRestrictedViewBand", () => {
  const restrictedView = (pricePounds: number): PriceBand => ({
    code: RESTRICTED_VIEW_CODE,
    name: "Rear Circle Restricted View",
    pricePounds,
  });

  // Guards against a merge that clamps every restricted-view raise on principle,
  // whether or not the tier's amount would actually cross the ceiling.
  it("raises normally while there is headroom under the ceiling", () => {
    expect(raiseRestrictedViewBand(restrictedView(20), "low").pricePounds).toBe(25);
  });

  // This is the whole point of the exercise: the ceiling is a rule the domain cares
  // about, not a fourth literal that happens to fit the raiseByFive/Ten/Twenty family.
  it("clamps at the ceiling when the tier's rise would cross it", () => {
    expect(raiseRestrictedViewBand(restrictedView(30), "high").pricePounds).toBe(45);
  });

  // Guards the boundary itself: landing exactly on the ceiling must not be nudged
  // further down by an off-by-one in the clamp comparison.
  it("lands exactly on the ceiling without dropping below it", () => {
    expect(raiseRestrictedViewBand(restrictedView(25), "high").pricePounds).toBe(45);
  });
});

describe("raisePriceBands", () => {
  // Guards the case a per-band merge is most likely to get wrong: a mixed rack, where
  // only the restricted-view band should ever see the ceiling.
  it("raises every band in a rack, capping only the restricted-view one", () => {
    const raised = raisePriceBands(
      [stalls, { code: RESTRICTED_VIEW_CODE, name: "Rear Circle", pricePounds: 30 }],
      "high",
    );
    expect(raised[0]?.pricePounds).toBe(80);
    expect(raised[1]?.pricePounds).toBe(45);
  });

  // Guards the empty rack, where there is no band to route anywhere.
  it("leaves an empty rack empty", () => {
    expect(raisePriceBands([], "medium")).toEqual([]);
  });
});
