/**
 * Regenerates every file in the repository that is derived from the exercises'
 * meta.json: the three READMEs, the catalog and smell indexes, and the per-exercise
 * tsconfig that teaches `tsc` about the `@exercise` alias.
 *
 *   npm run index            rewrite the generated files
 *   npm run index -- --check fail if anything on disk is out of date (used by CI)
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import process from "node:process";
import {
  ROOT,
  catalogNames,
  discoverExercises,
  smellNames,
  type Exercise,
} from "./lib/exercises.ts";
import {
  MODULES,
  difficultyDots,
  exerciseLink,
  table,
  translationFlags,
} from "./lib/render.ts";

const GENERATED = "<!-- generated by `npm run index` - do not edit by hand -->";

const exercises = discoverExercises();
const catalog = catalogNames();
const smells = smellNames();

const covered = new Set(exercises.flatMap((exercise) => exercise.meta.refactorings));
const coverage = `${String(catalog.filter((name) => covered.has(name)).length)}/${String(catalog.length)}`;

interface Strings {
  lang: "en" | "pt";
  switcher: string;
  tagline: string;
  disclaimer: string;
  what: string;
  quickStart: string;
  progress: string;
  headers: string[];
  empty: string;
  more: string;
}

const EN: Strings = {
  lang: "en",
  switcher: "🌐 **English** · [🇧🇷 Português](./README.pt.md)",
  tagline:
    "Hands-on exercises for *Refactoring: Improving the Design of Existing Code*, 2nd edition, in TypeScript.",
  disclaimer:
    "> Unofficial practice material. Not affiliated with Martin Fowler or the publisher, and it contains none of the book's code or prose. **The book is a prerequisite**, not something this repository replaces.",
  what: [
    "Every exercise is a small program that already works, a test suite that is already green, and one named refactoring to apply. The tests are your safety net and they never change; the solution is a diary of micro-steps, not a finished file.",
    "",
    "**Drills** name the refactoring for you and train the mechanics. **Katas** hand you realistic code and let you find the smell yourself.",
  ].join("\n"),
  quickStart: "Quick start",
  progress: `**Catalog coverage: ${coverage} refactorings.**`,
  headers: ["Exercise", "Refactoring", "Smells", "Level", "Min", "Lang"],
  empty: "_No exercises in this module yet._",
  more: "Where to go next",
};

const PT: Strings = {
  lang: "pt",
  switcher: "[🌐 English](./README.en.md) · 🇧🇷 **Português**",
  tagline:
    "Exercícios práticos do livro *Refactoring: Improving the Design of Existing Code*, 2ª edição, em TypeScript.",
  disclaimer:
    "> Material de prática não oficial. Sem vínculo com Martin Fowler ou a editora, e sem nenhum trecho de código ou texto do livro. **O livro é pré-requisito**, não algo que este repositório substitua.",
  what: [
    "Cada exercício é um programa pequeno que já funciona, uma suíte de testes que já está verde e um refactoring nomeado para aplicar. Os testes são a sua rede de segurança e nunca mudam; a solução é um diário de micro-passos, não um arquivo pronto.",
    "",
    "Os **drills** dizem qual refactoring aplicar e treinam a mecânica. Os **katas** entregam código realista e deixam você encontrar o smell sozinho.",
  ].join("\n"),
  quickStart: "Começando",
  progress: `**Cobertura do catálogo: ${coverage} refactorings.**`,
  headers: ["Exercício", "Refactoring", "Smells", "Nível", "Min", "Idioma"],
  empty: "_Nenhum exercício neste módulo ainda._",
  more: "Por onde seguir",
};

function moduleSection(strings: Strings, chapter: number, title: string): string {
  const rows = exercises
    .filter((exercise) => exercise.meta.chapter === chapter)
    .map((exercise) => [
      exerciseLink(exercise, strings.lang),
      exercise.meta.refactorings.join(", "),
      exercise.meta.smells.join(", "),
      difficultyDots(exercise.meta.difficulty),
      String(exercise.meta.estimatedMinutes),
      translationFlags(exercise),
    ]);
  const body = rows.length > 0 ? table(strings.headers, rows) : strings.empty;
  return `### Chapter ${String(chapter)} — ${title}\n\n${body}`;
}

function readme(strings: Strings): string {
  return [
    GENERATED,
    "",
    strings.switcher,
    "",
    "# refactoring-practice",
    "",
    strings.tagline,
    "",
    strings.disclaimer,
    "",
    strings.what,
    "",
    `## ${strings.quickStart}`,
    "",
    "```bash",
    "npm install",
    "npm start -- drill-06-01     # print the brief and run the suite in watch mode",
    "npm run diff -- drill-06-01  # compare with the published solutions (once green)",
    "```",
    "",
    "## Exercises",
    "",
    strings.progress,
    "",
    ...MODULES.map(
      (module) => `${moduleSection(strings, module.chapter, module.title)}\n`,
    ),
    `## ${strings.more}`,
    "",
    "- [How to practice](./docs/HOW-TO-PRACTICE.md)",
    "- [Catalog coverage](./docs/CATALOG.md) · [Smell index](./docs/SMELLS.md)",
    "- [Design notes](./docs/DESIGN.md) · [Contributing](./CONTRIBUTING.md)",
    "",
    "MIT licensed.",
    "",
  ].join("\n");
}

function catalogDoc(): string {
  const byRefactoring = new Map<string, Exercise[]>();
  for (const exercise of exercises) {
    for (const name of exercise.meta.refactorings) {
      byRefactoring.set(name, [...(byRefactoring.get(name) ?? []), exercise]);
    }
  }
  const rows = catalog.map((name) => {
    const hits = byRefactoring.get(name) ?? [];
    return [
      name,
      hits.length > 0 ? "✅" : "⬜",
      hits.map((exercise) => exerciseLink(exercise, "en", "../")).join(", ") || "—",
    ];
  });
  return [
    GENERATED,
    "",
    "# Catalog coverage",
    "",
    "Every refactoring in the second edition, and the exercise that drills it.",
    "",
    `**${coverage} covered.**`,
    "",
    table(["Refactoring", "", "Exercise"], rows),
    "",
  ].join("\n");
}

function smellsDoc(): string {
  const rows = smells.map((smell) => {
    const hits = exercises.filter((exercise) => exercise.meta.smells.includes(smell));
    return [
      smell,
      hits.map((exercise) => exerciseLink(exercise, "en", "../")).join(", ") || "—",
    ];
  });
  return [
    GENERATED,
    "",
    "# Smell index",
    "",
    "Arrived with a real problem instead of an open chapter? Start here.",
    "",
    table(["Smell (chapter 3)", "Exercises"], rows),
    "",
  ].join("\n");
}

/**
 * Teaches `tsc` the same `@exercise` alias that vitest.config.ts sets up.
 *
 * Written as a literal rather than JSON.stringify so the output matches oxfmt's
 * formatting exactly - otherwise `npm run index -- --check` and `oxfmt --check` would
 * disagree with each other forever.
 */
function exerciseTsconfig(exercise: Exercise): string {
  const toRoot = path.relative(exercise.dir, ROOT).split(path.sep).join("/");
  return [
    "{",
    `  "extends": "${toRoot}/tsconfig.base.json",`,
    '  "compilerOptions": {',
    '    "paths": {',
    '      "@exercise": ["./src/index.ts"]',
    "    }",
    "  },",
    '  "include": ["src/**/*.ts", "tests/**/*.ts", "solutions/**/*.ts"]',
    "}",
    "",
  ].join("\n");
}

const outputs = new Map<string, string>([
  ["README.en.md", readme(EN)],
  ["README.pt.md", readme(PT)],
  ["README.md", readme(EN)],
  ["docs/CATALOG.md", catalogDoc()],
  ["docs/SMELLS.md", smellsDoc()],
  ...exercises.map(
    (exercise) =>
      [`${exercise.relDir}/tsconfig.json`, exerciseTsconfig(exercise)] as const,
  ),
]);

const check = process.argv.includes("--check");
const stale: string[] = [];

for (const [relPath, content] of outputs) {
  const absolute = path.join(ROOT, relPath);
  if (check) {
    let current = "";
    try {
      current = readFileSync(absolute, "utf8");
    } catch {
      current = "";
    }
    if (current !== content) stale.push(relPath);
  } else {
    writeFileSync(absolute, content);
  }
}

if (check) {
  if (stale.length > 0) {
    console.error("✗ generated files are out of date:");
    for (const file of stale) console.error(`  ${file}`);
    console.error("\n  run `npm run index` and commit the result.");
    process.exit(1);
  }
  console.log(`✓ ${String(outputs.size)} generated files are up to date`);
} else {
  console.log(`✓ wrote ${String(outputs.size)} generated files`);
}
