import { describe, expect, it } from "vitest";
import { LessonArchive, type Lesson } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of replacing LessonArchive's superclass with a delegate.
 * Do not edit this file: if a refactoring seems to require changing a test, either the
 * refactoring changed behaviour or the exercise is wrong.
 *
 * There is one test per behaviour a plausible Replace Superclass with Delegate could
 * silently change - not one per method. Each test names the move it is guarding against.
 *
 * This file never calls insertAt, removeAt, or replaceAt: those are exactly the methods
 * this drill's target removes, so a shared suite that has to stay green against both the
 * challenge and the solution cannot reference them at all - see tests-fixed/ for the one
 * behaviour only the fixed version can even be asked about.
 */

const priya: Lesson = { id: "L-1", student: "Priya Shah", completedOn: "2026-03-02" };
const owen: Lesson = { id: "L-2", student: "Owen Clarke", completedOn: "2026-03-03" };
const mabel: Lesson = { id: "L-3", student: "Mabel Ives", completedOn: "2026-03-05" };

describe("LessonArchive", () => {
  // Guards the empty case, where there is no first entry to reach for.
  it("starts empty", () => {
    const archive = new LessonArchive();
    expect(archive.entries()).toEqual([]);
    expect(archive.count()).toBe(0);
  });

  // Guards a single archived lesson surviving with every field intact - not just its id.
  it("holds one archived lesson exactly as it was given", () => {
    const archive = new LessonArchive();
    archive.add(priya);
    expect(archive.entries()).toEqual([priya]);
  });

  // Guards insertion order over any accidental sort, since an archive is a chronological
  // record, not a ranking.
  it("keeps completed lessons in the order they were archived, not sorted", () => {
    const archive = new LessonArchive();
    archive.add(mabel);
    archive.add(priya);
    archive.add(owen);
    expect(archive.entries()).toEqual([mabel, priya, owen]);
  });

  // Guards count matching the number of entries even as more are added one at a time -
  // the usual casualty of a count that is cached instead of read from the entries.
  it("counts entries as they are added", () => {
    const archive = new LessonArchive();
    expect(archive.count()).toBe(0);
    archive.add(priya);
    expect(archive.count()).toBe(1);
    archive.add(owen);
    expect(archive.count()).toBe(2);
  });

  // Guards two archives never sharing storage - a real risk once storage moves from an
  // inherited instance field to a delegate object that could, by mistake, be shared or
  // created once at the module level instead of once per archive.
  it("keeps two archives independent of each other", () => {
    const first = new LessonArchive();
    const second = new LessonArchive();
    first.add(priya);
    expect(first.count()).toBe(1);
    expect(second.count()).toBe(0);
    expect(second.entries()).toEqual([]);
  });

  // Guards a longer run of adds all landing in the archive, not just the first and last -
  // the usual casualty of an off-by-one in whatever replaces a simple push.
  it("archives every lesson across a longer run of adds", () => {
    const archive = new LessonArchive();
    for (const lesson of [priya, owen, mabel]) {
      archive.add(lesson);
    }
    expect(archive.entries().map((entry) => entry.id)).toEqual(["L-1", "L-2", "L-3"]);
    expect(archive.count()).toBe(3);
  });
});
