import { describe, expect, it } from "vitest";
import { CatalogueItem, findByKey, renderCatalogueIndex } from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step of inlining the key-wrapping class. Do not edit this file:
 * if a refactoring seems to require changing a test, either the refactoring changed
 * behaviour or the exercise is wrong.
 *
 * Inline Class should be invisible from out here - every test below passes unchanged
 * whether the key lives in a wrapper object or a plain string. That invisibility is the
 * whole point: it is what makes it safe to delete the wrapper.
 */

const theSaltPath = new CatalogueItem({
  key: "FIC-2024-0091",
  title: "The Salt Path",
  author: "Raynor Winn",
});
const circe = new CatalogueItem({
  key: "FIC-2019-0002",
  title: "Circe",
  author: "Madeline Miller",
});
const braidingSweetgrass = new CatalogueItem({
  key: "NONFIC-2023-0007",
  title: "Braiding Sweetgrass",
  author: "Robin Wall Kimmerer",
});
const dictionary = new CatalogueItem({
  key: "REF-2020-0001",
  title: "Concise Oxford Dictionary",
  author: "OUP",
});

describe("renderCatalogueIndex", () => {
  // Guards section grouping, section ordering, and the sort-by-key within a section
  // surviving the move from a wrapped key to a plain one.
  it("groups items by section, sections sorted, items sorted by key within each", () => {
    const items = [theSaltPath, dictionary, circe, braidingSweetgrass];
    expect(renderCatalogueIndex(items)).toBe(
      [
        "FIC",
        "  FIC-2019-0002  Circe — Madeline Miller",
        "  FIC-2024-0091  The Salt Path — Raynor Winn",
        "NONFIC",
        "  NONFIC-2023-0007  Braiding Sweetgrass — Robin Wall Kimmerer",
        "REF",
        "  REF-2020-0001  Concise Oxford Dictionary — OUP",
      ].join("\n"),
    );
  });

  // Guards the empty case, where there is no first section to reach for.
  it("says so plainly when nothing is catalogued yet", () => {
    expect(renderCatalogueIndex([])).toBe("No items catalogued.");
  });

  // Guards the single-item, single-section case rendering without a stray blank line.
  it("renders a single item under its own section with no extra lines", () => {
    expect(renderCatalogueIndex([dictionary])).toBe(
      ["REF", "  REF-2020-0001  Concise Oxford Dictionary — OUP"].join("\n"),
    );
  });

  // Guards sort stability: two items sharing an exact key (a duplicate entry, the kind
  // a real catalogue occasionally has) must keep their original relative order rather
  // than being reordered by an unstable comparator.
  it("keeps items with an identical key in the order they were entered", () => {
    const copyA = new CatalogueItem({
      key: "FIC-2024-0091",
      title: "Copy A",
      author: "X",
    });
    const copyB = new CatalogueItem({
      key: "FIC-2024-0091",
      title: "Copy B",
      author: "X",
    });
    const rows = renderCatalogueIndex([copyA, copyB]).split("\n").slice(1);
    expect(rows[0]).toContain("Copy A");
    expect(rows[1]).toContain("Copy B");
  });

  // Guards section() against a key with no separator - the fallback branch that only a
  // type predicate or a `?? ""` protects, and easy to lose when the split moves files.
  it("treats a key with no section separator as its own, whole section", () => {
    const misc = new CatalogueItem({
      key: "MISC",
      title: "Odds and Ends",
      author: "Unknown",
    });
    expect(renderCatalogueIndex([misc])).toBe(
      ["MISC", "  MISC  Odds and Ends — Unknown"].join("\n"),
    );
  });
});

describe("findByKey", () => {
  const items = [theSaltPath, circe, braidingSweetgrass];

  // Guards matchesKey staying an equality check, not a lookup that survives on an
  // allocation nobody needs any more.
  it("finds the item whose key matches exactly", () => {
    expect(findByKey(items, "FIC-2019-0002")).toBe(circe);
  });

  it("returns undefined when no item's key matches", () => {
    expect(findByKey(items, "FIC-2019-9999")).toBeUndefined();
  });

  // Guards against a careless inline turning `===` into a prefix or substring check -
  // a key that merely starts with a valid key must not count as a match.
  it("does not match a key that is only a prefix of a real one", () => {
    expect(findByKey(items, "FIC-2019")).toBeUndefined();
  });
});
