import { describe, expect, it } from "vitest";
import {
  explainTopBlock,
  rankSeatBlocks,
  type GroupRequest,
  type Row,
  type SeatBlock,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`: the whole point of Replace Function with
 * Command is that the thing being scored changes shape - a function in the challenge, a
 * class in the solution. So this suite imports only the two callers - `rankSeatBlocks`
 * and `explainTopBlock` - and never the scorer by name.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

function row(
  rowNumber: number,
  seatCount: number,
  options: { held?: readonly number[]; aisleAfterNumber?: number | null } = {},
): Row {
  const held = new Set(options.held ?? []);
  return {
    rowNumber,
    seats: Array.from({ length: seatCount }, (_, i) => ({
      number: i + 1,
      isHeld: held.has(i + 1),
    })),
    aisleAfterNumber: options.aisleAfterNumber ?? null,
  };
}

function block(
  theRow: Row,
  firstSeatNumber: number,
  lastSeatNumber: number,
  pricePerSeatPounds: number,
): SeatBlock {
  return { row: theRow, firstSeatNumber, lastSeatNumber, pricePerSeatPounds };
}

describe("explainTopBlock", () => {
  it("picks the block that combines location, price and the aisle bonus best", () => {
    const gala = row(12, 11, { aisleAfterNumber: 5 });
    const request: GroupRequest = { targetPricePounds: 50 };
    const central = block(gala, 6, 8, 50);
    const cheapButOffCenterAndUnderpriced = block(gala, 1, 3, 20);

    expect(explainTopBlock([cheapButOffCenterAndUnderpriced, central], request)).toBe(
      "Row 12 seats 6-8: location +19, price +15, aisle +5 (total 39)",
    );
  });

  // Guards the empty case, where there is no top block to explain.
  it("has nothing to explain when there are no candidate blocks", () => {
    const request: GroupRequest = { targetPricePounds: 50 };
    expect(explainTopBlock([], request)).toBeNull();
  });

  // Guards a phase that clamps its own factor before the combine step runs, instead of
  // clamping only the final total. The breakdown should still report what actually drove
  // the score to zero.
  it("floors the total at zero but still reports the honest breakdown that produced it", () => {
    const wideRow = row(9, 21, { held: [1, 5] });
    const request: GroupRequest = { targetPricePounds: 100 };
    const farAndFragmented = block(wideRow, 3, 3, 0);

    expect(explainTopBlock([farAndFragmented], request)).toBe(
      "Row 9 seats 3-3: location +12, price +0, fragmentation -16 (total 0)",
    );
  });
});

describe("rankSeatBlocks", () => {
  // Guards a sort comparator that stops being stable once ties are possible.
  it("keeps equally-scored blocks in the order they were given", () => {
    const evenRow = row(4, 11);
    const request: GroupRequest = { targetPricePounds: 50 };
    const left = block(evenRow, 1, 3, 50);
    const right = block(evenRow, 9, 11, 50);

    expect(rankSeatBlocks([left, right], request)).toEqual([left, right]);
  });

  // Guards against the location factor being dropped or its weight changed while the
  // other three factors are held equal.
  it("prefers a block closer to the row's centre when nothing else differs", () => {
    const straightRow = row(7, 11);
    const request: GroupRequest = { targetPricePounds: 50 };
    const centred = block(straightRow, 5, 7, 50);
    const edge = block(straightRow, 1, 3, 50);

    expect(rankSeatBlocks([edge, centred], request)).toEqual([centred, edge]);
  });

  // Guards against the price factor being dropped or computed against the wrong field.
  it("prefers a block priced closer to the group's target when nothing else differs", () => {
    const straightRow = row(3, 11);
    const request: GroupRequest = { targetPricePounds: 50 };
    const matched = block(straightRow, 1, 3, 50);
    const mismatched = block(straightRow, 9, 11, 30);

    expect(rankSeatBlocks([mismatched, matched], request)).toEqual([matched, mismatched]);
  });

  // Guards against the aisle bonus being applied to the wrong edge of the block, or lost
  // entirely, while location and price are held equal.
  it("rewards a block that sits against the aisle when everything else is equal", () => {
    const aisleRow = row(3, 11, { aisleAfterNumber: 5 });
    const request: GroupRequest = { targetPricePounds: 50 };
    const onAisle = block(aisleRow, 6, 8, 50);
    const offAisle = block(aisleRow, 4, 6, 50);

    expect(rankSeatBlocks([offAisle, onAisle], request)).toEqual([onAisle, offAisle]);
  });

  // Guards against merging the fragmentation check into the location check, or dropping
  // it while extracting the phases into methods.
  it("penalizes a block that strands a single open seat next to it", () => {
    const fragmentingRow = row(6, 11, { held: [5] });
    const request: GroupRequest = { targetPricePounds: 50 };
    const strandsSeatFour = block(fragmentingRow, 1, 3, 50);
    const clean = block(fragmentingRow, 9, 11, 50);

    expect(rankSeatBlocks([strandsSeatFour, clean], request)).toEqual([
      clean,
      strandsSeatFour,
    ]);
  });
});
