import { describe, expect, it } from "vitest";
import {
  renderCustomReport,
  renderMonthReport,
  renderSeasonToDate,
  type Season,
} from "@exercise";

/**
 * Characterization tests. They are green before you touch anything and they must stay
 * green after every micro-step. Do not edit this file.
 *
 * This exercise declares `apiFrozen: false`, because the signatures below the surface are
 * exactly what you are changing. So the suite pins the three *callers* - the entry points
 * the club's tooling calls - and says nothing about how they reach the report. Every
 * signature between here and the bottom of the module is yours to rewrite.
 *
 * One test per behaviour a plausible refactoring could silently change; each names the
 * move it guards against.
 */

const season: Season = {
  club: "Silverbrook AC",
  year: 2026,
  opensOn: "2026-03-01",
  races: [
    { name: "Riverbank 10K", date: "2026-04-05", distanceKm: 10 },
    { name: "Silverbrook Half Marathon", date: "2026-03-14", distanceKm: 21.1 },
    { name: "Coldwater Fell Race", date: "2026-05-24", distanceKm: 12 },
    { name: "Ashgrove Marathon", date: "2026-06-07", distanceKm: 42.2 },
  ],
};

function withRaces(races: Season["races"]): Season {
  return { ...season, races };
}

describe("renderCustomReport", () => {
  it("reports the window the secretary asked for", () => {
    expect(renderCustomReport(season, "2026-03-01", "2026-05-31")).toBe(
      [
        "Silverbrook AC - 2026 season",
        "2026-03-01 to 2026-05-31 (92 days)",
        "2026-03-14  Silverbrook Half Marathon      21.1 km",
        "2026-04-05  Riverbank 10K                  10.0 km",
        "2026-05-24  Coldwater Fell Race            12.0 km",
        "Races: 3",
        "Distance: 43.1 km",
        "Weekly average: 3.3 km",
        "Longest: Silverbrook Half Marathon (21.1 km)",
      ].join("\n"),
    );
  });

  // Guards the closed interval. A range object makes `from <= date <= to` a single
  // method, and a single method is a single place to get the comparison wrong.
  it("includes races on both end days and excludes the days either side", () => {
    const report = renderCustomReport(
      withRaces([
        { name: "One day early", date: "2026-03-31", distanceKm: 5 },
        { name: "On the from day", date: "2026-04-01", distanceKm: 5 },
        { name: "On the to day", date: "2026-04-30", distanceKm: 5 },
        { name: "One day late", date: "2026-05-01", distanceKm: 5 },
      ]),
      "2026-04-01",
      "2026-04-30",
    );

    expect(report).toContain("On the from day");
    expect(report).toContain("On the to day");
    expect(report).not.toContain("One day early");
    expect(report).not.toContain("One day late");
  });

  // Guards against a comparator that stops being stable when the filter and the sort
  // are rearranged - two races on one day must stay in entry order.
  it("lists races by date, and keeps same-day races in the order they were entered", () => {
    const report = renderCustomReport(
      withRaces([
        { name: "Evening 3K", date: "2026-04-05", distanceKm: 3 },
        { name: "Morning 5K", date: "2026-04-05", distanceKm: 5 },
        { name: "Opening Mile", date: "2026-04-01", distanceKm: 1.6 },
      ]),
      "2026-04-01",
      "2026-04-30",
    ).split("\n");

    expect(report[2]).toContain("Opening Mile");
    expect(report[3]).toContain("Evening 3K");
    expect(report[4]).toContain("Morning 5K");
  });

  // Guards the tie in the longest-race scan: first by date wins, which a switch to
  // sort-and-take-last would silently reverse.
  it("names the earlier race when two are equally long", () => {
    const report = renderCustomReport(
      withRaces([
        { name: "April Ten", date: "2026-04-10", distanceKm: 10 },
        { name: "April Two", date: "2026-04-02", distanceKm: 10 },
      ]),
      "2026-04-01",
      "2026-04-30",
    );

    expect(report).toContain("Longest: April Two (10.0 km)");
  });

  // Guards the empty window, where there is no race to be longest.
  it("omits the longest line for a window nobody raced in", () => {
    expect(renderCustomReport(season, "2026-01-01", "2026-01-07")).toBe(
      [
        "Silverbrook AC - 2026 season",
        "2026-01-01 to 2026-01-07 (7 days)",
        "Races: 0",
        "Distance: 0.0 km",
        "Weekly average: 0.0 km",
      ].join("\n"),
    );
  });

  // Guards the day count and the division by it: seven days is one week exactly, so the
  // weekly average must equal the distance. Counting days exclusively would give 6/7.
  it("counts both end days, so a seven-day window averages its own distance", () => {
    const report = renderCustomReport(
      withRaces([{ name: "Solo 10K", date: "2026-04-03", distanceKm: 10 }]),
      "2026-04-01",
      "2026-04-07",
    );

    expect(report).toContain("2026-04-01 to 2026-04-07 (7 days)");
    expect(report).toContain("Weekly average: 10.0 km");
  });

  // Guards against tidying the column into a truncation. Long names push the row out.
  it("lets a race name wider than its column overflow instead of being cut", () => {
    const report = renderCustomReport(
      withRaces([
        {
          name: "Silverbrook Midsummer Night Ultramarathon",
          date: "2026-04-04",
          distanceKm: 50,
        },
      ]),
      "2026-04-01",
      "2026-04-30",
    );

    expect(report).toContain(
      "2026-04-04  Silverbrook Midsummer Night Ultramarathon 50.0 km",
    );
  });
});

describe("renderMonthReport", () => {
  // Guards the month-to-window arithmetic, which is the caller's hand-rolled bit: April
  // ends on the 30th, and the last month of the year must not roll into the next one.
  it("spans the whole calendar month, whatever length it is", () => {
    expect(renderMonthReport(season, "2026-04")).toContain(
      "2026-04-01 to 2026-04-30 (30 days)",
    );
    expect(renderMonthReport(season, "2026-12")).toContain(
      "2026-12-01 to 2026-12-31 (31 days)",
    );
    expect(renderMonthReport(season, "2024-02")).toContain(
      "2024-02-01 to 2024-02-29 (29 days)",
    );
  });

  it("reports only the races run inside that month", () => {
    expect(renderMonthReport(season, "2026-04")).toBe(
      [
        "Silverbrook AC - 2026 season",
        "2026-04-01 to 2026-04-30 (30 days)",
        "2026-04-05  Riverbank 10K                  10.0 km",
        "Races: 1",
        "Distance: 10.0 km",
        "Weekly average: 2.3 km",
        "Longest: Riverbank 10K (10.0 km)",
      ].join("\n"),
    );
  });
});

describe("renderSeasonToDate", () => {
  // Guards the one window whose start comes from the season rather than the caller.
  it("runs from the day the season opened up to and including today", () => {
    const report = renderSeasonToDate(season, "2026-04-30");

    expect(report).toContain("2026-03-01 to 2026-04-30 (61 days)");
    expect(report).toContain("Races: 2");
    expect(report).not.toContain("Coldwater Fell Race");
  });
});
